### ISSUE TITLE
Spigot #1543 1.7.9 - Pex error

### ISSUE THREAD

**Issue by KVPEK** [PEXPlugins/PermissionsEx#1809]
### Description ###

[Insert description of issue here]
### Detailed Information ###
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
at ru.tehkode.permissions.RegExpMatcher.(RegExpMatcher.java:17)
at ru.tehkode.permissions.PermissionManager.(PermissionManager.java:58)
at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:476)
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:394)
at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:360)
at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:334)
at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:290)
at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:194)
at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:458)
at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[Is available here](https://gist.github.com/2264698f3b2ac0b5fa3c)

**Comment by Skin0x** [comment]
Same error !! :x

**Comment by Stormbow** [comment]
Don't use PermissionsEx 1.23, which is //only// for 1.8 bukkit servers, on your 1.7.x server.
