### ISSUE TITLE
HELLP

### ISSUE THREAD

**Issue by Skin0x** [PEXPlugins/PermissionsEx#1812]
### Description ###
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

[20:49:20 INFO]: Done (3.476s)! For help, type "help" or "?"

### Detailed Information ###

[Is available here](https://gist.github.com/767c0cb24f29b70a8128)

**Comment by Stormbow** [comment]
Don't use PermissionsEx 1.23, which is //only// for 1.8 bukkit servers, on your 1.7.x server.
