### ISSUE TITLE
Pex timed out but my port 80 is open

### ISSUE THREAD

**Issue by AwaaX** [PEXPlugins/PermissionsEx#1822]
[19:43:33] [Thread-10/ERROR]: [PermissionsEx] null
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.7.0_65]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[?:1.7.0_65]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[?:1.7.0_65]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[?:1.7.0_65]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.7.0_65]
        at java.net.Socket.connect(Socket.java:579) ~[?:1.7.0_65]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618) ~[?:1.7.0_65]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.7.0_65]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.7.0_65]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.7.0_65]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[?:1.7.0_65]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[?:1.7.0_65]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.7.0_65]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932) ~[?:1.7.0_65]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.7.0_65]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300) ~[?:1.7.0_65]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.7.0_65]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.read(Updater.java:643) [PermissionsEx.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.runUpdater(Updater.java:718) [PermissionsEx.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.access$100(Updater.java:36) [PermissionsEx.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater$UpdateRunnable.run(Updater.java:713) [PermissionsEx.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

**Comment by AwaaX** [comment]
How can I resolve that ?

**Comment by zml2008** [comment]
What do you mean "my port 80 is open"? outgoing connections have a randomized source port. even if java *didn't* properly clean up connections this is not something that could really happen

**Comment by AwaaX** [comment]
So why it do that ?

**Comment by zml2008** [comment]
You're getting the error that you're seeing because your server couldn't reach dev.bukkit.org for some reason

**Comment by AwaaX** [comment]
up

**Comment by AwaaX** [comment]
Can you answer ?

**Comment by zml2008** [comment]
It's your server's internet connection, not my problem.
