### ISSUE TITLE
I updated pex to the 1.8.1 version 

### ISSUE THREAD

**Issue by yoshy112** [PEXPlugins/PermissionsEx#1823]
i had an issue with pex braking after 6 months of it working perfectly, i was told it did not work due to my spigot.jar using a 1.7 hack even though its version is 1.8.

so i updated pex as soon as the new version came out, and it has now given me this error:

 [PermissionsEx] Disabling PermissionsEx v1.23
[21:11:52 INFO]: WEPIF: Using the Bukkit Permissions API.
[21:11:52 INFO]: [Vault][Permission] PermissionsEx un-hooked.
[21:11:52 INFO]: Essentials: Using PermissionsEx based permissions.
[21:11:52 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PluginDisableEvent to Essentials v2.13.1
org.bukkit.event.EventException
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1641]
        at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-1641]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-1641]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) [spigot.jar:git-Spigot-1641]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:271) [PermissionsEx.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [spigot.jar:git-Spigot-1641]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1641]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-1641]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:73) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommands.onCommand(PlugManCommands.java:100) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1641]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1641]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753) [spigot.jar:git-Spigot-1641]
        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326) [spigot.jar:git-Spigot-1641]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290) [spigot.jar:git-Spigot-1641]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1641]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1641]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1641]
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
        at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:393) ~[?:?]
        at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17) ~[?:?]
        at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:109) ~[?:?]
        at com.earth2me.essentials.EssentialsPluginListener.onPluginDisable(EssentialsPluginListener.java:48) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]

**Comment by Stormbow** [comment]
PEX 1.23 is not for 1.7.x servers.  Download a different version and read the release notes.
