### ISSUE TITLE
PEX isn't working whatsoever

### ISSUE THREAD

**Issue by asmith123** [PEXPlugins/PermissionsEx#1828]
I'm starting a server, and when I downloaded PEX and did /pl, the text that said PermissionsEX was red. I didn't even touch the config.yml at all. Infact, it didn't even generate the PermissionsEX folder. Please help me. My OS is mac.

**Comment by Stormbow** [comment]
What version is the server and what version of PEX are you using?

**Comment by zml2008** [comment]
Do you get any errors while starting up the server? Which version of PEX are you using? Which version of your server are you using (/version)

**Comment by asmith123** [comment]
The version i am using for the SERVER is CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
My PEX version is 1.23
![screen shot 2015-01-06 at 7 11 15 am](https://cloud.githubusercontent.com/assets/10407803/5628318/4a3d25e6-9573-11e4-8b54-f96c15d5cf85.png)
And this is the error I get whilst starting it:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;

at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)

at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)

at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)

at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)

at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)

at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)

at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)

at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)

at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by Stormbow** [comment]
Pex 1.23 is not for your server version.  You need to download a different  version.  Be sure to read the release notes.

**Comment by asmith123** [comment]
Thank you so much!
