### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by GXGamer** [PEXPlugins/PermissionsEx#1830]
### Detailed Information ###

Basic info

Server version: 1.7.5-R0.1-SNAPSHOT running on git-Spigot-1387 (MC: 1.7.8)

Plugins (9): (Strikeout means disabled)

kFlameHG v1.6 (me.flame.hg.Main)
JBorder v1.0 (Pl.Borda.Pandora.BordaLibsHG)
ProtocolLib v3.4.0 (com.comphenix.protocol.ProtocolLibrary)
PermissionsEx v1.23 (ru.tehkode.permissions.bukkit.PermissionsEx)
pAntiAura v0.1-SNAPSHOT (tk.maciekmm.antiaura.AntiAura)
TerrainControl v2.6.0 (com.khorn.terraincontrol.bukkit.TCPlugin)
fAntiHax v0.0.1 (me.flame.antihax.AntiHax)
Reporter v3.2.6 (net.KabOOm356.Reporter.Reporter)
UltimatePluginUpdater v4 (net.stormdev.bukkitmods.ultimatepluginupdater.main.main)
What PEX Saw

Reason: Error while enabling:

Stacktrace:

java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
    at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
    at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:462)
    at org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:380)
    at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:353)
    at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:328)
    at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:284)
    at net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:186)
    at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:442)
    at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)

**Comment by Stormbow** [comment]
Solved:  PEX 1.23 is not for 1.7.5 servers.  Read the release notes.  Download a different version of PEX.
