### ISSUE TITLE
Server Issue After ModifyWorld

### ISSUE THREAD

**Issue by Death-Blade-RSX** [PEXPlugins/PermissionsEx#1831]
### Description ###

I put ModifyWorld on to my server after PEX had been loaded due to having forgot about it. Then I got this error...
[06:21:22] [pool-22-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/eRxkiA. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
	at org.bukkit.Bukkit.reload(Bukkit.java:301)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
	at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

Pls help

[Is available here](https://gist.github.com/03e35d7f2dc85dbd68d8)

**Comment by Stormbow** [comment]
PEX 1.23 is not for 1.7.10 servers. Download a different version; read the release notes.
