### ISSUE TITLE
Issue D: Part 2

### ISSUE THREAD

**Issue by xXTheBetXx** [PEXPlugins/PermissionsEx#1836]
### Description ###
Here is the error, it's the same than the other.

[18:58:12 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post
 it to http://git.io/dZmBQQ. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)
Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.jav
a:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.ja
va:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:417)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
a:476)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
java:394)
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:3
60)
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:3
34)
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:2
90)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.jav
a:210)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28)

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/8f67a0568bc679b800eb)

**Comment by xXTheBetXx** [comment]
Oh sorry I resolved the issue

**Comment by Stormbow** [comment]
No, zml resolved this issue.  You're not running an actual 1.8 server; you're using the protocol hack put out by Spigot.
