### ISSUE TITLE
[PermissionsEx] Error

### ISSUE THREAD

**Issue by cschellenberger** [PEXPlugins/PermissionsEx#1840]
### Error occurred with PermissionsEx! ###

[Error occurred with PermissionsEx!]
### java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352)
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326)
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282)
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) ###

[Is available here](https://gist.github.com/202c3aeb507f1625893b)

**Comment by Stormbow** [comment]
PEX 1.23 is not for your server version.  Download one that is; read the release notes.
