### ISSUE TITLE
HELP!!! PLeasepleaseplease

### ISSUE THREAD

**Issue by mineforce6883** [PEXPlugins/PermissionsEx#1842]
### Description ###

I had this Problem since like 2 months ago and i still couldn't fix it.
I added the PermissionsEX Executable Jar file into the plugins folder and started up the server.
But there is no Pex folder!
here is the Log-
### Detailed Information ###
[10:58:15] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.22.7-SNAPSHOT
[10:58:15] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.22.7-SNAPSHOT
[10:58:15] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:58:15] [Server thread/INFO]: Done (4.618s)! For help, type "help" or "?"
[10:58:16] [pool-4-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/hrpQcg. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[Is available here](https://gist.github.com/39d7b3b5bd876615d4af)

**Comment by zml2008** [comment]
You're using PEX 1.23, which is only compatible with 1.8 servers, on a 1.7 server. Use 1.22.6 instead.
