### ISSUE TITLE
Thread.java:745 when adding user with metacharacter

### ISSUE THREAD

**Issue by Immaridel** [PEXPlugins/PermissionsEx#1862]
### Description ###
java.lang.Thread.run(Thread.java:745) when running pex against user with underscore in name
/pex user jaykob_lussier group set Member

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/2d8748e8816442bad012)

**Comment by Stormbow** [comment]
Do you get the same error when you enter the username within quotation marks?
/pex user "jaykob_lussier" group set Member

**Comment by Immaridel** [comment]
I did, yes.  This may be a non-issue, however.  I just had to bounce my
server for another issue, and when we came back up this issue was no longer
occurring.  I was having to work on a several plugins to setup some
configurations, so it's possible that I encountered a problem after
reloading one of them and it all went downhill from there.

The two things I unsuccessfully attempted when it was a problem, however,
were to enter the name as "jaykob_lussier" and "jaykob\_lussier".  Not sure
if you can escape a control character from the mc command line, but it was
worth a try I suppose.

Thanks for looking at this.  Not sure if it's worth investing time into
since it's working now.  I can certainly just upload additional data later
if it happens again.

**Comment by KennosiS** [comment]
I have the same problem and it throws an exception, the user is Baron_PAPIMAFIA, 15 chars and underscored sign. He was on a timed group on previous version and with this version it expired and now have problems.

http://pastebin.com/bpyzg3gj

and 

[15:18:00] [Server thread/INFO]: Alphabravo9 issued server command: /pex user "Baron_PAPIMAFIA" group set Usuario
[15:18:00] [Server thread/INFO]: Héroe
[15:18:01] [pool-13-thread-1/WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.github.com/gists
[15:18:01] [pool-13-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
[15:18:01] [pool-13-thread-1/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[15:18:01] [pool-13-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport.gistText(ErrorReport.java:120)
[15:18:01] [pool-13-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport$Builder.build(ErrorReport.java:372)
[15:18:01] [pool-13-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport.withException(ErrorReport.java:328)
[15:18:01] [pool-13-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport$2.run(ErrorReport.java:193)
[15:18:01] [pool-13-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[15:18:01] [pool-13-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[15:18:01] [pool-13-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[15:18:01] [pool-13-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[15:18:01] [pool-13-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by zml2008** [comment]
Not been able to get any actual stacktraces from users due to the fact that the commands system has issues. Not really worth the time to invest in a system that is going to be trashed anyway.
