### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by jknetwork** [PEXPlugins/PermissionsEx#1865]
### Description ###

java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'name' in 'field list'
	at ru.tehkode.permissions.backends.sql.SQLBackend.getEntityNames(SQLBackend.java:332)
	at ru.tehkode.permissions.backends.sql.SQLBackend.getGroupNames(SQLBackend.java:360)
	at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:432)
	at ru.tehkode.permissions.PermissionManager.preloadGroups(PermissionManager.java:518)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:607)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:176)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'name' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.permissions.backends.sql.SQLData.getEntitiesNames(SQLData.java:385)
	at ru.tehkode.permissions.backends.sql.SQLBackend.getEntityNames(SQLBackend.java:327)
	... 18 more

### Detailed Information ###

My Pex Config:

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: true
  createUserRecords: true
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://*********.de/********_permissions
      user: ********_pex
      password: ***********************
      aliases:
        permissions: testserver_permissions
        permissions_inheritance: testserver_inheritance
        permissions_entity: testserver_entity
updater: true
alwaysUpdate: false

[Is available here](https://gist.github.com/482a1f709f38ae3d02f8)

**Comment by zml2008** [comment]
You have an invalid database schema for some reason. Make sure updates didn't fail in the past.
