### ISSUE TITLE
Uh. Help? (PermissionsEX issue, won't load)

### ISSUE THREAD

**Issue by block4447** [PEXPlugins/PermissionsEx#1867]
### Description ###

When I turn on my server or reload plugins, Pex gets an error and spews the detailed information at me.

### Detailed Information ###
2015-01-21T19:22:32.139360170Z 
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:647)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.util.Waitable.run(Waitable.java:24)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.MinecraftServer$1.evaluate(MinecraftServer.java:951)
2015-01-21T19:22:32.139360170Z 	at net.minecraft.server.v1_7_R4.MinecraftServer$1.evaluate(MinecraftServer.java:960)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.Bukkit.reload(Bukkit.java:301)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
2015-01-21T19:22:32.139360170Z 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
2015-01-21T19:22:32.139360170Z 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
2015-01-21T19:22:32.139360170Z 	at ru.tehkode.permissions.PermissionManager.(PermissionManager.java:58)
2015-01-21T19:22:32.139360170Z 	at ru.tehkode.permissions.RegExpMatcher.(RegExpMatcher.java:17)
2015-01-21T19:22:32.139360170Z java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
2015-01-21T19:22:32.139360170Z >
[19:22:32 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/Idfx4Q. Full error:
2015-01-21T19:22:32.071365437Z >

[Is available here](https://gist.github.com/a4bb4a58b8ae2bf83dd8)

**Comment by Stormbow** [comment]
Download PEX 1.22.6 and see if you still have the same error.

**Comment by zml2008** [comment]
This is from trying to use the incorrect PEX version for your MC version
