### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by XibrenX** [PEXPlugins/PermissionsEx#1899]
### Description ###
NoSuchMethodError occured in PermissionsEx

[Insert description of issue here]
### Detailed Information ###
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I) Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.jav
a:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.ja
va:159)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.jav
a:356)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.
java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:4
02)
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:3
70)
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:3
25)
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.jav
a:211)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:505)
        at java.lang.Thread.run(Unknown Source)

[Is available here](https://gist.github.com/7e3caa04a8839c315e11)

**Comment by Stormbow** [comment]
Guava needs to be updated.  Use PEX 1.23.
