### ISSUE TITLE
Can't use the plugin because of this

### ISSUE THREAD

**Issue by alepalma** [PEXPlugins/PermissionsEx#1900]
Whenever I start the server I get this error:

[18:19:53] [pool-5-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/NjOX. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
        at java.lang.Thread.run(Thread.java:745)

Here's the full log just in case: http://pastebin.com/6K3TJzre

**Comment by Stormbow** [comment]
Guava update required.
