### ISSUE TITLE
PermissionsEx Error

### ISSUE THREAD

**Issue by TheFrecyboy** [PEXPlugins/PermissionsEx#1915]
### Description ###

[16:43:34] [pool-9-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/xGeX. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:187)
	at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
	at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:193)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:476)
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:394)
	at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:360)
	at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:334)
	at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:290)
	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:194)
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:458)
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:162)
	... 24 more
### Detailed Information ###

[Is available here](https://gist.github.com/9487e84dca05777c6be1)

**Comment by Stormbow** [comment]
I think this is a matter of you having 2 "schema-version" lines in your SQL entries.  As far as I know, the correct version is "schema-version: 1".

**Comment by zml2008** [comment]
Yeah, you have to correct the schema version to 1 or whatever it is -- I don't currently have the sql backend in front of me (though I'll have to dig that up eventually to reimplement it for Sponge).
