### ISSUE TITLE
Error when using on offline user

### ISSUE THREAD

**Issue by Kyle1264x** [PEXPlugins/PermissionsEx#1928]
### Description ###

[Insert description of issue here]
when doing a command on an offline user, we get an error code

java.lang.RuntimeException: java.lang.NullPointerException
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:117)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:316)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:631)
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

[Is available here](https://gist.github.com/eec34549ff754408cabe)

**Comment by Stormbow** [comment]
Here are some problem areas I can immediately identify:
• vTeamCity produces a shoddy/bad plugin.  You should only use the official Essentials download.
• You have incorrectly weighted a large number of your groups as "1".  The weight value is to determine which group has priority in such things as displaying a prefix in chat.  Groups can't all be the same weight.
• You have many, many, many permissions which are not permissions at all.  Things such as "swag" and "nickname" and usernames.  Take a look at group C for a perfect example of what I'm talking about, and look at all of the groups after that for the same errors.  Putting fictitious permission nodes in the file won't break anything, but it makes your file unnecessarily long and can contribute to lag issues.
• Consider using inheritance to shorten your permissions.yml file and using the cleanup command to remove some of the users who have quit playing on the server.  Your permissions.yml file is over 10,000 lines long.
• You have many permissions which do not even exist; one example being in group C which has essentials.bal which is not a permission node according to the Essentials permission nodes page.
• According to your permissions.yml file, you don't have a user named "nintendude" to use any commands on.

**Comment by zml2008** [comment]
This bug is not of sufficient severity and frequentness to warrant the effort required to fix it. Please wait for the rewrite of PEX to be ready (available for Sponge/Forge servers).
