### ISSUE TITLE
PermissionsEx Not Working?

### ISSUE THREAD

**Issue by Aqaos** [PEXPlugins/PermissionsEx#1929]
### PermissionsEx not working? ###

[[23:00:30 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post
 it to http://git.io/pq6f. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)
Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.jav
a:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.ja
va:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:417)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
a:476)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
java:394)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:86
6)
        at org.bukkit.Bukkit.reload(Bukkit.java:301)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
23)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
1)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServe
r.java:767)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(Craf
tServer.java:753)
        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:
326)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:2
90)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:5
84)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:490)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28)]

**Comment by Stormbow** [comment]
You're using the wrong version of PEX with your 1.7.x server.  Read the release notes to find the correct version of PEX for your server in the future.  (1.22.7 is what you should be using.)
