### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AndresMC54** [PEXPlugins/PermissionsEx#1932]
Hello, i need help please!,I got this error: 

2015-03-08 13:24:57 [SEVERE] [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F173cc131278d49fcb7ae%29%0A. Full error:
java.lang.IllegalArgumentException: Null or empty name passed! Name must not be empty
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:110)
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:135)
	at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:50)
	at ru.tehkode.permissions.bukkit.SuperpermsListener.onPlayerLogin(SuperpermsListener.java:146)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
	at net.minecraft.server.v1_5_R3.PlayerList.attemptLogin(PlayerList.java:332)
	at net.minecraft.server.v1_5_R3.PendingConnection.d(PendingConnection.java:120)
	at net.minecraft.server.v1_5_R3.PendingConnection.c(PendingConnection.java:44)
	at net.minecraft.server.v1_5_R3.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:41)
	at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:29)
	at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:57

**Comment by macdja38** [comment]
You must fill in a password for your sql server in the config.

**Comment by AndresMC54** [comment]
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}


And where I do that ?.

**Comment by macdja38** [comment]
Sorry I completely misread part of the error, what version of pex and what version of spigot/bukkit/other are you using?

**Comment by AndresMC54** [comment]
I bukkit 1.5.2 and pex version I use is 1.20.4, Before using the version 1.19.6, i need help please.

**Comment by zml2008** [comment]
Can't help you if you're using incredibly outdated versions of both Bukkit and PEX.

**Comment by AndresMC54** [comment]
Please, i need help :(
