### ISSUE TITLE
Error occurred with PermissionsEx!

### ISSUE THREAD

**Issue by CathalCraft** [PEXPlugins/PermissionsEx#1938]
Spigot 1.8 git-Spigot-c3c767f-33d5de3
PEX v1.23

PEX v1.23.1 doesn't rank users correctly so I use 1.23.

[PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/pKYB. Full error:
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:247)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.isPermissionSet(PermissiblePEX.java:201)
	at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.isPermissionSet(CraftHumanEntity.java:94)
	at com.earth2me.essentials.perm.SuperpermsHandler.hasPermission(SuperpermsHandler.java:40)
	at com.earth2me.essentials.perm.PermissionsExHandler.hasPermission(PermissionsExHandler.java:83)
	at com.earth2me.essentials.perm.PermissionsHandler.hasPermission(PermissionsHandler.java:82)
	at com.earth2me.essentials.User.isAuthorizedCheck(User.java:102)
	at com.earth2me.essentials.User.isAuthorized(User.java:84)
	at com.earth2me.essentials.utils.FormatUtil.formatMessage(FormatUtil.java:53)
	at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:47)
	at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1036)
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:975)
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
	at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
Always read the release notes. ;)

**Comment by CathalCraft** [comment]
What do you mean? I always read the release notes. I don't understand how they would help.

**Comment by FenixFire613** [comment]
I'm having the same problem on my server, and I've also read the release notes.  What should I do?  Please help!!! ty!
