### ISSUE TITLE
Error upon joining

### ISSUE THREAD

**Issue by TWSSYesterday** [PEXPlugins/PermissionsEx#1941]
### Description ###

[Insert description of issue here]
Occurs when someone joins the server

[17:21:19] [Server thread/INFO]: Ne0nInheriterTFM[/68.2.81.181:46980] logged in with entity id 8 at ([flat]253.5, 36.0, 1391.5)
[17:21:30] [pool-21-thread-1/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists
[17:21:30] [pool-21-thread-1/WARN]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
[17:21:30] [pool-21-thread-1/WARN]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
[17:21:30] [pool-21-thread-1/WARN]:     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[17:21:30] [pool-21-thread-1/WARN]:     at ru.tehkode.permissions.bukkit.ErrorReport.gistText(ErrorReport.java:120)
[17:21:30] [pool-21-thread-1/WARN]:     at ru.tehkode.permissions.bukkit.ErrorReport$Builder.build(ErrorReport.java:372)
[17:21:30] [pool-21-thread-1/WARN]:     at ru.tehkode.permissions.bukkit.ErrorReport.withException(ErrorReport.java:328)
[17:21:30] [pool-21-thread-1/WARN]:     at ru.tehkode.permissions.bukkit.ErrorReport$2.run(ErrorReport.java:193)
[17:21:30] [pool-21-thread-1/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:21:30] [pool-21-thread-1/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:21:30] [pool-21-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:21:30] [pool-21-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:21:30] [pool-21-thread-1/WARN]:     at java.lang.Thread.run(Thread.java:745)
[17:21:30] [pool-21-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/_14rzA. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.checkLocked(slot_lock.java:402)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.onPlayerInteract(slot_lock.java:205)
        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226)
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193)
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189)
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:692)
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:714)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:655)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:558)
        at java.lang.Thread.run(Thread.java:745)

**Comment by TWSSYesterday** [comment]
Using latest version (PermissionsEx v1.23.1) on latest Spigot (1.8.3)

**Comment by zml2008** [comment]
slot_lock is broken. Talk to the slot_lock dev. That plugin has been present in the stacktraces of a lot of people encountering this issue.

**Comment by TWSSYesterday** [comment]
Thanks, can't believe I missed something that obvious...
