### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MiisterNarsik** [PEXPlugins/PermissionsEx#1954]
### Description ###

>pex user Caiprina group set builder
[17:52:06 INFO]: Error occurred with PermissionsEx! Please post it to http://git.io/julM. Full error:
java.lang.RuntimeException: java.lang.NullPointerException
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:117)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:316)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

**Comment by zml2008** [comment]
unable to reproduce. make sure your server is in online mode and you're running recent versions of everything else on your server.
