### ISSUE TITLE
Exception when using Banmanager tab complete

### ISSUE THREAD

**Issue by EvilOlaf** [PEXPlugins/PermissionsEx#1956]
### Description ###
- Have a Server with Spigot 1.8, Pex 1.23.1 and BanManager 5.2.0
- Get yourself proper permissions to use /ban
- Enter /ban and hit tabulator
- An exception appears

### Detailed Information ###
```
[08:56:27 ERROR]: Permission name cannot be null
java.lang.IllegalArgumentException: Permission name cannot be null
        at org.bukkit.permissions.PermissibleBase.isPermissionSet(PermissibleBase.java:50) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:135) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at me.confuser.banmanager.commands.AutoCompleteNameTabCommand.onTabComplete(AutoCompleteNameTabCommand.java:24) ~[BanManager.jar:?]
        at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:387) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.tabCompleteCommand(CraftServer.java:1586) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.tabComplete(CraftServer.java:1570) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1116) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1869) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInTabComplete.a(SourceFile:46) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInTabComplete.a(SourceFile:10) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[08:56:28 INFO]: [PermissionsEx] User Olaf checked for permission 'modifyworld.mobtarget.monster.enderdragon', regex-matched a value of true from cache.
[08:56:28 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/j2LG. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
        at me.confuser.banmanager.commands.AutoCompleteNameTabCommand.onTabComplete(AutoCompleteNameTabCommand.java:24)
        at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:387)
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.tabCompleteCommand(CraftServer.java:1586)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.tabComplete(CraftServer.java:1570)
        at net.minecraft.server.v1_8_R1.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1116)
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1869)
        at net.minecraft.server.v1_8_R1.PacketPlayInTabComplete.a(SourceFile:46)
        at net.minecraft.server.v1_8_R1.PacketPlayInTabComplete.a(SourceFile:10)
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Thread.java:745)
```

CraftBukkit version git-Spigot-ed3e3af-ee6d0fa

Actually I don't wanna to publicize my whole plugin and permission setup. If needed leave me a message in IRC at the user Krauti2.
Thanks for reading.

**Comment by zml2008** [comment]
This is a bug in BanManager.

**Comment by confuser** [comment]
For others viewing this issue. The issue is within Spigot, and not BanManager.
