### ISSUE TITLE
ConcurrentModificationException in 1.22.7

### ISSUE THREAD

**Issue by ItsHarry** [PEXPlugins/PermissionsEx#1960]
Hello

Sometimes, PEX throws a ConcurrentModificationException when calling player.hasPermission() from an alternate thread. This is the same issue as #1399 

So, if we are not supposed to check permissions from an alternate thread, such as AsyncPlayerChatEvent, what is the correct method?

Here is the stack trace:
```java
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at com.google.common.collect.AbstractMultimap$WrappedCollection$WrappedIterator.next(AbstractMultimap.java:531)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:247)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:111)
```

Thanks

**Comment by zml2008** [comment]
I think I've finally gotten this taken care of in the 1.23.x/1.22.x branch (*have* I backported? maybe).
Hopefully you might be able to test one of those out and see if they fix your issue

**Comment by zml2008** [comment]
yeah, no haven't backported yet. Lemme do that real quick.

**Comment by ItsHarry** [comment]
Alright, let me know when it is and I will test it out.

**Comment by zml2008** [comment]
ok, try https://minions.aoeu.xyz/owncloud/index.php/s/4wwDiUBI2nJx7UF and let me know how it goes

**Comment by ItsHarry** [comment]
Well, it seems to be working fine on my local server. I haven't had a chance to test it on the real thing yet.

**Comment by zml2008** [comment]
awesome! I'll push a release in the next day or so.
