### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by AshourAziz** [PEXPlugins/PermissionsEx#1962]
### Description ###

[Lag issues from Permissionsex]
### Detailed Information ###
Timings:
http://gyazo.com/92971d79c01940796c25cc0a8e87d9dc

Timings overall seems fine except for the permissionsex portion.

### What PEX Saw ###

**Reason:** User-requested report

**Stacktrace:**
```
java.lang.Exception
	at ru.tehkode.permissions.bukkit.commands.UtilityCommands.report(UtilityCommands.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:248)
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:110)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:304)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

```
### PEX configuration ###
```yaml
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
      type: file
  superperms: {}
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false

```

About 150,000 users.

**Comment by zml2008** [comment]
It looks like there was some change in permissions that required a lot of the users on your server to be reloaded, or file access to occur. Based on the averages and totals, I'd guess that there were a few single events that took a while, maybe events involving reloading from file (because 150k is a fairly large file), but most of the time the server is not exhibiting issues. Unless you start getting a large number of long events like this, I don't think it's worth the effort to investigate.

**Comment by Gaurav99** [comment]
Hey,
This issue is happening to me (minus the error log), except the count is 2.3k and is causing heavy lag on my server - http://prntscr.com/9h17ae
My config - http://pastebin.com/yAFimQhx
~230k users
What could be causing this?

Thanks
