### ISSUE TITLE
Glowstone Error

### ISSUE THREAD

**Issue by seema84** [PEXPlugins/PermissionsEx#1971]
Glowstone: Glowstone #123 (stable)
PEX: v1.23.1

[PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/ve
HCI. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/Cache
Builder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:726)
        at net.glowstone.GlowServer.start(GlowServer.java:477)
        at net.glowstone.GlowServer.main(GlowServer.java:106)

**Comment by zml2008** [comment]
use 1.22.7
