### ISSUE TITLE
Error: Permissions being checked must not be null!

### ISSUE THREAD

**Issue by jessefjxm** [PEXPlugins/PermissionsEx#1976]
My server suddenly give me this error every several times. But strangely no problem seemed happened....

[12:34:01 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/_14rzA. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.checkLocked(slot_lock.java:430)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.onPlayerInteract(slot_lock.java:227)
        at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226)
        at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463)
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724)
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50)
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80)
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Thread.java:745)

**Comment by zml2008** [comment]
slot_lock is broken. talk to that plugin's dev.
