### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by xNinjaKittyx** [PEXPlugins/PermissionsEx#1984]
### Description ###

I just booted it and I got this error.
### Detailed Information ###
Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:341)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:313)
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:374)
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:329)
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:236)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501)
	at java.lang.Thread.run(Unknown Source)

[Is available here](https://gist.github.com/a471dcbdcb8abeeb2d1e)

**Comment by xNinjaKittyx** [comment]
Woops, I forgot to make sure PEX was running latest version.

My bad
