### ISSUE TITLE
Bug from Console

### ISSUE THREAD

**Issue by CloudeLecaw** [PEXPlugins/PermissionsEx#1991]
### Description ###
i found this bug in the console, it normaly not happend but this time it happend. when the user logged out
### Detailed Information ###

[Is available here](https://gist.github.com/9a04d17ebf4d284253e2)
[19:42:42] [pool-23-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vfi4p. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
	at org.bukkit.craftbukkit.v1_8_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
	at gyurix.antiddos.AntiDDos.onPlayerQuit(AntiDDos.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R2.PlayerList.disconnect(PlayerList.java:346)
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:848)
	at net.minecraft.server.v1_8_R2.NetworkManager.l(NetworkManager.java:315)
	at net.minecraft.server.v1_8_R2.ServerConnection.c(ServerConnection.java:145)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:809)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zml2008** [comment]
your plugin AntiDDos is broken.
