### ISSUE TITLE
Error PEX

### ISSUE THREAD

**Issue by logtainment** [PEXPlugins/PermissionsEx#1992]
### Description ###

java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:413)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
        at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
        at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
        at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:746)
        at org.bukkit.Bukkit.reload(Bukkit.java:534)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
        ... 22 more
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at ru.tehkode.permissions.backends.sql.SQLQueryCache.<init>(SQLQueryCache.java:21)
        at ru.tehkode.permissions.backends.sql.SQLBackend.<clinit>(SQLBackend.java:65)
        ... 27 more

### Detailed Information ###

[Is available here](https://gist.github.com/8b4f81feb31d4580dbf7)

**Comment by Stormbow** [comment]
PermissionsEx does not support OFFLINE mode servers.

**Comment by logtainment** [comment]
I have a NETWORK with MYSql and my servers must be offline mode (bungeecord)
