### ISSUE TITLE
Error occurred with PermissionsEx

### ISSUE THREAD

**Issue by jbackman86** [PEXPlugins/PermissionsEx#2008]
G'day,

I'm completely new to this stuff and I have no clue what's going on. Here's what my server is spitting at me when I start it up:

[06:04:03 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vUZaE. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746)
        at org.bukkit.Bukkit.reload(Bukkit.java:534)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632)
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
        at java.lang.Thread.run(Thread.java:745)

Any help is appreciated. Cheers.

**Comment by zml2008** [comment]
For a 1.8 server, use PEX 1.23.2
