### ISSUE TITLE
Probleme PEX

### ISSUE THREAD

**Issue by groupezk** [PEXPlugins/PermissionsEx#2020]
### Description ###
When I start the server I have this error
### Detailed Information ###
[14:12:41] [pool-7-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vTTF8. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
	at java.lang.Thread.run(Thread.java:745)
[Is available here](https://gist.github.com/9f5bb8344ec21bf9d556)

**Comment by zml2008** [comment]
Run the latest 1.23.2 version of PEX -- the one that says that it is the version for 1.8 in the release notes.
