### ISSUE TITLE
PEX Loading Issue

### ISSUE THREAD

**Issue by jamisen10** [PEXPlugins/PermissionsEx#2023]
### Description ###
PEX Will not load on the server.
### Detailed Information ###

[19:03:26] [pool-8-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vTy5f. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
Using the wrong version of PEX for your server.
