### ISSUE TITLE
Error when prefix is Emtpy

### ISSUE THREAD

**Issue by CloudeLecaw** [PEXPlugins/PermissionsEx#2033]
i see the prefix cant be empty...also there is no change to remove a prefix one it was settet.
And you get this little error.

[10:01:04 INFO]: Error occurred with PermissionsEx! Please post it to http://git.io/vkG1m. Full error:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at ru.tehkode.permissions.commands.CommandsManager$CommandSyntax.getMatchedArguments(CommandsManager.java:195)
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:89)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:315)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:632)
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Stormbow** [comment]
To remove a prefix, you can most simply delete the line from your permission.yml file.  Then /pex reload while in-game, or "pex reload" in the console.

Do you still have the error after the prefix is removed as mentioned above?

**Comment by zml2008** [comment]
This is an issue in the commands system that can be easily worked around as @Stormbow mentioned. Please use his workaround until the new PEX is ready for Sponge.

**Comment by CloudeLecaw** [comment]
Sponge? im not using Sponge or so..just the simple normal Spigot
Im not a friend of the Spongefaction ;)
I tried Stormbows way that works fine. the question was more
if i can set a plugin to execute a command
and i use the prefix command
what command do i need to remove this prefix or suffix? :3
so ingame or console setup of prefix and suffix with a command is needed here...
including the reseting without getting this error ^^
So something maybe like "/pex USER rem suffix" .... or just "/pex USER suffix"...etc?
Result should be a removed prefix.

Any ideas?
