### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by honzik25** [PEXPlugins/PermissionsEx#2034]
[17:49:39] [pool-7-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F92149d34920c300d8e6b%29%0A. Full error:
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
    at ru.tehkode.permissions.backends.sql.SQLData.fetchInfo(SQLData.java:89)
    at ru.tehkode.permissions.backends.sql.SQLData.<init>(SQLData.java:35)
    at ru.tehkode.permissions.backends.sql.SQLBackend.getGroupData(SQLBackend.java:124)
    at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:471)
    at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:497)
    at ru.tehkode.permissions.PermissionManager.preloadGroups(PermissionManager.java:586)
    at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:672)
    at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:747)
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:72)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:157)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:218)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:384)
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:298)
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:280)
    at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342)
    at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319)
    at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275)
    at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175)
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424)
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
    at com.mysql.jdbc.Util.getInstance(Util.java:382)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
    at ru.tehkode.permissions.backends.sql.SQLData.fetchInfo(SQLData.java:72)
    ... 20 more

**Comment by CyanoFresh** [comment]
There is no 'prefix' column in your database table. Same issue. Author, please tell how to use prefix&suffix with database integration?

**Comment by Stormbow** [comment]
I think this actually has to do with 2 "schema-version" lines, but we'll see what Zml says.  (I don't do SQL, but I've been troubleshooting PEX for almost a year now, and I seem to recall this problem and that solution...)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
