### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Saphiria** [PEXPlugins/PermissionsEx#2037]
[18:26:21 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/z1jjYQ. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:60)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:158)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
	at java.lang.Thread.run(Thread.java:695)

**Comment by zml2008** [comment]
You appear to be running the incorrect version of Bukkit for your MC version. You probably want to be running version 1.23.2.

**Comment by Saphiria** [comment]
I'm on Spigot 1.8.6
