### ISSUE TITLE
Pex Fehler (MySQL)

### ISSUE THREAD

**Issue by Nightfighter001** [PEXPlugins/PermissionsEx#2051]
Wenn Pex läd bekomme ich folgenden Fehler:
[23:22:56] [pool-11-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vIUjl. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
        at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:188)
        at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
        at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:194)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
        at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
        at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
        at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
        at com.mysql.jdbc.Util.getInstance(Util.java:382)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
        at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:163)
        ... 24 more

**Comment by CzEMC** [comment]
Similar to #2229

Follow my instructions on issue #2229 and reply here your results.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
