### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by zLemonProz** [PEXPlugins/PermissionsEx#2052]
### Description ###

[06:32:40 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vIs3N. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.checkLocked(slot_lock.java:402)
        at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.onPlayerClick(slot_lock.java:256)
        at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1620)
        at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:31)
        at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:9)
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
        at java.lang.Thread.run(Thread.java:745)

### Detailed Information ###

[Is available here](https://gist.github.com/1115d89b84735fd2b2ec)

**Comment by zml2008** [comment]
slot_lock is broken, talk to that plugin's dev.

**Comment by zLemonProz** [comment]
I was running an outdated version of slot lock. Updating it to the version before latest worked. (Latest is broken)
