### ISSUE TITLE
Players Cant join the server

### ISSUE THREAD

**Issue by Rida94** [PEXPlugins/PermissionsEx#2054]
The server is 1.8.6 spigot using latest permissionsex 

every few hours from the server being up when a player try to connect to the server I get errors like this one in console the only solution is to restart the server

[21:58:01] [User Authenticator #242/INFO]: UUID of player PixelCat_ is b381c367-8eb2-46a8-b947-cdba82c3f224
[21:58:01] [Server thread/WARN]: Failed to handle packet for /77.103.22.209:61144
java.lang.NullPointerException

and when I do /pex user (any offline user) I get like this error

[21:58:53] [pool-1502-thread-1/INFO]: Error occurred with PermissionsEx! Please post it to http://git.io/vIWn2. Full error:
java.lang.RuntimeException: java.lang.NullPointerException
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:117)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:315)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628)
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException

**Comment by zml2008** [comment]
Seen this issue before, but haven't been able to get a sensible error log from the server or reproduce it myself. My current workaround is to suggest that you not try to work with offline users, and wait for the Sponge 2.0 release to be ready.
