### ISSUE TITLE
PermissionsEx v[1.23.2]: InvocationTargetException

### ISSUE THREAD

**Issue by Kilovice** [PEXPlugins/PermissionsEx#2060]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:191) ~[PermissionsEx.jar:?]
	... 44 more
Caused by: java.lang.StackOverflowError
	at java.util.WeakHashMap.hash(Unknown Source) ~[?:1.7.0_75]
	at java.util.WeakHashMap.put(Unknown Source) ~[?:1.7.0_75]
	at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap$PEXSubscriptionValueMap.put(PEXPermissionSubscriptionMap.java:135) ~[?:?]
	at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap$PEXSubscriptionValueMap.put(PEXPermissionSubscriptionMap.java:104) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.subscribeToPermission(SimplePluginManager.java:655) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:187) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-ea179b3-6e0120a]

**Comment by zml2008** [comment]
This looks like you have misconfigured plugins that have set up an inheritance loop with the permissions they are registering. Try taking out plugins until the error goes away.
