### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by 1yeah** [PEXPlugins/PermissionsEx#2070]
### Description ###

[[03:06:43] [pool-47-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vLb5E. Full error:
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:413)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746)
	at org.bukkit.Bukkit.reload(Bukkit.java:534)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
	... 29 more
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at ru.tehkode.permissions.backends.sql.SQLQueryCache.<init>(SQLQueryCache.java:21)
	at ru.tehkode.permissions.backends.sql.SQLBackend.<clinit>(SQLBackend.java:64)
	... 34 more]

### Detailed Information ###
The Plugin disables automatically while starting with this message. If the error is already fixed I say sorry. Then it's my blame. A wonderful day!

[Is available here](https://gist.github.com/d8b5dc0130518049dab5)

**Comment by zml2008** [comment]
This shouldn't happen -- this means that a file that's supposed to be in the jar is not present. Try redownloading the jar and hopefully the error will clear up.

**Comment by 1yeah** [comment]
THX man!

Am 29.06.2015 04:36 schrieb "zml" <notifications@github.com>:
