### ISSUE TITLE
Inssue with PEX

### ISSUE THREAD

**Issue by Zaniquelli** [PEXPlugins/PermissionsEx#2073]
### Description ###

[Insert description of issue here]
### What PEX Saw ###

**Reason:** While disabling

**Stacktrace:**
```
21:07:11 [severe]  Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+setting+backend%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.IllegalStateException%3A+Error+loading+permissions+file%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A249%29%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.initialize%28FileBackend.java%3A84%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.setBackend%28PermissionManager.java%3A427%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.initBackend%28PermissionManager.java%3A492%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.%3Cinit%3E%28PermissionManager.java%3A55%29%0D%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onLoad%28PermissionsEx.java%3A83%29%0D%0A%09at+org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins%28CraftServer.java%3A244%29%0D%0A%09at+org.bukkit.craftbukkit.v1_5_R3.CraftServer.%3Cinit%3E%28CraftServer.java%3A217%29%0D%0A%09at+net.minecraft.server.v1_5_R3.PlayerList.%3Cinit%3E%28PlayerList.java%3A55%29%0D%0A%09at+net.minecraft.server.v1_5_R3.DedicatedPlayerList.%3Cinit%3E%28SourceFile%3A11%29%0D%0A%09at+net.minecraft.server.v1_5_R3.DedicatedServer.init%28DedicatedServer.java%3A106%29%0D%0A%09at+net.minecraft.server.v1_5_R3.MinecraftServer.run%28MinecraftServer.java%3A382%29%0D%0A%09at+net.minecraft.server.v1_5_R3.ThreadServerApplication.run%28SourceFile%3A573%29%0D%0ACaused+by%3A+org.bukkit.configuration.InvalidConfigurationException%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+54%2C+column+1%3A%0A++++%09-+ancientgates.use.*%0A++++%5E%0A%0D%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A55%29%0D%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A138%29%0D%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A105%29%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A232%29%0D%0A%09...+12+more%0D%0ACaused+by%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+54%2C+column+1%3A%0A++++%09-+ancientgates.use.*%0A++++%5E%0A%0D%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens%28ScannerImpl.java%3A358%29%0D%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.checkToken%28ScannerImpl.java%3A179%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl%24ParseIndentlessSequenceEntry.produce%28ParserImpl.java%3A535%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.peekEvent%28ParserImpl.java%3A161%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.checkEvent%28ParserImpl.java%3A146%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeSequenceNode%28Composer.java%3A203%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A158%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeDocument%28Composer.java%3A123%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.getSingleNode%28Composer.java%3A106%29%0D%0A%09at+org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData%28BaseConstructor.java%3A121%29%0D%0A%09at+org.yaml.snakeyaml.Yaml.loadFromReader%28Yaml.java%3A480%29%0D%0A%09at+org.yaml.snakeyaml.Yaml.load%28Yaml.java%3A399%29%0D%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A53%29%0D%0A%09...+15+more%0D%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0A++membro%3A%0A++++default%3A+true%0A++++permissions%3A%0A++++-+essentials.motd%0A++++-+essentials.help%0A++++-+essentials.helpop%0A++++-+essentials.rules%0A++++-+essentials.kit%0A++++-+essentials.kits.nb%0A++++-+essentials.spawn%0A++++-+essentials.ping%0A++++-+essentials.sethome.multiple.default%0A++++-+essentials.delhome%0A++++-+essentials.home%0A++++-+essentials.tpa%0A++++-+essentials.tpaccept%0A++++-+essentials.tpdeny%0A++++-+essentials.warp%0A++++-+essentials.warp.list%0A++++-+essentials.list%0A++++-+essentials.repair%0A++++-+legendchat.channel.global.chat%0A++++-+legendchat.channel.local.chat%0A++++-+legendchat.use%0A++++-+legendchat.use.global%0A++++-+legendchat.use.local%0A++++-+-ChestShop.shop.create%0A++++-+-ChestShop.shop.create.buy%0A++++-+-ChestShop.shop.create.sell%0A++++-+ChestShop.shop.buy%0A++++-+ChestShop.shop.sell%0A++++-+simpleclans.anyone.*%0A++++-+simpleclans.member.*%0A++++-+simpleclans.leader.*%0A++++-+authme.login%0A++++-+authme.register%0A++++-+authme.changepassword%0A++++-+iConomy.holdings%0A++++-+iConomy.holdings.others%0A++++-+iConomy.payment%0A++++-+iConomy.top%0A++++-+vipzero.use%0A++++-+vipzero.user%0A++++-+vipzero.usar.key%0A++++-+eventogamers.evento.parkour%0A++++-+-mcmmo.ability.unarmed%0A++++-+mcmmo.ability.all%0A++++-+mcmmo.commands.defaults%0A++++-+mcmmo.defaults%0A++++-+tgstaffon.usar%0A++++-+eventogamers.evento.parkour%0A++++-+limparchat.usar%0A%09-+ancientgates.use.*%0A%09-+automessage.receive.default%0A%09-+craftx1.desafiar%0A%09-+craftx1.aceitar%0A%09-+craftx1.camarote%0A%09-+eventogamers.evento.parkour%0A%09-+pin.*%0A%09-+tgstaffon.usar%0A%09-+vipzero.user%0A++vip%3A%0A++++inheritance%3A+membro%0A++++permissions%3A%0A++++-+automessage.receive.vip%0A++++-+ColoredSigns.color%0A++++-+essentials.hat%0A++++-+essentials.kit%0A++++-+essentials.kits.vip%0A++++-+essentials.repair.enchanted%0A++++-+essentials.workbench%0A++++-+essentials.afk%0A++++-+essentials.warp.vip%0A++++-+essentials.sethome%0A++++-+essentials.delhome%0A++++-+essentials.sethome.vip%0A++++-+fly.fly%0A++++-+essentials.joinfullserver%0A++++-+essentials.back.ondeath%0A++++-+chestshop.shop.create%0A++++-+chestshop.shop.buy%0A++++-+chestshop.shop.sell%0A++++-+PowerDesencantar.Usar%0A++++-+sec.spawnerchange%0A++++-+essentials.protect.pvp%0A++++-+pvptime.nopvp%0A++++-+essentials.fly%0A++++-+eventogamers.evento.parkour%0A++++-+massivehat.use%0A+++moderador%3A%0A++++inheritance%3A+vip%0A++++permissions%3A%0A++++-+advbans.*%0A++++-+ChestShop.mod%0A++++-+ColoredSigns.*%0A++++-+lagg.admin%0A++++-+commandsigns.*%0A++++-+craftx1.admin%0A++++-+essentials.break.bedrock%0A++++-+essentials.gamemode%0A++++-+essentials.backup%0A++++-+essentials.clearinventory%0A++++-+tgstaffon.staff%0A+++administrador%3A%0A++++inheritance%3A+moderador%0A++++permissions%3A%0A++++-+automessage.commands.*%0A++++-+ancientgates.*%0A++++-+authme.admin.*%0A++++-+ChestShop.admin%0A++++-+combatlog.*%0A++++-+essentials.give%0A++++-+essentials.*%0A++++-+heroclantags.admin%0A++++-+mcmmo.*%0A++++-+tgstaffon.staff%0A++++-+skript.admin%0A++++-+skript.effectcommands%0A++++-+mobcash.*%0A++++-+safecreeper.command.*%0A++++-+multiverse.core.*%0A++++-+apin.*%0A++++-+pkm.*%0A++++-+pvptime.*%0A++++-+safecreeper.command.*%0A++++-+simpleclans.mod.*%0A++++-+worldedit.*%0A++++-+worldguard.*%0A+++diretor%3A%0A++++inheritance%3A+administrador%0A++++permissions%3A%0A++++-+%27*%27%0A++++-+tgstaffon.staff%0A++++-+safecreeper.bypass.*%0A++++-+simpleclans.admin.*%0A++++-+vipzero.admin%0A++++-+itembans.use%0A++++-+reiniciar.*%0A++++users%3A%0A++Zaniquelli%3A%0A++++group%3A%0A++++-+Diretor%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++biielvz%3A%0A++++group%3A%0A++++-+Diretor%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++RayBan%3A%0A++++group%3A%0A++++-+Membro%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++xxxx%3A%0A++++group%3A%0A++++-+Membro%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++kaway%3A+%7B%7D%0A%60%60%60%0A. Full error:
21:07:11 [javastacktrace] java.lang.IllegalStateException: Error loading permissions file
21:07:11 [javastacktrace] 	at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:249)
21:07:11 [javastacktrace] 	at ru.tehkode.permissions.backends.FileBackend.initialize(FileBackend.java:84)
21:07:12 [javastacktrace] 	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:427)
21:07:12 [javastacktrace] 	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:492)
21:07:12 [javastacktrace] 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:55)
21:07:12 [javastacktrace] 	at ru.tehkode.permissions.bukkit.PermissionsEx.onLoad(PermissionsEx.java:83)
21:07:12 [javastacktrace] 	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:244)
21:07:12 [javastacktrace] 	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:217)
21:07:12 [javastacktrace] 	at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
21:07:12 [javastacktrace] 	at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
21:07:12 [javastacktrace] 	at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:106)
21:07:12 [javastacktrace] 	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:382)
21:07:12 [javastacktrace] 	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
21:07:12 [javastacktrace] 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
21:07:12 [javastacktrace] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
21:07:12 [javastacktrace] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
21:07:12 [javastacktrace] 	at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:232)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:535)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:203)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:158)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
21:07:12 [javastacktrace] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
21:07:12 [javastacktrace] 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)

**Comment by Zaniquelli** [comment]
Another inssue:

21:07:37 [severe]  Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+disabling%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.IllegalStateException%3A+Error+loading+permissions+file%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A249%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.reset%28PermissionManager.java%3A457%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.end%28PermissionManager.java%3A463%29%0D%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onDisable%28PermissionsEx.java%3A139%29%0D%0A%09at+org.bukkit.plugin.java.JavaPlugin.setEnabled%28JavaPlugin.java%3A219%29%0D%0A%09at+org.bukkit.plugin.java.JavaPluginLoader.disablePlugin%28JavaPluginLoader.java%3A481%29%0D%0A%09at+org.bukkit.plugin.SimplePluginManager.disablePlugin%28SimplePluginManager.java%3A400%29%0D%0A%09at+org.bukkit.plugin.SimplePluginManager.disablePlugins%28SimplePluginManager.java%3A393%29%0D%0A%09at+org.bukkit.craftbukkit.v1_5_R3.CraftServer.disablePlugins%28CraftServer.java%3A277%29%0D%0A%09at+net.minecraft.server.v1_5_R3.MinecraftServer.stop%28MinecraftServer.java%3A334%29%0D%0A%09at+net.minecraft.server.v1_5_R3.MinecraftServer.run%28MinecraftServer.java%3A441%29%0D%0A%09at+net.minecraft.server.v1_5_R3.ThreadServerApplication.run%28SourceFile%3A573%29%0D%0ACaused+by%3A+org.bukkit.configuration.InvalidConfigurationException%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+54%2C+column+1%3A%0A++++%09-+ancientgates.use.*%0A++++%5E%0A%0D%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A55%29%0D%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A138%29%0D%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A105%29%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A232%29%0D%0A%09...+11+more%0D%0ACaused+by%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+54%2C+column+1%3A%0A++++%09-+ancientgates.use.*%0A++++%5E%0A%0D%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens%28ScannerImpl.java%3A358%29%0D%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.checkToken%28ScannerImpl.java%3A179%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl%24ParseIndentlessSequenceEntry.produce%28ParserImpl.java%3A535%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.peekEvent%28ParserImpl.java%3A161%29%0D%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.checkEvent%28ParserImpl.java%3A146%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeSequenceNode%28Composer.java%3A203%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A158%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.composeDocument%28Composer.java%3A123%29%0D%0A%09at+org.yaml.snakeyaml.composer.Composer.getSingleNode%28Composer.java%3A106%29%0D%0A%09at+org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData%28BaseConstructor.java%3A121%29%0D%0A%09at+org.yaml.snakeyaml.Yaml.loadFromReader%28Yaml.java%3A480%29%0D%0A%09at+org.yaml.snakeyaml.Yaml.load%28Yaml.java%3A399%29%0D%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A53%29%0D%0A%09...+14+more%0D%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0A++membro%3A%0A++++default%3A+true%0A++++permissions%3A%0A++++-+essentials.motd%0A++++-+essentials.help%0A++++-+essentials.helpop%0A++++-+essentials.rules%0A++++-+essentials.kit%0A++++-+essentials.kits.nb%0A++++-+essentials.spawn%0A++++-+essentials.ping%0A++++-+essentials.sethome.multiple.default%0A++++-+essentials.delhome%0A++++-+essentials.home%0A++++-+essentials.tpa%0A++++-+essentials.tpaccept%0A++++-+essentials.tpdeny%0A++++-+essentials.warp%0A++++-+essentials.warp.list%0A++++-+essentials.list%0A++++-+essentials.repair%0A++++-+legendchat.channel.global.chat%0A++++-+legendchat.channel.local.chat%0A++++-+legendchat.use%0A++++-+legendchat.use.global%0A++++-+legendchat.use.local%0A++++-+-ChestShop.shop.create%0A++++-+-ChestShop.shop.create.buy%0A++++-+-ChestShop.shop.create.sell%0A++++-+ChestShop.shop.buy%0A++++-+ChestShop.shop.sell%0A++++-+simpleclans.anyone.*%0A++++-+simpleclans.member.*%0A++++-+simpleclans.leader.*%0A++++-+authme.login%0A++++-+authme.register%0A++++-+authme.changepassword%0A++++-+iConomy.holdings%0A++++-+iConomy.holdings.others%0A++++-+iConomy.payment%0A++++-+iConomy.top%0A++++-+vipzero.use%0A++++-+vipzero.user%0A++++-+vipzero.usar.key%0A++++-+eventogamers.evento.parkour%0A++++-+-mcmmo.ability.unarmed%0A++++-+mcmmo.ability.all%0A++++-+mcmmo.commands.defaults%0A++++-+mcmmo.defaults%0A++++-+tgstaffon.usar%0A++++-+eventogamers.evento.parkour%0A++++-+limparchat.usar%0A%09-+ancientgates.use.*%0A%09-+automessage.receive.default%0A%09-+craftx1.desafiar%0A%09-+craftx1.aceitar%0A%09-+craftx1.camarote%0A%09-+eventogamers.evento.parkour%0A%09-+pin.*%0A%09-+tgstaffon.usar%0A%09-+vipzero.user%0A++vip%3A%0A++++inheritance%3A+membro%0A++++permissions%3A%0A++++-+automessage.receive.vip%0A++++-+ColoredSigns.color%0A++++-+essentials.hat%0A++++-+essentials.kit%0A++++-+essentials.kits.vip%0A++++-+essentials.repair.enchanted%0A++++-+essentials.workbench%0A++++-+essentials.afk%0A++++-+essentials.warp.vip%0A++++-+essentials.sethome%0A++++-+essentials.delhome%0A++++-+essentials.sethome.vip%0A++++-+fly.fly%0A++++-+essentials.joinfullserver%0A++++-+essentials.back.ondeath%0A++++-+chestshop.shop.create%0A++++-+chestshop.shop.buy%0A++++-+chestshop.shop.sell%0A++++-+PowerDesencantar.Usar%0A++++-+sec.spawnerchange%0A++++-+essentials.protect.pvp%0A++++-+pvptime.nopvp%0A++++-+essentials.fly%0A++++-+eventogamers.evento.parkour%0A++++-+massivehat.use%0A+++moderador%3A%0A++++inheritance%3A+vip%0A++++permissions%3A%0A++++-+advbans.*%0A++++-+ChestShop.mod%0A++++-+ColoredSigns.*%0A++++-+lagg.admin%0A++++-+commandsigns.*%0A++++-+craftx1.admin%0A++++-+essentials.break.bedrock%0A++++-+essentials.gamemode%0A++++-+essentials.backup%0A++++-+essentials.clearinventory%0A++++-+tgstaffon.staff%0A+++administrador%3A%0A++++inheritance%3A+moderador%0A++++permissions%3A%0A++++-+automessage.commands.*%0A++++-+ancientgates.*%0A++++-+authme.admin.*%0A++++-+ChestShop.admin%0A++++-+combatlog.*%0A++++-+essentials.give%0A++++-+essentials.*%0A++++-+heroclantags.admin%0A++++-+mcmmo.*%0A++++-+tgstaffon.staff%0A++++-+skript.admin%0A++++-+skript.effectcommands%0A++++-+mobcash.*%0A++++-+safecreeper.command.*%0A++++-+multiverse.core.*%0A++++-+apin.*%0A++++-+pkm.*%0A++++-+pvptime.*%0A++++-+safecreeper.command.*%0A++++-+simpleclans.mod.*%0A++++-+worldedit.*%0A++++-+worldguard.*%0A+++diretor%3A%0A++++inheritance%3A+administrador%0A++++permissions%3A%0A++++-+%27*%27%0A++++-+tgstaffon.staff%0A++++-+safecreeper.bypass.*%0A++++-+simpleclans.admin.*%0A++++-+vipzero.admin%0A++++-+itembans.use%0A++++-+reiniciar.*%0A++++users%3A%0A++Zaniquelli%3A%0A++++group%3A%0A++++-+Diretor%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++biielvz%3A%0A++++group%3A%0A++++-+Diretor%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++RayBan%3A%0A++++group%3A%0A++++-+Membro%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++xxxx%3A%0A++++group%3A%0A++++-+Membro%0A++++worlds%3A%0A++++++world%3A+%7B%7D%0A++++++world_nether%3A+%7B%7D%0A++++++world_the_end%3A+%7B%7D%0A++++++eventos%3A+%7B%7D%0A++++++worldedit%3A+%7B%7D%0A++++++fogguer%3A+%7B%7D%0A++++++survival%3A+%7B%7D%0A++kaway%3A+%7B%7D%0A%60%60%60%0A. Full error:
21:07:37 [javastacktrace] java.lang.IllegalStateException: Error loading permissions file
21:07:37 [javastacktrace] 	at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:249)
21:07:37 [javastacktrace] 	at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:457)
21:07:37 [javastacktrace] 	at ru.tehkode.permissions.PermissionManager.end(PermissionManager.java:463)
21:07:37 [javastacktrace] 	at ru.tehkode.permissions.bukkit.PermissionsEx.onDisable(PermissionsEx.java:139)
21:07:37 [javastacktrace] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
21:07:37 [javastacktrace] 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
21:07:37 [javastacktrace] 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
21:07:37 [javastacktrace] 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
21:07:37 [javastacktrace] 	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.disablePlugins(CraftServer.java:277)
21:07:37 [javastacktrace] 	at net.minecraft.server.v1_5_R3.MinecraftServer.stop(MinecraftServer.java:334)
21:07:37 [javastacktrace] 	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:441)
21:07:37 [javastacktrace] 	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
21:07:38 [javastacktrace] 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
21:07:38 [javastacktrace] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
21:07:38 [javastacktrace] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
21:07:38 [javastacktrace] 	at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:232)
21:07:38 [javastacktrace] 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
21:07:38 [javastacktrace] 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
21:07:38 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:535)
21:07:38 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
21:07:38 [javastacktrace] 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
