### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ringpolice** [PEXPlugins/PermissionsEx#2075]
java.lang.Exception
    at ru.tehkode.permissions.bukkit.commands.UtilityCommands.report(UtilityCommands.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
    at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:114)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:165)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by zml2008** [comment]
You provided no details and cut off the relevant link. Can't really do anything if you don't tell us what's happening.

**Comment by zml2008** [comment]
No reply in a month, closing.
