### ISSUE TITLE
WinCraft

### ISSUE THREAD

**Issue by rmsk1pro** [PEXPlugins/PermissionsEx#2085]
015-07-01 23:07:39 [INFO] emrecan1907[/191.243.207.234:51620] logged in with entity id 144512 at ([world] 274.2347273301353, 25.0, 239.61024002944458)
2015-07-01 23:07:39 [SEVERE] [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F9f87745a7dd382ca6a71%29%0A. Full error:
java.lang.IllegalArgumentException: Null or empty name passed! Name must not be empty
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:110)
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:135)
	at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:50)
	at ru.tehkode.permissions.bukkit.SuperpermsListener.onPlayerLogin(SuperpermsListener.java:146)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
	at net.minecraft.server.v1_5_R3.PlayerList.attemptLogin(PlayerList.java:332)
	at net.minecraft.server.v1_5_R3.PendingConnection.d(PendingConnection.java:120)
	at net.minecraft.server.v1_5_R3.PendingConnection.c(PendingConnection.java:44)
	at net.minecraft.server.v1_5_R3.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:41)
	at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:29)
	at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

2015-07-01 23:07:39 [INFO] [WinCraft] Limpando o chao em! 10 segundos!

**Comment by zml2008** [comment]
You're running an ancient version of PermissionsEx on an ancient version of Bukkit. Why do you expect anybody to want to help you?

**Comment by rmsk1pro** [comment]
Which version is best for 1.5.2?
