### ISSUE TITLE
Pex Error

### ISSUE THREAD

**Issue by xAcrosonicx** [PEXPlugins/PermissionsEx#2096]
```
18.07 14:49:05 [Server] INFO Caused by: java.lang.NullPointerException
18.07 14:49:05 [Server] INFO at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_51]
18.07 14:49:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_51]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1131) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
18.07 14:49:05 [Server] INFO org.bukkit.event.EventException
```

**Comment by zml2008** [comment]
Don't use the names of any offline players in commands for now -- there's some issue in bukkit that breaks that that has been difficult to track down.
