### ISSUE TITLE
I Can't Use PermissionsEX

### ISSUE THREAD

**Issue by oriamrm** [PEXPlugins/PermissionsEx#2109]
it to http://git.io/vOJ0c. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)
Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.jav
a:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.ja
va:163)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:356)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:316)
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
14)
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
78)
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
33)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:263)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:524)
        at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
Which version of PEX are you using and which version of Minecraft are you running?

**Comment by zml2008** [comment]
You're using the 1.22.x version of PEX on a 1.8 server. Update to the latest 1.23.x version.
