### ISSUE TITLE
PermissionEx Not Working in SportBukkit/Spigot 1.8.7

### ISSUE THREAD

**Issue by BeastPsycho** [PEXPlugins/PermissionsEx#2121]
Error log:

[PermissionsEx] Unable to inject permissible for "anyplayerafterloginserver"
```
java.lang.ExceptionInInitializerError: Field of wrong type
	at ru.tehkode.utils.FieldReplacer.<init>(FieldReplacer.java:21) ~[PermissionsEx-1.23.3.jar:?]
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.<clinit>(PermissiblePEX.java:54) ~[PermissionsEx-1.23.3.jar:?]
	at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions.injectPermissible(RegexPermissions.java:62) [PermissionsEx-1.23.3.jar:?]
	at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions$EventListener.onPlayerLogin(RegexPermissions.java:136) [PermissionsEx-1.23.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) [spigot2.jar:git-Bukkit-5da39dd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot2.jar:git-Bukkit-5da39dd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:513) [spigot2.jar:git-Bukkit-5da39dd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:498) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:463) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:97) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:226) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:155) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:761) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [spigot2.jar:git-Bukkit-5da39dd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [spigot2.jar:git-Bukkit-5da39dd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

And consecuently of this, permissions are not working for any rank, any help?:c

**Comment by GangSterFlexx** [comment]
What version is your server running on?

**Comment by GangSterFlexx** [comment]
as I am reading the logs, looks like something failed to inject permissible anyplayerafterloginserver

**Comment by BeastPsycho** [comment]
GangSterFlexx, yes my friend, well...

Im running a SportBukkit 1.8.7 server, but this issue happens wth a normal spigot 1.8.7 or 1.8.8 server too, i think the plugin its coded for spigot v1_8_R3.

Y trid to upgrade my servers because are there a lot of server bugs reported and glitches, all my plugins are working for spigot 1.8.7 when i upgrade, but permissionsex not, i tried removing all plugins, same issue, any fix?

**Comment by zml2008** [comment]
I can't reproduce this on latest 1.8.8 spigot (built off of BuildTools 5 minutes ago, `git-Spigot-fdc1440-53fac9f`) and PEX 1.23.3. If those versions still don't work for you, could you send me your server jar? I'd need to take a look at the classes in the jar to see if there are any differences with what PEX expects.

**Comment by BeastPsycho** [comment]
Well, I need that Permissionsex works for the last version of SportBukkit, this is the Jar Im using in my server:

https://build.oc.tc/job/SportBukkit/lastSuccessfulBuild/artifact/build/CraftBukkit/target/sportbukkit-1.8.7-R0.1-SNAPSHOT.jar

I need that the plugin works with this version of server jar, because a i have some "Sportbukkit coded and updated Minigames plugins" and i dont find other good permissions plugin like yours.

Here some of Sportbukkit developers:

"CraftBukkit modifications and Bukkit API additions that fix bugs, add new features, and improve the quality of life"

**Comment by GangSterFlexx** [comment]
Perhaps you can give me ip so i can take a look??

I recommended you to get normal spigot, you can use sportspigot of you like, but its just my opinion.

**Comment by zml2008** [comment]
So yeah, it looks like SportBukkit has significantly changed the superperms interfaces. Use spigot instead, SportBukkit is no longer supported.

**Comment by TiTo-418** [comment]
@zml2008 Relevant patch: https://github.com/OvercastNetwork/SportBukkit/blob/master/Bukkit/0037-Improve-Permissible-interface.patch

It would be cool if you could fix it ;)

**Comment by zml2008** [comment]
I don't have the time to support everybody's forks with different changes. Do it yourself if you want it to happen (and don't drag up ancient issues).
