### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by griffen4** [PEXPlugins/PermissionsEx#2123]
### Description ###
This is a new error that just started to happen help is useful thanks :D
[Insert description of issue here]
### Detailed Information ###
[02:48:18] [pool-8-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/v3c3A. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
	at java.lang.Thread.run(Thread.java:745)
[Is available here](https://gist.github.com/52fa8c605cabbfc144df)

**Comment by zml2008** [comment]
Don't run PEX 1.22.x on a 1.8 server. Read the release notes.
