### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by DianaDunaeva** [PEXPlugins/PermissionsEx#2131]
```
[07:08:00] [Thread-56/ERROR]: Could not pass event AsyncPlayerPreLoginEvent to PermissionsEx v1.23.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[de1.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[de1.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [de1.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [de1.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [de1.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener$2.run(LoginListener.java:172) [de1.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Error initializing group voi
        at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:415) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:433) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:499) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:113) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:98) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:59) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.cacheUser(PermissionManager.java:191) ~[?:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onAsyncPlayerPreLogin(PermissionsEx.java:435) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[de1.jar:git-Spigot-870264a-0a645a2]
        ... 6 more
Caused by: java.lang.RuntimeException: ru.tehkode.libs.org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
        at ru.tehkode.permissions.backends.sql.SQLData.getParentsMap(SQLData.java:316) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.loadInheritance(CachingData.java:59) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.getParents(CachingData.java:203) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:843) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:840) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:70) ~[?:?]

        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[de1.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [de1.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [de1.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [de1.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener$2.run(LoginListener.java:172) [de1.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Error initializing group voi
        at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:415) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:433) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:499) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:113) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:98) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:59) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.cacheUser(PermissionManager.java:191) ~[?:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onAsyncPlayerPreLogin(PermissionsEx.java:435) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[de1.jar:git-Spigot-870264a-0a645a2]
        ... 6 more
Caused by: java.lang.RuntimeException: ru.tehkode.libs.org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
        at ru.tehkode.permissions.backends.sql.SQLData.getParentsMap(SQLData.java:316) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.loadInheritance(CachingData.java:59) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.getParents(CachingData.java:203) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:843) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:840) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:70) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParentsInternal(PermissionEntity.java:856) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionGroup.initialize(PermissionGroup.java:45) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:412) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:433) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:499) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:113) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:98) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:59) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.cacheUser(PermissionManager.java:191) ~[?:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onAsyncPlayerPreLogin(PermissionsEx.java:435) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[de1.jar:git-Spigot-870264a-0a645a2]
        ... 6 more
Caused by: ru.tehkode.libs.org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
        at ru.tehkode.libs.org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:114) ~[?:?]
        at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLData.getParentsMap(SQLData.java:304) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.loadInheritance(CachingData.java:59) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.getParents(CachingData.java:203) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:843) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:840) ~[?:?]

        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionGroup.initialize(PermissionGroup.java:45) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:412) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:433) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:499) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:113) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:98) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:59) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.cacheUser(PermissionManager.java:191) ~[?:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onAsyncPlayerPreLogin(PermissionsEx.java:435) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[de1.jar:git-Spigot-870264a-0a645a2]
        ... 6 more
Caused by: ru.tehkode.libs.org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
        at ru.tehkode.libs.org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:114) ~[?:?]
        at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLData.getParentsMap(SQLData.java:304) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.loadInheritance(CachingData.java:59) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.getParents(CachingData.java:203) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:843) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:840) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:70) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParentsInternal(PermissionEntity.java:856) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionGroup.initialize(PermissionGroup.java:45) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:412) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getGroupList(PermissionManager.java:433) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:499) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:113) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831) ~[?:?]
        at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:98) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:478) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:67) ~[?:?]
        at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:59) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:239) ~[?:?]
        at ru.tehkode.permissions.PermissionManager.cacheUser(PermissionManager.java:191) ~[?:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onAsyncPlayerPreLogin(PermissionsEx.java:435) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[de1.jar:git-Spigot-870264a-0a645a2]
        ... 6 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
        at ru.tehkode.libs.org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1134) ~[?:?]
        at ru.tehkode.libs.org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106) ~[?:?]
        at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245) ~[?:?]
        at ru.tehkode.permissions.backends.sql.SQLData.getParentsMap(SQLData.java:304) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.loadInheritance(CachingData.java:59) ~[?:?]
        at ru.tehkode.permissions.backends.caching.CachingData.getParents(CachingData.java:203) ~[?:?]
        at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823) ~[?:?]
```

**Comment by zml2008** [comment]
It looks like this issue may be caused by circular inheritance in your configuration -- take a look at the inheritance table to see if any exists, and remove it if necessary.
