### ISSUE TITLE
Odd message on console command

### ISSUE THREAD

**Issue by iampyrex** [PEXPlugins/PermissionsEx#2142]
From console: ```pex group Owner create```

Result:
```
[15:12:28] [Server thread/INFO]: Error occurred while executing command: GRAY
[15:12:28] [Server thread/ERROR]: Error occurred while executing command 'pex group Owner create' for source net.minecraft.server.dedicated.DedicatedServer@8757c54: GRAY
java.lang.NoSuchFieldError: GRAY
        at ninja.leaping.permissionsex.sponge.SpongeMessageFormatter.<clinit>(SpongeMessageFormatter.java:47) ~[SpongeMessageFormatter.class:?]
        at ninja.leaping.permissionsex.sponge.SpongeCommander.<init>(SpongeCommander.java:50) ~[SpongeCommander.class:?]
        at ninja.leaping.permissionsex.sponge.PEXSpongeCommand.process(PEXSpongeCommand.java:43) ~[PEXSpongeCommand.class:?]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:345) ~[SimpleDispatcher.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:250) [SimpleCommandService.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

**Comment by iampyrex** [comment]
Fresh server running latest sponge and only the latest PEX 2.0.

**Comment by zml2008** [comment]
Ok, looks like this was a change in sponge that just requires a rebuild. That has been made, so you should be good to just download a new dev build from http://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/
