### ISSUE TITLE
Duplicate entry for key 'name' error

### ISSUE THREAD

**Issue by ItsHarry** [PEXPlugins/PermissionsEx#2143]
I'm using PEX version 1.23.3 using MySQL backend.

I sometimes get this error (different UUIDs obviously), which causes the group not to be set for the user:

``` java
[16:20:06] [pool-11-thread-1/WARN]: Exception in thread "pool-11-thread-1" 
[16:20:06] [pool-11-thread-1/WARN]: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '9cb659c2-ee9d-40b1-89d9-7d00b7cc6f1d-1' for key 'name'
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.sql.SQLData.updateInfo(SQLData.java:49)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.sql.SQLData.save(SQLData.java:280)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.sql.SQLData.setParents(SQLData.java:344)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.caching.CachingData$4.run(CachingData.java:219)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.caching.CachingData$1.run(CachingData.java:34)
[16:20:06] [pool-11-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:20:06] [pool-11-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:20:06] [pool-11-thread-1/WARN]:     at java.lang.Thread.run(Thread.java:745)
[16:20:06] [pool-11-thread-1/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '9cb659c2-ee9d-40b1-89d9-7d00b7cc6f1d-1' for key 'name'
[16:20:06] [pool-11-thread-1/WARN]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:20:06] [pool-11-thread-1/WARN]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:20:06] [pool-11-thread-1/WARN]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:20:06] [pool-11-thread-1/WARN]:     at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.Util.getInstance(Util.java:382)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[16:20:06] [pool-11-thread-1/WARN]:     at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
[16:20:06] [pool-11-thread-1/WARN]:     at ru.tehkode.permissions.backends.sql.SQLData.updateInfo(SQLData.java:43)
[16:20:06] [pool-11-thread-1/WARN]:     ... 7 more
```

**Comment by ItsHarry** [comment]
This problem is still happening, any chance it could be fixed?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
