### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yodabosten** [PEXPlugins/PermissionsEx#2147]
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by zml2008** [comment]
wrong version of PEX for your server version. read the release notes.
