### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by EvilTroll** [PEXPlugins/PermissionsEx#2159]
Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:157)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:348)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:351)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:323)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:420)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:384)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:339)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:240)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by zml2008** [comment]
read the release notes...
