### ISSUE TITLE
Mysql frequent Errors

### ISSUE THREAD

**Issue by jebr** [PEXPlugins/PermissionsEx#2163]
### Description ###

[21:27:46 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vZRZx. Full error:
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
        at ru.tehkode.permissions.backends.sql.SQLData.fetchInfo(SQLData.java:70)
        at ru.tehkode.permissions.backends.sql.SQLData.<init>(SQLData.java:34)
        at ru.tehkode.permissions.backends.sql.SQLBackend.getUserData(SQLBackend.java:263)
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:220)
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:201)
        at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:53)
        at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:39)
        at ru.tehkode.permissions.bukkit.SuperpermsListener.onSystemEvent(SuperpermsListener.java:268)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at ru.tehkode.permissions.bukkit.PermissionsEx.callEvent(PermissionsEx.java:393)
        at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:697)
        at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:701)
        at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:659)
        at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:645)
        at ru.tehkode.permissions.bukkit.commands.UtilityCommands.reload(UtilityCommands.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:248)
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:110)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:315)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646)
        at me.william.simplecommandscheduler.Main$1.run(Main.java:21)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
        at sun.reflect.GeneratedConstructorAccessor105.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
        at com.mysql.jdbc.Util.getInstance(Util.java:382)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
        at ru.tehkode.libs.org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java
:38)
        at ru.tehkode.libs.org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:5
82)
        at ru.tehkode.libs.org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
        at ru.tehkode.libs.org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
        at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245)
        at ru.tehkode.permissions.backends.sql.SQLData.fetchInfo(SQLData.java:58)
        ... 39 more

**Comment by zml2008** [comment]
Raise the limit on connections allowed to your MySQL server
