### ISSUE TITLE
PermisssionsEX Doesn't load on server launch.

### ISSUE THREAD

**Issue by Arctic-JD** [PEXPlugins/PermissionsEx#2164]
My PermissionsEX 1.7.10 file doesn't load! I'm not using Groupmanager, so I'm resorting to PEX.
Here's the file Error:
ull error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source) 

[Is available here](https://gist.github.com/819f0de6db2281d8e2b6)

**Comment by zml2008** [comment]
Read the release notes for the latest release of PEX
