### ISSUE TITLE
[PermissionsEx] Error occurred with PermissionsEx! Please post  it to http://git.io/vZ1oh. Full error:

### ISSUE THREAD

**Issue by Realmpixel** [PEXPlugins/PermissionsEx#2167]
### Description ###

[16:38:17] [pool-16-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vZ1BC. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
	at org.bukkit.craftbukkit.v1_7_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:111)
	at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock.checkLocked(slot_lock.java:402)
	at io.hotmail.com.jacob_vejvoda.slot_lock.slot_lock$6.run(slot_lock.java:233)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:638)
	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284)
	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
### Detailed Information ###

[Is available here](https://gist.github.com/ce4374a6b513f6b92ba7)

**Comment by zml2008** [comment]
slot_lock is broken
