### ISSUE TITLE
Doesnt seem to work with new sponge-1.8-1499-2.1DEV-650

### ISSUE THREAD

**Issue by LunaticXCrazy** [PEXPlugins/PermissionsEx#2172]
Basicly this happens everytime i want to run the server:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1499-2.1DEV-650.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 9/23/15 6:04 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: ninja.leaping.permissionsex.sponge.PermissionsExPlugin
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ninja.leaping.permissionsex.sponge.PermissionsExPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
	... 5 more
Caused by: java.lang.UnsupportedClassVersionError: ninja/leaping/permissionsex/sponge/PermissionsExPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 39960688 bytes (38 MB) / 425721856 bytes (406 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	UC	Forge{11.14.3.1450} [Minecraft Forge] (minecraft_server.jar) 
	UC	Sponge{1.8-1499-2.1DEV-650} [SpongeForge] (minecraft.jar) 
	UC	customnpcs{1.8.0_beta} [CustomNPCs] (CustomNPCs_1.8.0_beta.jar) 
	UE	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UC	SpongeEssentialCmds{2.8} [SpongeEssentialCmds] (SpongeEssentialCmds-2.8e.jar) 
	UC	supersentai{1.0.0} [SuperSentai] (SuperSentaiMod-v.1.0.0-forge-1.8-11.14.1.1341.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1499-2.1DEV-650.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by LunaticXCrazy** [comment]
Never mind didnt have java jre8 well at least who ever finds this and has same problem you know what to install :)
