### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rinns** [PEXPlugins/PermissionsEx#2177]
it to http://git.io/vcWgi. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)
Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.jav
a:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.ja
va:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:356)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:316)
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
18)
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
82)
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
37)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:256)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:528)
        at java.lang.Thread.run(Unknown Source)

**Comment by zml2008** [comment]
Update PEX
