### ISSUE TITLE
SQL Error with connection

### ISSUE THREAD

**Issue by evaldas867** [PEXPlugins/PermissionsEx#2180]
[23:34:31 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vcNu3. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can\'t DROP \'unique\'; check that column/key exists
at ru.tehkode.permissions.backends.sql.SQLBackend$1.performUpdate(SQLBackend.java:131)
at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
at ru.tehkode.permissions.backends.sql.SQLBackend.&lt;init&gt;(SQLBackend.java:192)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
at ru.tehkode.permissions.PermissionManager.&lt;init&gt;(PermissionManager.java:67)
at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746)
at org.bukkit.Bukkit.reload(Bukkit.java:534)
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can\'t DROP \'unique\'; check that column/key exists
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
at com.mysql.jdbc.Util.getInstance(Util.java:382)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
at ru.tehkode.permissions.backends.sql.SQLBackend$1.performUpdate(SQLBackend.java:129)
... 36 more

**Comment by CzEMC** [comment]
Similar to #2229

Follow instructions on issue #2229 and reply your results here.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
