### ISSUE TITLE
SQL Error when plugin is loading

### ISSUE THREAD

**Issue by HamsterCrack** [PEXPlugins/PermissionsEx#2192]
[18:43:54 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vWeqS. Full error: ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list' at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:188) at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90) at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:194) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:684) at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list' at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) at com.mysql.jdbc.Util.getInstance(Util.java:382) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273) at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:163) ... 24 more

**Comment by CzEMC** [comment]
Similar to #2193

Follow instructions that I've posted there and see if that helps.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
