### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Alcarin350** [PEXPlugins/PermissionsEx#2202]
19:42:52] [pool-69-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2Ff2a83a68dd6940a58743%29%0A. Full error:
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 32,599 milliseconds ago. The last packet sent successfully to the server was 0 milliseconds ago. 
 at ru.tehkode.permissions.backends.sql.SQLBackend.getDefaultGroupNames(SQLBackend.java:183) 
 at ru.tehkode.permissions.PermissionManager.getDefaultGroups(PermissionManager.java:568) 
 at ru.tehkode.permissions.PermissionUser.getParentsInternal(PermissionUser.java:94) 
 at ru.tehkode.permissions.PermissionEntity.getParentIdentifiers(PermissionEntity.java:853) 
 at ru.tehkode.permissions.bukkit.SuperpermsListener.updatePlayerMetadata(SuperpermsListener.java:97) 
 at ru.tehkode.permissions.bukkit.SuperpermsListener.updateSelective(SuperpermsListener.java:190) 
 at ru.tehkode.permissions.bukkit.SuperpermsListener.onEntityEvent(SuperpermsListener.java:204) 
 at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
 at java.lang.reflect.Method.invoke(Unknown Source) 
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) 
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) 
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) 
 at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:759) 
 at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:720) 
 at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:724) 
 at ru.tehkode.permissions.PermissionEntity.setSuffix(PermissionEntity.java:185) 
 at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.setPlayerSuffix(Chat_PermissionsEx.java:311) 
 at net.milkbowl.vault.chat.Chat.setPlayerSuffix(Chat.java:228) 
 at com.entrapmentserver.ChatListener.onPlayerChat(ChatListener.java:108) 
 at sun.reflect.GeneratedMethodAccessor278.invoke(Unknown Source) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
 at java.lang.reflect.Method.invoke(Unknown Source) 
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) 
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) 
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) 
 at net.minecraft.network.NetHandlerPlayServer$5.evaluate(NetHandlerPlayServer.java:1208) 
 at org.bukkit.craftbukkit.v1_7_R4.util.Waitable.run(Waitable.java:24) 
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:880) 
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) 
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) 
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) 
 at java.lang.Thread.run(Unknown Source) 
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 32,599 milliseconds ago. The last packet sent successfully to the server was 0 milliseconds ago. 
 at sun.reflect.GeneratedConstructorAccessor175.newInstance(Unknown Source) 
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 
 at java.lang.reflect.Constructor.newInstance(Unknown Source) 
 atcom.mysql.jdbc.Util.handleNewInstance(Util.java:407) 
 at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116) 
 at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082) 
 at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968) 
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516) 
 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) 
 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) 
 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) 
 at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) 
 at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273) 
 at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) 
 at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) 
 at ru.tehkode.permissions.backends.sql.SQLBackend.getDefaultGroupNames(SQLBackend.java:173) 
 ... 34 more 
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost. 
 at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529) 
 at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979) 
 ... 44 more

**Comment by zml2008** [comment]
Update PEX to the latest 1.7-compatible version.
