### ISSUE TITLE
PeermissionsEx keeps breaking

### ISSUE THREAD

**Issue by ZombiesM16** [PEXPlugins/PermissionsEx#2204]
### Description ###
At some time pex always breaks. It use to not break. What is causing pex to break?
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
	at org.bukkit.Bukkit.reload(Bukkit.java:535)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
### Detailed Information ###

[Is available here](https://gist.github.com/db0d7b82f6f44d850b0a)

**Comment by zml2008** [comment]
You're running an outdated version of PEX on a 1.8 server.

**Comment by ZombiesM16** [comment]
So PermissionsEx-1.23.3 isn't the latest version

**Comment by zml2008** [comment]
It is the latest, but that's not what you're running (You're running 1.22.9).

**Comment by ZombiesM16** [comment]
Can you give me the link to the latest version
