### ISSUE TITLE
PermissionsEx Error | Plugin does not work

### ISSUE THREAD

**Issue by craftsmany** [PEXPlugins/PermissionsEx#2206]
### Description ###

[Insert description of issue here]
### Detailed Information ###
[04:53:18] [pool-9-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vlWAh. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
	at java.lang.Thread.run(Thread.java:745)

[Is available here](https://gist.github.com/bbeb76a7f84a5be7eec6)

**Comment by craftsmany** [comment]
i have tested the plugin on another server, it doesn't work either

**Comment by htilly** [comment]
Having the same problem...

**Comment by zml2008** [comment]
You're running the 1.7 version of PEX on a 1.8 server. Update.
