### ISSUE TITLE
PeX Not Loading

### ISSUE THREAD

**Issue by PandemicMC** [PEXPlugins/PermissionsEx#2215]
### Description ###

Plugin will not load. Database error?

[23:36:23 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/v8Z4k. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
        at org.bukkit.Bukkit.reload(Bukkit.java:535)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:745)

### Detailed Information ###

[Is available here](https://gist.github.com/c2cc96a3f07dc0f29198)

**Comment by zml2008** [comment]
You're using the 1.7 version of PEX on a 1.8 server.
