### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ti-wil** [PEXPlugins/PermissionsEx#2219]
### Description ###
Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
at ru.tehkode.permissions.RegExpMatcher.‹init›(RegExpMatcher.java:17)
at ru.tehkode.permissions.PermissionManager.‹init›(PermissionManager.java:58)
at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:341)
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:313)
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503)
at java.lang.Thread.run(Thread.java:745)

(https://gist.github.com/c5745991bc94f3f31843)

**Comment by zml2008** [comment]
1.7 PEX on a 1.8 server
