### ISSUE TITLE
Can't DROP 'name'; check that column/key exists

### ISSUE THREAD

**Issue by PyPKjE** [PEXPlugins/PermissionsEx#2229]
### Description

ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can't DROP 'name'; check that column/key exists
### Detailed Information

[19:27:34] [pool-27-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/v49V4. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can't DROP 'name'; check that column/key exists
    at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
    at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
    at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
    at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
    at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
    at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can't DROP 'name'; check that column/key exists
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
    at com.mysql.jdbc.Util.getInstance(Util.java:382)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
    at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
    at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
    at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:179)
    ... 24 more

**Comment by CzEMC** [comment]
Does permissionsEx the have the sufficient SQL privileges?

If you think so, try backing up tables, and dropping all tables in the pex database and let pex rebuild them. Then, re upload only the SQL data to the database and see if that fixed the problem.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
