### ISSUE TITLE
Error retreating methods from google common CacheBuilder when enabling pex

### ISSUE THREAD

**Issue by GregZ123** [PEXPlugins/PermissionsEx#2244]
### Basic info ###

**Server version:** 1.8.8-R0.1-SNAPSHOT *running on* git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

**Online mode:** true

**Java version:** Oracle Corporation - Java Runtime Environment - 1.8.0_66

**Plugins (6):** (~~Strikeout~~ means disabled)
- ~~PermissionsEx *v1.22.9*~~ (```ru.tehkode.permissions.bukkit.PermissionsEx```)
- WorldEdit *v6.1;no_git_id* (```com.sk89q.worldedit.bukkit.WorldEditPlugin```)
- ~~Essentials *vTeamCity*~~ (```com.earth2me.essentials.Essentials```)
- Vault *v1.5.3-b37* (```net.milkbowl.vault.Vault```)
- ~~Multiverse-Core *v2.4-b527*~~ (```com.onarandombox.MultiverseCore.MultiverseCore```)
- ~~SurvivalGames *v0.4*~~ (```me.gregz_.survivalgames.SurvivalGames```)

### What PEX Saw ###

**Reason:** Error while enabling: 

**Stacktrace:**
```
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
	at java.lang.Thread.run(Unknown Source)

```
### PEX configuration ###
```yaml
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false

```
### Permissions database ###

**Active backend:** unknown
```yaml
Permissions configuration could not be read. Does it exist?
```

**Comment by Stormbow** [comment]
Wrong version of PEX being used on 1.8.8 server.
