### ISSUE TITLE
So,It`s a problem with permissionsex2.0-Sponge  It can not be use.

### ISSUE THREAD

**Issue by SmithJiong** [PEXPlugins/PermissionsEx#2245]
the crashport about the plugin was like this

 sponge ver is ：spongeforge-1.8-1563-2.1-DEV-814.jar
 forge ver is ： forge-1.8-11.14.4.1563

 22:40:35] [Server thread/ERROR] [Sponge]: [Plugin Class: ninja.leaping.permissionsex.sponge.PermissionsExPlugin][Handler: onPreInit]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.handleModStateEvent(SpongeModPluginContainer.java:129) [SpongeModPluginContainer.class:1.8-1563-2.1-DEV-814]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: Error occurred while enabling PermissionsEx
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:136) ~[PermissionsExPlugin.class:?]
	... 32 more
Caused by: ninja.leaping.permissionsex.exception.PermissionsLoadingException: While loading permissions file from config\permissionsex\permissions.json
	at ninja.leaping.permissionsex.backend.file.FileDataStore.initializeInternal(FileDataStore.java:119) ~[FileDataStore.class:?]
	at ninja.leaping.permissionsex.backend.AbstractDataStore.initialize(AbstractDataStore.java:65) ~[AbstractDataStore.class:?]
	at ninja.leaping.permissionsex.PermissionsEx.initialize(PermissionsEx.java:295) ~[PermissionsEx.class:?]
	at ninja.leaping.permissionsex.PermissionsEx.<init>(PermissionsEx.java:107) ~[PermissionsEx.class:?]
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:134) ~[PermissionsExPlugin.class:?]
	... 32 more
Caused by: java.nio.file.NoSuchFileException: config\permissionsex\permissions.json
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_66]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_66]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_66]
	at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:1.8.0_66]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_66]
	at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_66]
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader$Builder.lambda$setPath$1(AbstractConfigurationLoader.java:68) ~[AbstractConfigurationLoader$Builder.class:1.8-1563-2.1-DEV-814]
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:118) ~[AbstractConfigurationLoader.class:1.8-1563-2.1-DEV-814]
	at ninja.leaping.permissionsex.backend.file.FileDataStore.initializeInternal(FileDataStore.java:117) ~[FileDataStore.class:?]
	at ninja.leaping.permissionsex.backend.AbstractDataStore.initialize(AbstractDataStore.java:65) ~[AbstractDataStore.class:?]
	at ninja.leaping.permissionsex.PermissionsEx.initialize(PermissionsEx.java:295) ~[PermissionsEx.class:?]
	at ninja.leaping.permissionsex.PermissionsEx.<init>(PermissionsEx.java:107) ~[PermissionsEx.class:?]
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:134) ~[PermissionsExPlugin.class:?]
	... 32 more

**Comment by zml2008** [comment]
Create the files config/permissionsex/permissionsex.conf and config/permissionsex/permissions.json before you start the server. Also make sure if you update Sponge that you update PEX to the latest build.
