### ISSUE TITLE
GamePreInitializationEvent

### ISSUE THREAD

**Issue by seema84** [PEXPlugins/PermissionsEx#2252]
Sponge Vanilla ->

[Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=PermissionsEx, name=PermissionsEx, version=2.0-SNAPSHOT}
java.lang.RuntimeException: Error occurred while enabling PermissionsEx
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:137) ~[PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_PermissionsExPlugin_onPr
eInit8.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-2.1-DEV-90]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:247) [SpongeEventMan
ager.class:1.8-2.1-DEV-90]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:258) [SpongeEventManager.class:1.8-2.1-DEV-90]
        at org.spongepowered.server.SpongeVanilla.postState(SpongeVanilla.java:194) [SpongeVanilla.class:1.8-2
.1-DEV-90]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:113) [SpongeVanilla.class:1.8-2.1-DEV-90]
        at net.minecraft.server.dedicated.DedicatedServer.onServerLoad(SourceFile:53) [po.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:97) [po.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:417) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.nio.file.NoSuchFileException: config\permissionsex\permissionsex.conf
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_66]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_66]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_66]
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:1.8.0_66]
        at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_66]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_66]
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader$Builder.lambda$setPath$1(AbstractConfi
gurationLoader.java:68) ~[spongevanilla-1.8-2.1-DEV-90.jar:1.8-2.1-DEV-90]
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:
118) ~[spongevanilla-1.8-2.1-DEV-90.jar:1.8-2.1-DEV-90]
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:
110) ~[spongevanilla-1.8-2.1-DEV-90.jar:1.8-2.1-DEV-90]
        at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfi
guration.java:63) ~[FilePermissionsExConfiguration.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:135) ~[PermissionsExPlugin.class:?]
        ... 10 more

**Comment by zml2008** [comment]
You have to create the files permissionsex.conf and permissions.json in `config/permissionsex` before starting the server.

**Comment by seema84** [comment]
manually? 0o
