### ISSUE TITLE
Monsters can not respawn in the world

### ISSUE THREAD

**Issue by SmithJiong** [PEXPlugins/PermissionsEx#2258]
So,i found this issue about PermissionsEx2.0-sponge 

The server will stop spawned any monsters after i used  this plugin when the server used offline mod.

But it will be right when server was running in online mod .SO  I want to know if the plugin  support the offline mod and how can i fix this problem.

In fact,there was an error message when server was running in offline mod  after the other users login:

[15:41:21] [Netty Server IO #2/ERROR] [Sponge]: Could not pass ClientConnectionE
vent$Auth$Impl to Plugin{id=PermissionsEx, name=PermissionsEx, version=2.0-SNAPS
HOT}
java.lang.NullPointerException
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.cacheUserAsync
(PermissionsExPlugin.java:197) ~[PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.AuthListener_PermissionsExPlu
gin_cacheUserAsync3.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredLi
stener.java:86) ~[RegisteredListener.class:1.8-1577-2.1-DEV-920]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventMan
ager.java:247) [SpongeEventManager.class:1.8-1577-2.1-DEV-920]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEvent
Manager.java:274) [SpongeModEventManager.class:1.8-1577-2.1-DEV-920]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEvent
Manager.java:242) [SpongeModEventManager.class:1.8-1577-2.1-DEV-920]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:111) [S
pongeImpl.class:1.8-1577-2.1-DEV-920]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetH
andlerLoginServer.java:103) [rq.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEventOffli
ne(NetHandlerLoginServer.java:114) [rq.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147316_a(NetH
andlerLoginServer.java:142) [rq.class:?]
        at net.minecraft.network.login.client.C00PacketLoginStart.func_180773_a(
SourceFile:33) [ni.class:?]
        at net.minecraft.network.login.client.C00PacketLoginStart.func_148833_a(
SourceFile:10) [ni.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java
:136) [gr.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java
:414) [gr.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChanne
lInboundHandler.java:103) [SimpleChannelInboundHandler.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Fin
al]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final
]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:153) [ByteToMessageDecoder.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Fin
al]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final
]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:153) [ByteToMessageDecoder.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Fin
al]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final
]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHa
ndler.java:149) [ReadTimeoutHandler.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Fin
al]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final
]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:785) [DefaultChannelPipeline.class:4.0.15.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:132) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.15.Fi
nal]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:485) [NioEventLoop.class:4.0.15.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:452) [NioEventLoop.class:4.0.15.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346) [NioEven
tLoop.class:4.0.15.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:101) [SingleThreadEventExecutor$2.class:4.0.15.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by zml2008** [comment]
This is probably a sponge issue -- the offline-mode profile used here doesn't have any uuid assigned. PEX needs a uuid for each user. However, we also don't support offline mode unless you're using it through a proxy -- like bungee or lilypad. For bungee you have to enable the appropriate sponge config setting.

PEX doesn't do anything to affect mob spawning -- that's probably something else.
