### ISSUE TITLE
Permission EX

### ISSUE THREAD

**Issue by LeonPlayZ** [PEXPlugins/PermissionsEx#2273]
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
    at java.security.AccessController.checkPermission(AccessController.java:884)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at java.util.concurrent.ThreadPoolExecutor.checkShutdownAccess(ThreadPoolExecutor.java:735)
    at java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1387)
    at java.util.concurrent.ScheduledThreadPoolExecutor.shutdown(ScheduledThreadPoolExecutor.java:761)
    at java.util.concurrent.Executors$DelegatedExecutorService.shutdown(Executors.java:669)
    at ru.tehkode.permissions.PermissionManager.initTimer(PermissionManager.java:678)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:210)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
    at java.lang.Thread.run(Thread.java:745)

**Comment by zml2008** [comment]
What environment are you running this in? (Server implementation, versions, host (if applicable), control panel, etc) There isn't any SecurityManager installed by default.

**Comment by Someone-NEW** [comment]
So witch wersion coul be used when i use Spigot 1.8.8 and java 8 PermissionsEx v1.22.10 or PermissionsEx v1.22.4 ??
Thanks you guys for all that work you made i hope timed permissions work.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
