### ISSUE TITLE
[sponge]when player join server case NPE.

### ISSUE THREAD

**Issue by jaciloy** [PEXPlugins/PermissionsEx#2278]
[10:55:12] [Netty Server IO #1/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Auth$Impl to Plugin{id=PermissionsEx, name=PermissionsEx, version=2.0-SNAPSHOT}
java.lang.NullPointerException
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.cacheUserAsync(PermissionsExPlugin.java:197) ~[PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.AuthListener_PermissionsExPlugin_cacheUserAsync14.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-1577-2.1-DEV-967]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:231) [SpongeModEventManager.class:1.8-1577-2.1-DEV-967]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:275) [SpongeModEventManager.class:1.8-1577-2.1-DEV-967]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:243) [SpongeModEventManager.class:1.8-1577-2.1-DEV-967]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:111) [SpongeImpl.class:1.8-1577-2.1-DEV-967]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:102) [rq.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEventOffline(NetHandlerLoginServer.java:113) [rq.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147316_a(NetHandlerLoginServer.java:142) [rq.class:?]
        at net.minecraft.network.login.client.C00PacketLoginStart.func_180773_a(SourceFile:33) [ni.class:?]
        at net.minecraft.network.login.client.C00PacketLoginStart.func_148833_a(SourceFile:10) [ni.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:136) [gr.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:414) [gr.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [SimpleChannelInboundHandler.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153) [ByteToMessageDecoder.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153) [ByteToMessageDecoder.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:4.0.15.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:132) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.15.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485) [NioEventLoop.class:4.0.15.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452) [NioEventLoop.class:4.0.15.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346) [NioEventLoop.class:4.0.15.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:4.0.15.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
[10:55:12] [Netty Server IO #1/INFO] [FML]: Client protocol version 2

**Comment by zml2008** [comment]
Don't use offline mode.
