### ISSUE TITLE
PermissionEx not working

### ISSUE THREAD

**Issue by Alexima** [PEXPlugins/PermissionsEx#2290]
I have gotten the following error(read below) when i try to use PermissionsEx, please help me fix this.

java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:740)
        at org.bukkit.Bukkit.reload(Bukkit.java:534)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
        at java.lang.Thread.run(Thread.java:745)

**Comment by CzEMC** [comment]
It would be helpful if you told us what your jar version is.

If its 1.8, then stop your server, download the latest version of pex again, and upload it it your server, delete the old version of pex, and then start your server.

**Comment by zml2008** [comment]
Update PEX to the latest version from 1.23.x
