### ISSUE TITLE
[SEVERE] [PermissionsEx] Error occurred with PermissionsEx! Glowstone++ v1.8.9

### ISSUE THREAD

**Issue by netsequent** [PEXPlugins/PermissionsEx#2293]
Full error:
```
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
        at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:810)
        at net.glowstone.GlowServer.start(GlowServer.java:513)
        at net.glowstone.GlowServer.run(GlowServer.java:135)
        at net.glowstone.GlowServer.main(GlowServer.java:110)
```

**Comment by zml2008** [comment]
You need to run the latest PEX 1.23.x version.
