### ISSUE TITLE
PermissionsEx giving error when starting server

### ISSUE THREAD

**Issue by PandaK551** [PEXPlugins/PermissionsEx#2303]
Im on SpongeForge 1065
Forge Version: 11.15.0.1707

[14:34:28] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=PermissionsEx, name=PermissionsEx, version=2.0-SNAPSHOT}
java.lang.RuntimeException: Error occurred while enabling PermissionsEx
    at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:136) ~[PermissionsExPlugin.class:?]
    at org.spongepowered.common.event.listener.GamePreInitializationEventListener_PermissionsExPlugin_onPreInit4.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1694-3.1.0-BETA-1065]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:233) [SpongeModEventManager.class:1.8.9-1694-3.1.0-BETA-1065]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277) [SpongeModEventManager.class:1.8.9-1694-3.1.0-BETA-1065]
    at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:184) [SpongeMod.class:1.8.9-1694-3.1.0-BETA-1065]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.onPost(LoadController.java:53) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) [ko.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.io.IOException: configurate.typesafe.config.ConfigException$Parse: Reader: 23: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes)
    at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:157) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:42) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:63) ~[FilePermissionsExConfiguration.class:?]
    at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:134) ~[PermissionsExPlugin.class:?]
    ... 33 more
Caused by: configurate.typesafe.config.ConfigException$Parse: Reader: 23: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes)
    at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201) ~[ConfigDocumentParser$ParseContext.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197) ~[ConfigDocumentParser$ParseContext.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:482) ~[ConfigDocumentParser$ParseContext.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:595) ~[ConfigDocumentParser$ParseContext.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14) ~[ConfigDocumentParser.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260) ~[Parseable.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248) ~[Parseable.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:180) ~[Parseable.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:174) ~[Parseable.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.impl.Parseable.parse(Parseable.java:299) ~[Parseable.class:1.8.9-1694-3.1.0-BETA-1065]
    at configurate.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:668) ~[ConfigFactory.class:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:104) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:149) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:42) ~[spongeforge-1.8.9-1694-3.1.0-BETA-1065.jar:1.8.9-1694-3.1.0-BETA-1065]
    at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:63) ~[FilePermissionsExConfiguration.class:?]
    at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:134) ~[PermissionsExPlugin.class:?]
    ... 33 more
[14:34:28] [Server thread/TRACE] [sponge/sponge]: Sent event FMLPreInitializationEvent to mod sponge

**Comment by zml2008** [comment]
You have a syntax error in your `permissionsex.conf` file -- pastebin it if you want some help.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
