### ISSUE TITLE
Erm Help!

### ISSUE THREAD

**Issue by KingCurry1717** [PEXPlugins/PermissionsEx#2326]
Ok so, when I added in new permissions to PEX, it started loading the plugin on server restart, then gave me this error, 

ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
    at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_80]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_80]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_80]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_80]
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx.jar:?]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
    at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx.jar:?]
    at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx.jar:?]

here is the pastebin link to the config file
http://pastebin.com/pihcW3Ew
Thank You in Advance

**Comment by zml2008** [comment]
For some reason your whole permissions file is wrapped in a string. Delete the `'` characters at the beginning and ends of your permissions.yml.

**Comment by zml2008** [comment]
Check http://yaml-online-parser.appspot.com to find and correct errors in your permissions.yml.
