### ISSUE TITLE
Didn't work...

### ISSUE THREAD

**Issue by KingCurry1717** [PEXPlugins/PermissionsEx#2327]
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx-1.23.4.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_80]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_80]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 2, column 3:
      Pilot:
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 90, column 4:
       Captain:
       ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
	... 23 more
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 2, column 3:
      Pilot:
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 90, column 4:
       Captain:
       ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
	... 23 more

This was after I removed the ' before and after the config
Here is the Pastebin link again: http://pastebin.com/Hyca2sGX

**Comment by zml2008** [comment]
Post in your existing issue #2326 -- don't waste space with a new one.
