### ISSUE TITLE
Permission problems with 1.9

### ISSUE THREAD

**Issue by alien12** [PEXPlugins/PermissionsEx#2346]
When using essentials, fly mode is not correctly disabled on worlds where the user does not have permissions. Using the latest version of PEX from Jenkins (Feb 14th) however throws errors on server start.
The problem may be essentials related, not sure.

`[20:28:31] [Server thread/ERROR]: Could not pass event PluginEnableEvent to Essentials vTeamCity
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NoClassDefFoundError: ru/tehkode/permissions/bukkit/PermissionsEx
	at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:121) ~[?:?]
	at com.earth2me.essentials.EssentialsPluginListener.onPluginEnable(EssentialsPluginListener.java:30) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	... 13 more
Caused by: java.lang.ClassNotFoundException: ru.tehkode.permissions.bukkit.PermissionsEx
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:121) ~[?:?]
	at com.earth2me.essentials.EssentialsPluginListener.onPluginEnable(EssentialsPluginListener.java:30) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-dd155ed-31caee5]
	... 13 more`

**Comment by Tslat** [comment]
I'm having various other permissions issues too
No errors being thrown, but permissions randomly not working, even for ops sometimes

**Comment by KanjiOkami** [comment]
I am sure someone will correct me if I am wrong but I am certain this is because you are trying to use pex with a version that has had no work towards compatibility published yet so I am not surprised you are having problems.

**Comment by Tslat** [comment]
Not surprising at all
They did do a build for 1.9, but it looks like it was just one made to avoid any crashing

That's the one I'm using anyway

**Comment by alien12** [comment]
Thought it would be better to make a post rather than not as the page says it's compatible with 1.9 but appears to have some issues.

**Comment by zml2008** [comment]
On March 4, 2016 5:37:46 AM PST, alien12 <notifications@github.com> wrote:
>Thought it would be better to make a post rather than not as the page
>says it's compatible with 1.9 but appears to have some issues.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PEXPlugins/PermissionsEx/issues/2346#issuecomment-192286719

You're using a development version of a complete rewrite of pex. 1.23.4 is the recommended version of pex for 1.9

**Comment by alien12** [comment]
Regardless the rewrite works better than the recommended version. The rewrite just throws that error whereas recommended seems to ignore some permissions.

**Comment by Tslat** [comment]
Yeah 1.23.4 ignores a lot of permissions.

I'm getting messages saying I don't have permission to do things, but when I go /pex user check
It says I have the permission

**Comment by zml2008** [comment]
Example?

**Comment by Tslat** [comment]
It varies heavily.
I have my permissions set up per-group only, and yet two different people in that group can find that they may be unable to do something that the other can. Resetting their group may work.

One that seems to be persistent is
McMMO /inspect on far/distant players (It's not McMMO, I've checked my code)

**Comment by alien12** [comment]
I've only noticed what i wrote in my original post this far.
If you use /fly in a world you have permission to then switch to a world you dont then flying remains enabled although you cant use /fly anymore. Previously and with the rewrite it is automatically disabled in worlds you dont have permission.

**Comment by Permanently** [comment]
Woah, sh*t is getting down for real.
Just saying.

(also I think a rewrite for 1.9 would help :+1: )

**Comment by zml2008** [comment]
The original issue here was a compatibility issue between PEX2 and EssentialsX that has been fixed already -- this further underscores that PEX2 is a complete rewrite with many functional changes. The other changes are most likely weird event interactions between PEX and other permissions plugins on world change (PEX not changing early enough?)
