### ISSUE TITLE
NPE in onPlayerJoin at PermissionsExPlugin.java:219

### ISSUE THREAD

**Issue by viveleroi** [PEXPlugins/PermissionsEx#2365]
Using latest Pex development build and SpongeForge 1213. This flaw is fatal and breaks permissions completely for us.

```
[12:23:24] [Server thread/ERROR] [Sponge/]: Could not pass PlayerLoggedInEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@197d7543
java.lang.NullPointerException
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPlayerJoin(PermissionsExPlugin.java:219) ~[PermissionsExPlugin.class:?]
	at org.spongepowered.common.event.listener.JoinListener_PermissionsExPlugin_onPlayerJoin12.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1763-4.1.0-BETA-1213]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1213]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:199) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1213]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:279) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1213]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1213]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:128) [SpongeImpl.class:1.8.9-1763-4.1.0-BETA-1213]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:325) [lx.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) [ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by viveleroi** [comment]
I've realized that both the old and new folder names existed, and the existence of the original was throwing `DirectoryNotEmptyException`. I've removed the original folder and this error has been resolved.
