### ISSUE TITLE
removing as player's prefix/suffix with a single double quote causes error

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2371]
```
[10:29:08] [Client thread/INFO]: [CHAT] leasoncre: /pex user leasoncre suffix "
[10:29:10] [Client thread/INFO]: [CHAT] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
[10:29:10] [Client thread/INFO]: [CHAT] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[10:29:10] [Client thread/INFO]: [CHAT] 	at java.lang.String.substring(String.java:1967)
[10:29:10] [Client thread/INFO]: [CHAT] 	at ru.tehkode.permissions.commands.CommandsManager$CommandSyntax.getMatchedArguments(CommandsManager.java:195)
[10:29:10] [Client thread/INFO]: [CHAT] 	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:89)
[10:29:10] [Client thread/INFO]: [CHAT] 	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:315)
[10:29:10] [Client thread/INFO]: [CHAT] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:29:10] [Client thread/INFO]: [CHAT] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:29:10] [Client thread/INFO]: [CHAT] 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[10:29:10] [Client thread/INFO]: [CHAT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:29:10] [Client thread/INFO]: [CHAT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:29:10] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:29:10] [Client thread/INFO]: [CHAT] 	at java.lang.Thread.run(Thread.java:745)
```

probably a known bug? but pex said report it. 
PS. why print the error to the client instead of console?

**Comment by Stormbow** [comment]
Have you tried using 2 apostrophes?

**Comment by leasoncre** [comment]
yeah, that works fine. was trying to completely clear the suffix i had (remove it from shoing up in /pex user leasoncre, but guess i can't remove the variable completely with commands

**Comment by Stormbow** [comment]
If all else fails, you can open the permissions.yml file with Notepad and delete it from there, too.
