### ISSUE TITLE
Error occurred with PermissionsEx!

### ISSUE THREAD

**Issue by MCnyrein** [PEXPlugins/PermissionsEx#2383]
### Description ###
[18:09:50 ERROR]: Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+performing+PEX+check%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.NullPointerException%0D%0A%09at+ru.tehkode.permissions.backends.file.FileEntity.getNode%28FileEntity.java%3A48%29%0D%0A%09at+ru.tehkode.permissions.backends.file.FileEntity.%3Cinit%3E%28FileEntity.java%3A42%29%0D%0A%09at+ru.tehkode.permissions.backends.file.FileUser.%3Cinit%3E%28FileUser.java%3A39%29%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.getUser%28FileBackend.java%3A111%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.getUser%28PermissionManager.java%3A116%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.getUser%28PermissionManager.java%3A135%29%0D%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.getUser%28PermissionsEx.java%3A201%29%0D%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.performCheck%28PermissiblePEX.java%3A150%29%0D%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.checkPermission%28PermissiblePEX.java%3A125%29%0D%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.hasPermission%28PermissiblePEX.java%3A116%29%0D%0A%09at+org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission%28CraftHumanEntity.java%3A102%29%0D%0A%09at+com.massivecraft.massivecore.util.PermUtil.has%28PermUtil.java%3A29%29%0D%0A%09at+com.massivecraft.massivecore.util.PermUtil.has%28PermUtil.java%3A38%29%0D%0A%09at+com.massivecraft.massivecore.MassiveCorePerm.has%28MassiveCorePerm.java%3A72%29%0D%0A%09at+com.massivecraft.massivecore.MassiveCoreEngineVariable.variableBuffer%28MassiveCoreEngineVariable.java%3A141%29%0D%0A%09at+com.massivecraft.massivecore.MassiveCoreEngineVariable.variable%28MassiveCoreEngineVariable.java%3A68%29%0D%0A%09at+com.massivecraft.massivecore.MassiveCoreEngineVariable.variable%28MassiveCoreEngineVariable.java%3A62%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke0%28Native+Method%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke%28Unknown+Source%29%0D%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.invoke%28Unknown+Source%29%0D%0A%09at+java.lang.reflect.Method.invoke%28Unknown+Source%29%0D%0A%09at+org.bukkit.plugin.java.JavaPluginLoader%241.execute%28JavaPluginLoader.java%3A306%29%0D%0A%09at+org.bukkit.plugin.RegisteredListener.callEvent%28RegisteredListener.java%3A62%29%0D%0A%09at+org.bukkit.plugin.SimplePluginManager.fireEvent%28SimplePluginManager.java%3A502%29%0D%0A%09at+org.bukkit.plugin.SimplePluginManager.callEvent%28SimplePluginManager.java%3A484%29%0D%0A%09at+net.minecraft.server.v1_8_R3.PlayerConnection.chat%28PlayerConnection.java%3A1084%29%0D%0A%09at+net.minecraft.server.v1_8_R3.PlayerConnection.a%28PlayerConnection.java%3A1022%29%0D%0A%09at+net.minecraft.server.v1_8_R3.PacketPlayInChat%241.run%28PacketPlayInChat.java%3A39%29%0D%0A%09at+java.util.concurrent.Executors%24RunnableAdapter.call%28Unknown+Source%29%0D%0A%09at+java.util.concurrent.FutureTask.run%28Unknown+Source%29%0D%0A%09at+java.util.concurrent.ThreadPoolExecutor.runWorker%28Unknown+Source%29%0D%0A%09at+java.util.concurrent.ThreadPoolExecutor%24Worker.run%28Unknown+Source%29%0D%0A%09at+java.lang.Thread.run%28Unknown+Source%29%0D%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0D%0A++Default%3A%0D%0A++++default%3A+true%0D%0A++++build%3A+true%0D%0A++++prefix%3A+%27%267%5BMember%5D%26f%27%0D%0A++++permissions%0D%0A++++-+essentials.help%0D%0A++++-+modifyworld.chat%0D%0A++++-+modifyworld.*%0D%0A++++-+essentials.home%0D%0A++++-+essentials.sethome%0D%0A++++-+essentials.back%0D%0A++++-+essentials.tpa%0D%0A++++-+essentials.tpaccept%0D%0A++++-+essentials.tpdeny%0D%0A++++-+essentials.spawn%0D%0A++Regular%3A%0D%0A++++build%3A+true%0D%0A++++inheritance%3A%0D%0A++++-+Default%0D%0A++++prefix%3A+%27%266%5BDonator%5D%26f%27%0D%0A++++permissions%3A%0D%0A++++-+essentials.enchant%0D%0A++++-+essentials.repair%0D%0A%0D%0A++Helper%3A%0D%0A++++build%3A+true%0D%0A++++inheritance%3A%0D%0A++++-+Default%0D%0A++++prefix%3A+%27%26b%5BModerator%5D%267%27%0D%0A++++suffix%3A+%27%267%27%0D%0A++++permissions%3A%0D%0A++++-+essentials.repair%0D%0A++++-+essentials.heal%0D%0A++++-+essentials.item%0D%0A++++-+essentials.give%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.kick%0D%0A++++-+essentials.mute%0D%0A++++-+essentials.tjail%0D%0A++++-+essentials.jail%0D%0A++++-+essentials.tempban%0D%0A++++-+essentials.vanish%0D%0A++Admin%3A%0D%0A++++build%3A+true%0D%0A++++inheritance%3A%0D%0A++++-+Moderator%0D%0A++++prefix%3A+%27%264%5B%26cAdmin%264%5D%26e%27%0D%0A++++suffix%3A+%27%267%27%0D%0A++++permissions%3A+%0D%0A++++-+essentials.gamemode%0D%0A++++-+essentials.ban%0D%0A++++-+essentials.unban%0D%0A++++-+essentials.ipban%0D%0A++++-+essentials.unipban+%0D%0A++++-+essentials.pardon%0D%0A++++-+essentials.enchant%0D%0A++Owner%3A%0D%0A++++build%3Atrue%0D%0A++++inheritance%3A%0D%0A++++-+Admin%0D%0A++++prefix%3A+%27%264%5BOwner%5D%27%0D%0A++++suffix%3A+%27%26b%27%0D%0A++++permissions%3A%0D%0A++++-+%27*%27%0D%0A++++-+kit*%0D%0A+users%3A%0D%0A++++MCnyrein%3A%0D%0A++++++++group%3A%0D%0A++++++++-Owner%0D%0A++++++++permissions%3A%0D%0A++++++++-+permissions.*%60%60%60%0Aºr. Full error:
java.lang.NullPointerException
        at ru.tehkode.permissions.backends.file.FileEntity.getNode(FileEntity.java:48)
        at ru.tehkode.permissions.backends.file.FileEntity.<init>(FileEntity.java:42)
        at ru.tehkode.permissions.backends.file.FileUser.<init>(FileUser.java:39)
        at ru.tehkode.permissions.backends.FileBackend.getUser(FileBackend.java:111)
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:116)
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:135)
        at ru.tehkode.permissions.bukkit.PermissionsEx.getUser(PermissionsEx.java:201)
        at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.performCheck(PermissiblePEX.java:150)
        at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.checkPermission(PermissiblePEX.java:125)
        at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.hasPermission(PermissiblePEX.java:116)
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
        at com.massivecraft.massivecore.util.PermUtil.has(PermUtil.java:29)
        at com.massivecraft.massivecore.util.PermUtil.has(PermUtil.java:38)
        at com.massivecraft.massivecore.MassiveCorePerm.has(MassiveCorePerm.java:72)
        at com.massivecraft.massivecore.MassiveCoreEngineVariable.variableBuffer(MassiveCoreEngineVariable.java:141)
        at com.massivecraft.massivecore.MassiveCoreEngineVariable.variable(MassiveCoreEngineVariable.java:68)
        at com.massivecraft.massivecore.MassiveCoreEngineVariable.variable(MassiveCoreEngineVariable.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022)
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by zml2008** [comment]
Update to the latest version of PEX.
