### ISSUE TITLE
group list error (PEX 2.0 on Sponge)

### ISSUE THREAD

**Issue by lasercar** [PEXPlugins/PermissionsEx#2386]
When I do the command `/pex group list` this error happens:

>
![image](https://cloud.githubusercontent.com/assets/6022168/14406616/60a57342-fe72-11e5-99ab-c83e20896577.png)
```
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationService.builder()Lorg/spongepowered/api/service/pagination/PaginationList$Builder;
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at ninja.leaping.permissionsex.sponge.SpongeCommander.msgPaginated(SpongeCommander.java:97)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at ninja.leaping.permissionsex.command.PermissionsExCommands$1.execute(PermissionsExCommands.java:90)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at ninja.leaping.permissionsex.util.command.CommandSpec.process(CommandSpec.java:163)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at ninja.leaping.permissionsex.sponge.PEXSpongeCommand.process(PEXSpongeCommand.java:43)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:252)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:44)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
[16:43:36] [Server thread/INFO] [STDERR]: [ninja.leaping.permissionsex.util.command.CommandSpec:process:169]: 	at java.lang.Thread.run(Thread.java:745)
```

Version:
>
![image](https://cloud.githubusercontent.com/assets/6022168/14406635/a625b71a-fe72-11e5-98fc-eae2fe3e5fda.png)
![image](https://cloud.githubusercontent.com/assets/6022168/14406636/b2326972-fe72-11e5-857c-758760a2ad65.png)

**Comment by zml2008** [comment]
3.1.0 versions of Sponge are pretty outdated at this point -- PEX builds against 4.0, which you should be using (download the development/"unstable" builds of Sponge).

**Comment by lasercar** [comment]
Thanks, silly me. That solved some other problems I had too!
