### ISSUE TITLE
[2.0-Sponge] Plugin does not work.

### ISSUE THREAD

**Issue by Time6628** [PEXPlugins/PermissionsEx#2405]
There are no errors in the startup log.
On prelogin this exception throws:
```
[19:44:00] [User Authenticator #1/WARN] [ninja.leaping.permissionsex/]: Error while loading data for user Optional[TimeTheCat]/c7d044f4-94db-40a0-9038-add8473d3e28 during prelogin: null
java.lang.NullPointerException
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.cacheUserAsync(PermissionsExPlugin.java:201) [PermissionsExPlugin.class:?]
	at org.spongepowered.common.event.listener.AuthListener_PermissionsExPlugin_cacheUserAsync5.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) [RegisteredListener.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:217) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:258) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) [SpongeImpl.class:1.8.9-1855-4.1.0-BETA-1310]
	at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:102) [lo.class:?]
```
On login this error throws:
```
[19:44:02] [Server thread/ERROR] [Sponge/]: Could not pass PlayerLoggedInEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@7c59fe73
java.lang.NullPointerException
	at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPlayerJoin(PermissionsExPlugin.java:219) ~[PermissionsExPlugin.class:?]
	at org.spongepowered.common.event.listener.JoinListener_PermissionsExPlugin_onPlayerJoin6.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:217) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:173) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:252) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1310]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) [SpongeImpl.class:1.8.9-1855-4.1.0-BETA-1310]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:325) [lx.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) [ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

No config files are generated in config/ninja.leaping.permissionsex either.

**Comment by zml2008** [comment]
Look for errors generated earlier in startup, and make sure you are running the latest build of PEX -- see if that fixes anything.

**Comment by Time6628** [comment]
Here's the full log. Was too long to pastebin, hastebin, or gist it.
[fml-server-latest.txt](https://github.com/PEXPlugins/PermissionsEx/files/253687/fml-server-latest.txt)

**Comment by zml2008** [comment]
That log doesn't seem to have anything useful in it -- forge's logging setup is a bit weird. There should also be just a plain latest.log in the same log folder that might have more useful information.

**Comment by Time6628** [comment]
https://gist.github.com/Time6628/464d8d70748b4f5bdcb188f88b5cbe43 - Latest.log.

**Comment by zml2008** [comment]
Well that doesn't have anything useful... gotta love Forge's logging... seems like it's working all fine? If you're still having issues pastebin your permissions.json.

**Comment by Time6628** [comment]
That's the issue, there is no permissions.json and the plugin doesn't work at all.

**Comment by XileForce** [comment]
can confirm. having the same problem here. latest pex, sponge and forge

**Comment by Abandonnn** [comment]
@zml2008 @XileForce have you guys found a fix for this yet ? I am also having the same error.

Minecraft version is 1.8.9
Running on Sponge
Pex version is 2.0

**Comment by XileForce** [comment]
As I recall this was an issue caused by enderio in conjunction with sponge. it has only been fixed in newer versions on 1.9.4 and 1.10 :(

**Comment by Abandonnn** [comment]
That's unfortunate to hear.

**Comment by Abandonnn** [comment]
I'm in desperate need of some sort of Group Manager plug-in at the moment for my server, it's the only plug-in lacking right now. Please do let me know if you find out anymore information!

**Comment by Time6628** [comment]
This a problem with sponge... sorry.

**Comment by bardkin** [comment]
So I am on sponge 1.8.9-1890 and permissionsex 2.0 as a client world just for local lan.
I dont have a permissions.json file either, and cant use ANY commands. I cant even gamemode 1...
I get You do not have permission to use this command!

Does permissionex only work in a server mode? 
Since I dont have a permissions.json, can I make one or copy one to work from? Where would it go?

**Comment by bardkin** [comment]
P.S.
Saw this in my log file. dont know if it has anything to do with it but-

[12:47:26] [Server thread/INFO]: Sawtooth_[local:E:b16d180e] logged in with entity id 232 in PEX testing(0) at (244.62913163196444, 63.0, 14.867687891799404)
[12:47:26] [Server thread/INFO]: Sawtooth_ joined the game
[12:47:27] [Client thread/INFO]: [CHAT] Sawtooth_ joined the game
[12:47:27] [pool-3-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@21cc71c6[id=9038b690-e5b1-43e6-a1f5-4f543caff272,name=Sawtooth_,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
 
Also- this is what happens when I try to use /pex group admin create

[12:47:29] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5333ms behind, skipping 106 tick(s)
[12:49:34] [Client thread/INFO]: [CHAT] Too many arguments!
[12:49:34] [Client thread/INFO]: [CHAT] Usage: /pex [ranking|[--context|--contexts|-c] [-transient] subject permission-default|delete|options|info|permission|parents|[-transient] subject-type list [filter]]
