### ISSUE TITLE
Console error + server crash

### ISSUE THREAD

**Issue by dino147** [PEXPlugins/PermissionsEx#2412]
[18:30:50] [Server thread/ERROR]: Command speed failed:

java.lang.OutOfMemoryError: PermGen space

	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0]

	at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0]

	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0]

	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0]

	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0]

	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0]

	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]

	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0]

	at com.earth2me.essentials.commands.Commandspeed.getMoveSpeed(Commandspeed.java:144) ~[?:?]

	at com.earth2me.essentials.commands.Commandspeed.run(Commandspeed.java:46) ~[?:?]

	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) ~[?:?]

	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) ~[?:?]

	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) ~[?:?]

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]

	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[?:1.7.0]

	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[?:1.7.0]

	at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[?:1.7.0]

	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

java.lang.OutOfMemoryError: PermGen space

	at sun.misc.Unsafe.defineClass(Native Method) ~[?:1.7.0]

	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63) ~[?:1.7.0]

	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399) ~[?:1.7.0]

	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:396) ~[?:1.7.0]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]

	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:395) ~[?:1.7.0]

	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:77) ~[?:1.7.0]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:46) ~[?:1.7.0]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]

	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]

	at com.sn1cko.tablist.methods.theMessages.replaceWithVariables(theMessages.java:107) ~[?:?]

	at com.sn1cko.tablist.methods.theTablist.sendTablist(theTablist.java:28) ~[?:?]

	at com.sn1cko.tablist.methods.theSwitcher$1.run(theSwitcher.java:51) ~[?:?]

	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

[18:30:54] [Server thread/INFO]: (comandant) (Fondator)dino14 : e anti-hackul....

[18:31:03] [Server thread/ERROR]: Encountered an unexpected exception

java.lang.RuntimeException: Error generating crash report

	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:777) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

Caused by: java.lang.OutOfMemoryError: PermGen space

[18:31:03] [Server thread/ERROR]: 	Cause of unexpected exception was

java.lang.OutOfMemoryError: PermGen space

[18:31:03] [Thread-419/INFO]: UUID of player casian01819 is 1c958c28-8d6e-385d-9cca-54a8760a72ab

[18:31:07] [Server thread/INFO]: Stopping server

[18:31:07] [Server thread/INFO]: [InfoBoardReborn] Disabling InfoBoardReborn v1.7.0

[18:31:07] [Async Chat Thread - #27/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 51.604ms!

[18:31:10] [Server thread/ERROR]: Error occurred while disabling InfoBoardReborn v1.7.0 (Is it up to date?)

java.lang.OutOfMemoryError: PermGen space

[18:31:10] [Thread-420/INFO]: UUID of player casian01819 is 1c958c28-8d6e-385d-9cca-54a8760a72ab

[18:31:13] [Server thread/ERROR]: Error occurred (in the plugin loader) while cancelling tasks for InfoBoardReborn v1.7.0 (Is it up to date?)

java.lang.OutOfMemoryError: PermGen space

**Comment by zml2008** [comment]
This is not a PEX issue -- this is you not having enough memory available for your server.
