### ISSUE TITLE
Issue with some backend types

### ISSUE THREAD

**Issue by Augustin37** [PEXPlugins/PermissionsEx#2419]
Hello, I just updated my server with the latest dev build, and I got this issue. I am using a mysql database for pex storage.

```java
[00:49:04] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT
[00:49:04] [Server thread/ERROR]: [PermissionsEx] Error occurred while enabling PermissionsEx
java.io.IOException: ninja.leaping.permissionsex.libs.configurate.objectmapping.ObjectMappingException: Unknown DataStore type sql
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:82) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:74) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:109) [PermissionsEx.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.4.jar:git-Paper-754]
	at org.dynmap.bukkit.permissions.PEXPermissions.create(PEXPermissions.java:24) [dynmap.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:794) [dynmap.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.9.4.jar:git-Paper-754]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.9.4.jar:git-Paper-754]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:414) [patched_1.9.4.jar:git-Paper-754]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:379) [patched_1.9.4.jar:git-Paper-754]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:333) [patched_1.9.4.jar:git-Paper-754]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:272) [patched_1.9.4.jar:git-Paper-754]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:573) [patched_1.9.4.jar:git-Paper-754]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: ninja.leaping.permissionsex.libs.configurate.objectmapping.ObjectMappingException: Unknown DataStore type sql
	at ninja.leaping.permissionsex.config.DataStoreSerializer.deserialize(DataStoreSerializer.java:35) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.config.DataStoreSerializer.deserialize(DataStoreSerializer.java:29) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.libs.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:162) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.libs.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:142) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.libs.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:80) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.libs.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:140) ~[PermissionsEx.jar:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:80) ~[PermissionsEx.jar:?]
	... 18 more
[00:49:04] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v2.0-SNAPSHOT
```

Here is my config file. For the synthax I use the wiki, and it worked well with previous dev builds:
```yml
[...]
permissions:
[...]
  backend: sql
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      uri: mysql://localhost/pex
      user: root
      password: ******
      type: sql
[...]
```

Thank you :)
Have a nice day

**Comment by zml2008** [comment]
The dev builds are a complete rewrite of PEX and SQL support has not yet been reimplemented. Don't use the dev builds yet.

**Comment by Augustin37** [comment]
okay no problem, thank you :)
