### ISSUE TITLE
Error loading backend

### ISSUE THREAD

**Issue by Dewritos** [PEXPlugins/PermissionsEx#2429]
Can someone please help me with this error?

[04:29:30] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[04:29:30] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[04:29:30] [Server thread/ERROR]: [PermissionsEx] 
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx-1.23.4.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_74]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 16, column 1:
    	- reports.report
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
	... 23 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 16, column 1:
    	- reports.report
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
	... 23 more
[04:29:30] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4

**Comment by Stormbow** [comment]
(Do not use \t(TAB) for indentation)
in 'string', line 16, column 1:
- reports.report
