### ISSUE TITLE
PermissiblePEX.calculateChildPerms

### ISSUE THREAD

**Issue by JiRt** [PEXPlugins/PermissionsEx#2461]
Hi, can you please deal with this? I do not see what it can do. Resulted in the shutdown res. Thank you

`> [15:36:52 INFO]: UUID of player Turtwig is a7d8fe2f-56ce-xxxxxxxxxxxxxxxxxxxxx
> [15:36:52 INFO]: Turtwig[/81.30.XXX.XXX:52955] logged in with entity id 478119 at ([priroda2]-256.76382477317514, 67.0, -36.700738150611926)
> [15:36:52 INFO]: [GAListener] Player: Turtwig has 0 votes
> [15:36:52 INFO]: ◀HRAC▶ Turtwig >> se k nam prave pripojil/a
> [15:36:52 WARN]: Exception in thread "Craft Scheduler Thread - 653"
> [15:36:52 WARN]: org.apache.commons.lang.UnhandledException: Plugin Residence v4.4.1.1 generated an exception while executing task 60699
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:195)
at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.recalculatePermissions(PermissiblePEX.java:178)
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.recalculatePermissions(CraftHumanEntity.java:130)
at org.bukkit.permissions.Permission.recalculatePermissibles(Permission.java:168)
at org.bukkit.permissions.Permission.(Permission.java:67)
at org.bukkit.permissions.Permission.(Permission.java:35)
at com.bekvon.bukkit.residence.containers.PlayerGroup.getPermissionGroup(PlayerGroup.java:102)
at com.bekvon.bukkit.residence.containers.PlayerGroup.updateGroup(PlayerGroup.java:69)
at com.bekvon.bukkit.residence.permissions.PermissionManager.updateGroupNameForPlayer(PermissionManager.java:128)
at com.bekvon.bukkit.residence.permissions.PermissionManager.updateGroupNameForPlayer(PermissionManager.java:118)
at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener$3.run(ResidencePlayerListener.java:647)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:191)
... 15 more
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:181)
at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190)
... 19 more

> [15:36:57 INFO]: [AuthMe] Turtwig logged in!

**Comment by Stormbow** [comment]
If I'm reading that right, the Residence 4.4.1.1 plugin is not for Minecraft 1.8.x servers.  That's what's causing the error.

**Comment by JiRt** [comment]
Thank you very much sir

**Comment by zml2008** [comment]
Looks like Residence is doing permissions operations on an async task, which is not supported by bukkit or PEX -- this should be brought up with that plugin's devs.
