### ISSUE TITLE
Sponge crash on startup

### ISSUE THREAD

**Issue by snekman11** [PEXPlugins/PermissionsEx#2471]
Hi, I have tried the 2.0 and 1.0 versions of pex for sponge and my server crashes on startup every time. I am only running the spongeforge mod and this. Here is my crash report:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 16/07/16 10:38
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.AbstractMethodError: ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getDefaultData()Lorg/spongepowered/api/service/permission/SubjectData;
        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
        at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:801)
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:289)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getDefaultData()Lorg/spongepowered/api/service/permission/SubjectData;
        at net.minecraft.command.ServerCommandManager.registerDefaultPermissions(SourceFile:128)
        at net.minecraft.command.ServerCommandManager.registerCommandsList(SourceFile:139)
        at net.minecraft.command.ServerCommandManager.registerLowPriorityCommands(SourceFile:145)
        at org.spongepowered.mod.SpongeMod.onServerStarted(SpongeMod.java:272)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:800)
        ... 3 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.8.9
        Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
        Java Version: 1.8.0_91, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 774629456 bytes (738 MB) / 1425014784 bytes (1359 MB) up to 2863661056 bytes (2731 MB)
        JVM Flags: 1 total; -Xmx3G
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        FML: MCP 9.19 Powered by Forge 11.15.1.1875 5 mods loaded, 5 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{8.0.99.99} [Forge Mod Loader] (forge.jar)
        UCHIJAAAA       Forge{11.15.1.1875} [Minecraft Forge] (forge.jar)
        UCHIJAAAE       sponge{1.8.9-1890-4.2.0-BETA-1538} [SpongeForge] (spongeforge.jar)
        UCHIJAAAA       ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (permissionsex-sponge-2.0-SNAPSHOT-shaded.jar)
        Loaded coremods (and transformers):
SpongeCoremod (spongeforge.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
        Profiler Position: N/A (disabled)
        Player Count: 0 / 150; []
        Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
        Type: Dedicated Server (map_server.txt)`

**Comment by NaerenVastir** [comment]
I'm having this same issue. 


---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1566.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 7/17/16 5:06 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.AbstractMethodError: ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getDefaultData()Lorg/spongepowered/api/service/permission/SubjectData;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:801)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:289)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AbstractMethodError: ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getDefaultData()Lorg/spongepowered/api/service/permission/SubjectData;
	at net.minecraft.command.ServerCommandManager.registerDefaultPermissions(SourceFile:128)
	at net.minecraft.command.ServerCommandManager.registerCommandsList(SourceFile:139)
	at net.minecraft.command.ServerCommandManager.registerLowPriorityCommands(SourceFile:145)
	at org.spongepowered.mod.SpongeMod.onServerStarted(SpongeMod.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:800)
	... 3 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-573.22.1.el6.x86_64
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9391688 bytes (8 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 5 total; -Xmx512M -Xms512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (custom.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (custom.jar) 
	UCHIJAAAE	sponge{1.8.9-1890-4.2.0-BETA-1566} [SpongeForge] (spongeforge-1.8.9-1890-4.2.0-BETA-1566.jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.8.9-8.1.13-universal.jar) 
	UCHIJAAAA	griefprevention{1.0} [GriefPrevention] (griefprevention-1.8.9-1.0-31.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (permissionsex-sponge-2.0-SNAPSHOT-shaded.jar) 
	UCHIJAAAA	io.github.hsyyid.polis{2.6.6} [Polis] (Polis-1.8.9-2.6.8.jar) 
	UCHIJAAAA	com.gmail.trentech.pjp{0.12.2} [Project Portals] (projectportals-5.0.0-0.12.2.jar) 
	UCHIJAAAA	com.gmail.trentech.pjw{0.9.2} [Project Worlds] (projectworlds-4.2.0-0.9.2.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	totaleconomy{1.4.1} [Total Economy] (TotalEconomy-v1.4.1.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1566.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 12; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by zml2008** [comment]
You're using the 1.9+ version of PEX on a 1.8.9 server. Use build 131 or before.
