### ISSUE TITLE
Unable to connect to SQL database

### ISSUE THREAD

**Issue by liuqilili** [PEXPlugins/PermissionsEx#2497]
[02:46:52] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.3
[02:46:52] [Server thread/INFO]: [PermissionsEx] Initializing sql backend
[02:47:13] [Server thread/ERROR]: [PermissionsEx] 
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
# Details: Unable to connect to SQL database

ru.tehkode.permissions.exceptions.PermissionBackendException: Unable to connect to SQL database
    at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:118) ~[PermissionsEx-1.23.3.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.3.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561) [PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at ru.tehkode.libs.org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:112) ~[PermissionsEx-1.23.3.jar:?]
    ... 22 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_101]
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_101]
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_101]
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_101]
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
    at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
    at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
    at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
    at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
    at java.net.Socket.<init>(Unknown Source) ~[?:1.8.0_101]
    at java.net.Socket.<init>(Unknown Source) ~[?:1.8.0_101]
    at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-e489049-07c3001]
    at ru.tehkode.libs.org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.backends.sql.SQLBackend.getSQL(SQLBackend.java:245) ~[PermissionsEx-1.23.3.jar:?]
    at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:112) ~[PermissionsEx-1.23.3.jar:?]
    ... 22 more
[02:47:13] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.3

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
