### ISSUE TITLE
Pex not allowing any commands in game or console

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2508]
OK did they change the command structure or am just not doing something right?

**Comment by zml2008** [comment]
What commands have you tried? Which version of PEX? Have you read the wiki for 1.x or the getting started guide for 2.x?

**Comment by Ironic8b498** [comment]
/pex group Owner create 
/pex user Ironic_8b49 add permissions.*

either one I tried I got error in logs

`[22:51:42] [Craft Scheduler Thread - 16/WARN]: Exception in thread "Craft Scheduler Thread - 16" 
[22:51:42] [Craft Scheduler Thread - 16/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.2 generated an exception while executing task 29
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at me.armar.plugins.autorank.permissions.handlers.VaultPermissionsHandler.getPlayerGroups(VaultPermissionsHandler.java:104)
	at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:93)
	at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:54)
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:63)
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:81)
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
`

**Comment by zml2008** [comment]
That looks like an error with Autorank, not PEX. You should talk to them about the issue.

**Comment by Ironic8b498** [comment]
Ok there was no change to the commands, Thanks
