### ISSUE TITLE
[Sponge] Error quit with Bungeecoord enabled

### ISSUE THREAD

**Issue by Eufranio** [PEXPlugins/PermissionsEx#2516]
When i enabled Bungeecoord in my Sponge server, every time a player quit the server i get this error in console:

```
[20:47:49] [Server thread/INFO]: D4rkness_King lost connection: Disconnected
[20:47:49] [Server thread/INFO] [com.nguyenquyhy.spongediscord]: D4rkness_King has disconnected!
[20:47:49] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=ninja.leaping.permissionsex, name=PermissionsEx, version=2.0-SNAPSHOT-b140, source=/home/fracica/SERVIDOR/Teste/mods/PermissionsEx-Sponge.jar}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[minecraft_server.1.10.2.jar:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getUserSubjects(PermissionsExPlugin.java:295) ~[PermissionsExPlugin.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPlayerQuit(PermissionsExPlugin.java:246) ~[PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.DisconnectListener_PermissionsExPlugin_onPlayerQuit11.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:332) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:377) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2052-5.0.0-BETA-1675]
        at net.minecraft.network.NetHandlerPlayServer.onDisconnectHandler(NetHandlerPlayServer.java:613) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:802) [me.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455) [eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at ninja.leaping.permissionsex.sponge.PEXSubjectCollection.<init>(PEXSubjectCollection.java:60) ~[PEXSubjectCollection.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin$1.load(PermissionsExPlugin.java:112) ~[PermissionsExPlugin$1.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin$1.load(PermissionsExPlugin.java:109) ~[PermissionsExPlugin$1.class:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[minecraft_server.1.10.2.jar:?]
        ... 21 more

```

**Comment by Eufranio** [comment]
There is a error when loading too:

```
[20:52:13] [Netty Epoll Server IO #8/WARN] [ninja.leaping.permissionsex]: Error while loading data for user Optional[PotterCraft_]/03c81579-9839-4c0e-bf5e-2d2ece544972 during prelogin: null
java.lang.NullPointerException
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.cacheUserAsync(PermissionsExPlugin.java:205) [PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.AuthListener_PermissionsExPlugin_cacheUserAsync9.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2052-5.0.0-BETA-1675]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:102) [mg.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEventOffline(NetHandlerLoginServer.java:118) [mg.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147316_a(NetHandlerLoginServer.java:160) [mg.class:?]
        at net.minecraft.network.login.client.CPacketLoginStart.func_148833_a(SourceFile:33) [jv.class:?]
        at net.minecraft.network.login.client.CPacketLoginStart.func_148833_a(SourceFile:10) [jv.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:?]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [EpollSocketChannel$EpollSocketUnsafe.class:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [EpollEventLoop.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

```

**Comment by zml2008** [comment]
Take a look at your server's startup log, it looks like there was an error enabling PEX.

**Comment by Eufranio** [comment]
Sorry, i did a mistake in the .json file xD
