### ISSUE TITLE
[sponge] Error feedback when using "/pex rank default add group default"

### ISSUE THREAD

**Issue by 5igm** [PEXPlugins/PermissionsEx#2530]
spongeforge-1.10.2-2052-5.0.0-BETA-1679
PermissionsEx-Sponge

```
[05:04:27] [pool-2-thread-8/ERROR] [ninja.leaping.permissionsex/sponge]: Error occurred while executing command for user DeitySSS
org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "CONSTRAINT_INDEX_B ON PUBLIC.PEX_RANK_LADDERS(NAME, SUBJECT) VALUES ('default', 4, 4)"; SQL statement:
INSERT INTO pex_rank_ladders (`name`, `subject`) VALUES (?, ?) [23505-192]
    at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1208) ~[JdbcPreparedStatement.class:1.10.2-2052-5.0.0-BETA-1679]
    at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[ProxyStatement.class:1.10.2-2052-5.0.0-BETA-1679]
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:1.10.2-2052-5.0.0-BETA-1679]
    at ninja.leaping.permissionsex.backend.sql.SqlDao.lambda$setRankLadder$8(SqlDao.java:769) ~[SqlDao.class:?]
    at ninja.leaping.permissionsex.backend.sql.SqlDao.executeInTransaction(SqlDao.java:224) ~[SqlDao.class:?]
    at ninja.leaping.permissionsex.backend.sql.SqlDao.setRankLadder(SqlDao.java:748) ~[SqlDao.class:?]
    at ninja.leaping.permissionsex.backend.sql.SqlDataStore.lambda$setRankLadderInternal$7(SqlDataStore.java:287) ~[SqlDataStore.class:?]
    at ninja.leaping.permissionsex.util.Util.lambda$asyncFailableFuture$1(Util.java:93) ~[Util.class:?]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2052-5.0.0-BETA-1679]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2052-5.0.0-BETA-1679]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

```

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
