### ISSUE TITLE
[Sponge 1.8.4] PEX no longer works after I added permissions

### ISSUE THREAD

**Issue by PokeAcer549** [PEXPlugins/PermissionsEx#2531]
```java
[22:55:57 INFO] [permissionsex]: Pre-init of PermissionsEx v2.0-SNAPSHOT
[22:55:57 ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=ninja.leaping.permissionsex, name=PermissionsEx, version=2.0-SNAPSHOT, source=mods\pex-api4.jar}
java.lang.RuntimeException: Error occurred while enabling PermissionsEx
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:144) ~[PermissionsExPlugin.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_PermissionsExPlugin_onPreInit4.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-4.2.0-BETA-348]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:261) [SpongeEventManager.class:1.8.9-4.2.0-BETA-348]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:274) [SpongeEventManager.class:1.8.9-4.2.0-BETA-348]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:278) [SpongeEventManager.class:1.8.9-4.2.0-BETA-348]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:185) [SpongeImpl.class:1.8.9-4.2.0-BETA-348]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:147) [SpongeVanilla.class:1.8.9-4.2.0-BETA-348]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$0(SourceFile:60) [ko.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:98) [ko.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:421) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: ninja.leaping.permissionsex.exception.PermissionsLoadingException: While loading permissions file from config\ninja.leaping.permissionsex\permissions.json
        at ninja.leaping.permissionsex.backend.file.FileDataStore.initializeInternal(FileDataStore.java:124) ~[FileDataStore.class:?]
        at ninja.leaping.permissionsex.backend.AbstractDataStore.initialize(AbstractDataStore.java:67) ~[AbstractDataStore.class:?]
        at ninja.leaping.permissionsex.PermissionsEx.initialize(PermissionsEx.java:285) ~[PermissionsEx.class:?]
        at ninja.leaping.permissionsex.PermissionsEx.<init>(PermissionsEx.java:99) ~[PermissionsEx.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:142) ~[PermissionsExPlugin.class:?]
        ... 11 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 121 column 8
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[minecraft_server.1.8.9.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480) ~[minecraft_server.1.8.9.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[minecraft_server.1.8.9.jar:?]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseObject(GsonConfigurationLoader.java:157) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:107) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseObject(GsonConfigurationLoader.java:164) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:107) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseArray(GsonConfigurationLoader.java:147) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:110) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseObject(GsonConfigurationLoader.java:164) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:107) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseObject(GsonConfigurationLoader.java:164) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:107) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseObject(GsonConfigurationLoader.java:164) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.parseValue(GsonConfigurationLoader.java:107) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.gson.GsonConfigurationLoader.loadInternal(GsonConfigurationLoader.java:99) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:149) ~[spongevanilla-1.8.9-4.2.0-BETA-348.jar:1.8.9-4.2.0-BETA-348]
        at ninja.leaping.permissionsex.backend.file.FileDataStore.initializeInternal(FileDataStore.java:122) ~[FileDataStore.class:?]
        at ninja.leaping.permissionsex.backend.AbstractDataStore.initialize(AbstractDataStore.java:67) ~[AbstractDataStore.class:?]
        at ninja.leaping.permissionsex.PermissionsEx.initialize(PermissionsEx.java:285) ~[PermissionsEx.class:?]
        at ninja.leaping.permissionsex.PermissionsEx.<init>(PermissionsEx.java:99) ~[PermissionsEx.class:?]
        at ninja.leaping.permissionsex.sponge.PermissionsExPlugin.onPreInit(PermissionsExPlugin.java:142) ~[PermissionsExPlugin.class:?]
        ... 11 more
```
I added in a fair ton of permissions for default, moderator and developer, and this occured.

**Comment by zml2008** [comment]
There is an error in your json file's syntax. Check line 121 or the area around it.
