### ISSUE TITLE
PEX failing to start.

### ISSUE THREAD

**Issue by Mikgreg** [PEXPlugins/PermissionsEx#2607]
Hello.

We have recently run into an issue where PEX will not load up on start. We've not added any new plugins recently, nor changed any settings. The only change to its environment was that we updated our Java version a couple weeks ago but even then the issues did not begin immediately after we did that, it only started happening the other day.

It is happening across all of my servers, with different sets of plugins & environments, so we're struggling to find anything consistent that would be causing the issue.

We're running version 1.23.3 on Paperspigot version 1.8

Here's the error that's happening, we've tried re-uploading the plugin in case its corrupted but it doesn't fix the issue:

https://bluejay.pw/i/Aayq0y.png 

As well as this its worth noting that the plugin doesn't have an issue starting every time, sometimes the server will start and everything will be fine and other times the plugin doesn't load.

**Comment by zml2008** [comment]
If this is an intermittent issue, it's not PEX's problem. It seems to be some issue with your server, possibly issues with your hard drive/SSD or memory.

**Comment by MeltedLux** [comment]
This issue is actually caused by the autoupdater failing.

`[17:42:34] [Server thread/INFO]: Done (11.214s)! For help, type "help" or "?"
[17:42:35] [Thread-7/ERROR]: [PermissionsEx] The updater could not access files at: /home/invictus/lol/plugins/update
[17:42:36] [Craft Scheduler Thread - 0/INFO]: [PermissionsEx] An update to PermissionsEx v1.23.4 was downloaded and will be applied on next server launch.
`

& then on next boot:

`[17:43:21] [Server thread/ERROR]: Could not load 'plugins/PermissionsEx.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:75) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:73) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 6 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_111]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_111]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:73) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 6 more`

**Comment by Stormbow** [comment]
Do you have this same problem with PEX 1.23.4?
