### ISSUE TITLE
Permissionsex Confusing Plugin.yml error 

### ISSUE THREAD

**Issue by Skultrix** [PEXPlugins/PermissionsEx#2629]
Hello! I have been having a problem recently with loading up permissionsex. everytime I start my server permissionsex prints out an error to the console that says:
`[20:26:29] [Server thread/ERROR]: Could not load 'plugins\PermissionsEx-1.23.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	... 5 more
[20:26:29] [Server thread/ERROR]: Could not load 'plugins\SilkSpawners.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	... 5 more
[20:26:29] [Server thread/INFO]: Set PluginClassLoader as parallel capable`

**Comment by Stormbow** [comment]
Download PEX 1.23.4

**Comment by Skultrix** [comment]
I will try

**Comment by Stormbow** [comment]
Let me know how that works out.

**Comment by Stormbow** [comment]
Looks like this issue is closed.
