### ISSUE TITLE
Invalid locale format: en_us

### ISSUE THREAD

**Issue by mikroskeem** [PEXPlugins/PermissionsEx#2635]
When I do `/pex` command in game, I get "An internal error occured while attempting to perform this command" and this stack trace:
```
[17:11:17 INFO]: mikroskeem issued server command: /pex
[17:11:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pex' in plugin PermissionsEx v2.0-SNAPSHOT-b146
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1383) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
        at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[patched_1.11.2.jar:git-Paper-"49aca0c0"]
        at ninja.leaping.permissionsex.bukkit.BukkitMessageFormatter.tr(BukkitMessageFormatter.java:200) ~[?:?]
        at ninja.leaping.permissionsex.bukkit.BukkitMessageFormatter.tr(BukkitMessageFormatter.java:44) ~[?:?]
        at ninja.leaping.permissionsex.util.command.Commander.error(Commander.java:46) ~[?:?]
        at ninja.leaping.permissionsex.util.command.CommandSpec.process(CommandSpec.java:168) ~[?:?]
        at ninja.leaping.permissionsex.bukkit.PEXBukkitCommand.onCommand(PEXBukkitCommand.java:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.2.jar:git-Paper-"49aca0c0"]
        ... 15 more
```

Command seems to work fine from console.

PEX version: `v2.0-SNAPSHOT-b146`  
Server version: `This server is running Paper version git-Paper-"49aca0c0" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

**Comment by mikroskeem** [comment]
Current [temporary fix](https://github.com/mikroskeem/PermissionsEx/commit/63b0eaec4c611b6b57444c76c7b7d79af61aafb5)

**Comment by zml2008** [comment]
Hm, this seems like a recent change -- the client doesn't send the locale properly formatted. I'll see if PEX can correct the locale format so this can be worked around.
