### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by fabri2000779** [PEXPlugins/PermissionsEx#2670]
hi i have the follower problem with PEX
[12:27:30] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4[12:27:30] [Server thread/INFO]: [PermissionsEx] Initializing file backend[12:27:30] [Server thread/ERROR]: [PermissionsEx] ========== UNABLE TO LOAD PERMISSIONS BACKEND =========Your configuration must be fixed before PEX will enableDetails: Error loading permissions file!=======================================================ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file! at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.backends.file.FileBackend.(FileBackend.java:120) ~[PermissionsEx-1.23.4.jar:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_79] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_79] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_79] at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_79] at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.PermissionManager.(PermissionManager.java:67) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.4.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79] Caused by: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping in 'string', line 3, column 4: options: ^ expected , but found BlockMappingStart in 'string', line 7, column 5: permissions: ^ at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?] ... 23 more Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping in 'string', line 3, column 4: options: ^ expected , but found BlockMappingStart in 'string', line 7, column 5: permissions: ^ at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[craftbukkit-1.11.2-R0.1.jar:git-Bukkit-c1aa859] at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?] at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?] ... 23 more [12:27:30] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4

that the console said the problem is the permission file that i config but i dont understand what is the problem here is the file:
http://pastebin.com/JziTMPzX
just i want to know what is the problem there

**Comment by Stormbow** [comment]
• Your file has incorrect indentation all over the place.

• Several of your groups are missing inheritance sections.  (See line 19 of [this example](http://pastebin.com/8ZSHxauG) if a group is not inheriting permissions from otehr groups.

• Your file is missing the `schema-version: 1` line. (See the above link to find out where that goes.)

**Comment by fabri2000779** [comment]
Thanks you its work, not that all but work.

Now the file dont give me any error but the groups dont work
http://pastebin.com/sSfFZx2c

**Comment by Stormbow** [comment]
• Line 29: Remove this blank line.

After that, test the server, post again in this thread and be specific if something doesn't work as you expected.  ;)

**Comment by fabri2000779** [comment]
thanks man its work now, i have one more question, i want that in the game chat the people have a tag like member or owner and color, how can i do that? i understand that if i specify the prefix it work in the game chat but for me for example it doesnt work

thanks and sorry for my bad english

**Comment by Stormbow** [comment]
That would be handled by a chat management plugin.  Since most servers are running Spigot, they use EssentialsX for the majority of the basic server commands, and EssentialsXChat does the prefixes that you're looking for.  (Also requires Vault to be installed.)
