### ISSUE TITLE
Don't have permissions to use PEX

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2681]
OK after a few months, I'm back at this again, this time in the near future another of my plugins will work better if I have PEX 2.0. Guess what I need is list of command and perms, mostly I need to be able to use PEX commands. I have deleted old PEX folder on my test server and booted up with PEX 2.0 with my account as OP 4 it will not let me use commands. In console I was about to create a group called Owner. When I try to add perms from console it crashes server. Need to set a group so I can manually add perms, orr is there a way to import from my current PEX flat file or SQL?

**Comment by Stormbow** [comment]
@zml2008 will have to handle this one, since it's a PEX 2.x issue and PEX 2.x is still in development.

**Comment by Ironic8b498** [comment]
I would like to get a head start on getting my permissions done, since it's 2800 lines long, My first attempt to convert to PEX 2.0 was so I can have multi default groups for each server.

**Comment by zml2008** [comment]
If you have the old bukkit/pex 1.x folder structure set up (config at plugins/PermissionsEx/{config,permissions}.yml), then PEX 2 will automatically convert the configuration over to the 2.x format. The 2.0 commands and command permissions are also different -- check the [Ore page](https://ore.spongepowered.org/zml/PermissionsEx) for more details on that. If you get any crashes, please post the full stacktrace and the full command you tried -- without that information your error report is useless.

**Comment by Ironic8b498** [comment]
OK I restored my test server back before I started to figure out PEX 2.0 , this time I left PEX 1.x folder and switched out the plugins boot up server and got this error.

`[08:00:33] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT-b147
[08:00:33] [Server thread/ERROR]: [PermissionsEx] Error occurred while enabling PermissionsEx
java.io.IOException: ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMappingException: Unknown DataStore type backend
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:92) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:84) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:149) [permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMappingException: Unknown DataStore type backend
	at ninja.leaping.permissionsex.config.DataStoreSerializer.deserialize(DataStoreSerializer.java:35) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.config.DataStoreSerializer.deserialize(DataStoreSerializer.java:29) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:166) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:143) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:85) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:90) ~[permissionsex-bukkit-2.0-SNAPSHOT-shaded-%23147%20.jar:?]
	... 13 more
[08:00:33] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v2.0-SNAPSHOT-b147
`
