### ISSUE TITLE
"Invalid plugin.yml"?

### ISSUE THREAD

**Issue by Xiione** [PEXPlugins/PermissionsEx#2705]
Hello, I am currently starting my own Spigot 1.8 server.
The second time I started up my server, all pex commands and subcommands ingame and inside the console returned the "Unknown command. Type '/help' for a list of commands." message. 
One large string of text in the console log, I think, could be the reason PEX is not working:
`[08:32:57] [Server thread/ERROR]: Could not load 'plugins\PermissionsEx-1.23.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_91]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_91]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_91]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_91]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	... 5 more
[08:32:57] [Server thread/INFO]: Set PluginClassLoader as parallel capable`
Any help on this?

**Comment by Stormbow** [comment]
I believe this error means the PermissionsEx-1.23.3.jar file was corrupted when it was downloaded.

Try downloading it again from [this official download location](https://dev.bukkit.org/projects/permissionsex/files/909154) and let me know if you still get the same error.

**Comment by Xiione** [comment]
Thank you, that seems to have solved the problem!
I did download the version 1.23.3 jar from the official Bukkit page, but I was unsure of downloading version 1.23.4, since the files page says that the version only supports versions 1.9 - 1.11.
Again, thanks for the support.

**Comment by Stormbow** [comment]
Excellent!

And sorry about the file version notices on the Bukkit site.  Bukkit was originally _very_ restrictive in which versions we could assign to a file, even though a file was functional in other versions.

**Comment by Zukeow** [comment]
Help me please, I am having the same problem, and is that every time I put the permissionsEx everything works fine and everything, but when I start the server again I get the following error and I do not know how to solve it, if they help me I would appreciate them heart.


ERROR Could not load 'plugins/PermissionsEx-1.23.3.jar' in folder 'plugins'


I already try to re-install the plugin as they say in this post but it just does not work for me, and it's very stressful, I'm new to this and I stress very fast.
