### ISSUE TITLE
UNABLE TO LOAD PERMISSIONS BACKEND

### ISSUE THREAD

**Issue by Bradisswag** [PEXPlugins/PermissionsEx#2706]
If I could get some help, that would be much appreciated.
I am currently setting up a server from scratch and cant change any perms as i dont know what it would affect due to this error="UNABLE TO LOAD PERMISSIONS BACKEND".
This is what it says in my console,
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
        at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx-1.23.4.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-4448a7e]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit.jar:git-Bukkit-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-4448a7e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 46, column 11:
      Skittles:
              ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
        ... 23 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 46, column 11:
      Skittles:
              ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[craftbukkit.jar:git-Bukkit-4448a7e]
        at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
        ... 23 more
[19:49:27 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4

If i could have some help, that would be much appreciated.

**Comment by Bradisswag** [comment]
I am pretty sure this is the issue,

        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 47, column 11:
      Skittles:
                 ^

**Comment by zml2008** [comment]
Yep, it's a syntax error in your permissions.yml.

**Comment by Stormbow** [comment]
Sorry.  I could have sworn I replied to this ticket.

**Comment by TnTGamesTV** [comment]
Every time you see something like _org.bukkit.configuration.InvalidConfigurationException_ you know that it's time for a check. Use [YamlLint](http://yamllint.com/) or something similar and they will help you.

**mapping values are not allowed here in 'string', line 47, column 11:** means, that you forgot some spaces.
E.g.:
SomethingA:
  SomethingUnderA:
  **SomethingB:**
    SomethingUnderB:

Needs to be:
SomethingA:
  SomethingUnderA:
SomethingB:
  SomethingUnderB:

~TnTGames

**Comment by Bradisswag** [comment]
@TnTGamesTV Could you please explain this? I can't find what's wrong
it says "(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1"
I tried to make the first letter a capital, but that didn't work. Here is a screen shot=
https://gyazo.com/9a0c4dbb29a3f0c3c50b9506ae1070d4

**Comment by Stormbow** [comment]
Ticket closed, per @Bradisswag.
