### ISSUE TITLE
MySQL backend - Unknown column 'prefix' in 'field list' on load

### ISSUE THREAD

**Issue by TnTGamesTV** [PEXPlugins/PermissionsEx#2709]
I'm hosting a network containing three spigot server (one game server, one lobby server, and one backend server) and of course a bungeecord proxy server. Because I switched to this network, I wanted PEX to use a database as backend. 
Before starting the whole network, I started our other server and changed the backend to MySQL, to transfer the permissions and groups. Everything worked fine and no errors were thrown around. After the transfer, I stopped the server and started the backend server. I installed a fresh version of PEX (for 1.8) and changed the config.yml to a config.yml with MySQL backend. After reloading the server, PEX connects to our database and throws the following error. It has something to do with the query PEX is executing against the database on load, but of course, I'm not the developer.

**EDIT:**
I've tested all three servers, and it happens on all of them. Same error (and stack trace I think).

**EDIT 2:**
Everything import seems to work. I'm getting my normal permissions, I can list the groups and so on.
I think it's something on startup, that doesn't affect something else.

Here are some information and the stack trace:
Minecraft server architecture: Spigot - 1.8 R0.1 Snapshot
plugins: MultiVerse (on all of them), Master (on the backend), A game (obviously on the game server), and the lobby server has nothing special.
Server type: vServer
Server architecture: Ubuntu

Stack trace:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
  at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
  at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
  at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
  at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
  at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
  at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
  at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
  at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
  at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:746)
  at org.bukkit.Bukkit.reload(Bukkit.java:534)
  at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
  at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
  at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
  at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
  at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
  at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
  at com.mysql.jdbc.Util.getInstance(Util.java:382)
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
  at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
  at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
  ... 29 more

~TnTGamesTV

**Comment by TnTGamesTV** [comment]
Uhm. The issue is not solved but makes no difference at all. All permissions are loaded correctly and everyone has his correct group (and permissions).
