### ISSUE TITLE
unfriendly exceptions thrown when curse is down

### ISSUE THREAD

**Issue by smmmadden** [PEXPlugins/PermissionsEx#2736]
If there is a hard dependency to curse website for something, we don't need to have such a large traceback.  The first two messages are fine.  Then provide an option to manually complete the step it was trying to do.  Hard to tell here if the server is stable or not when this happens.

[21:11:38 ERROR]: [PermissionsEx] The updater could not contact dev.bukkit.org for updating.
[21:11:38 ERROR]: [PermissionsEx] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[21:11:38 ERROR]: [PermissionsEx] null
java.io.IOException: Server returned HTTP response code: 521 for URL: https://api.curseforge.com/servermods/files?projectIds=31279
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_112]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_112]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_112]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.read(Updater.java:643) [PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.runUpdater(Updater.java:718) [PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.access$100(Updater.java:36) [PermissionsEx-1.23.4.jar:?]
        at ru.tehkode.libs.net.gravitydevelopment.updater.Updater$UpdateRunnable.run(Updater.java:713) [PermissionsEx-1.23.4.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]

**Comment by Stormbow** [comment]
Are you still getting that error message?  The link/URL appears valid, so it may have just been Curse being Curse and fubar for a while.

**Comment by smmmadden** [comment]
I did a reload on all the servers and it looks like the site is back up.  All the years I've been in Minecraft world, I haven't seen that exception.  What exactly is it being used for or needing a dependency to it?

**Comment by zml2008** [comment]
That's the PEX updater -- it's actually an external library we use to check BukkitDev for new versions of PEX, so we all we can really do is report the issue to [gravitylow/Updater](https://github.com/gravitylow/Updater).

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
