### ISSUE TITLE
I'm not quite sure why but Perrmissons Ex wont work at all

### ISSUE THREAD

**Issue by gumguy99** [PEXPlugins/PermissionsEx#2738]
Here is my server log
```
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4%20(1).jar:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-7d78b81-270755d]
at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4%20(1).jar:?]
at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4%20(1).jar:?]
... 23 more
[21:43:42] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[21:43:42] [Server thread/INFO]: [ClearLag] Enabling ClearLag v2.9.3
[21:43:42] [Server thread/INFO]: [ClearLag] Loading modules...
[21:43:42] [Server thread/INFO]: [ClearLag] Modules enabed, loading config values
[21:43:42] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[21:43:42] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[21:43:42] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.5;4651611
[21:43:42] [Thread-8/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.11]...
[21:43:42] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[21:43:42] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_11_R1 as the Bukkit adapter
[21:43:42] [Server thread/INFO]: [Ram_Monitor] Enabling Ram_Monitor v1
[21:43:42] [Server thread/INFO]: [Ram Monitor] Listening on 67.202.109.126:1304
[21:43:42] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b370
[21:43:42] [Thread-8/INFO]: [ClearLag] No updates found!
[21:43:42] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsChat to the same version.
[21:43:42] [Server thread/INFO]: Using locale en_US
[21:43:42] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[21:43:43] [Server thread/INFO]: [Essentials] Using legacy item data provider as spawn egg provider.
[21:43:43] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[21:43:43] [Server thread/INFO]: Using locale en_US
[21:43:43] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
[21:43:43] [Server thread/WARN]: [Essentials] Detected supported permissions plugin PermissionsEx without Vault installed.
[21:43:43] [Server thread/WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[21:43:43] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[21:43:43] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[21:43:43] [Server thread/WARN]: §4Version mismatch! Please update all Essentials jars to the same version.
[21:43:43] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:43:43] [Server thread/INFO]: Done (4.578s)! For help, type "help" or "?"
[21:43:43] [Server thread/INFO]: Starting GS4 status listener
[21:43:43] [Server thread/INFO]: Starting remote control listener
```

And here is everything in my Permissions file
```yaml
groups:
  Member:
    default: true
    prefix: '&2[&aMember&2]&7 '
    build: true
    permissions:
    - essentials.help
    - essentials.rules
    - essentials.motd
    - essentials.afk
    - essentials.back
    - essentials.back.ondeath
    - essentials.delhome
    - essentials.help
    - essentials.home
    - essentials.kit
    - essentials.kit.start
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.r
    - essentials.rules
    - essentials.sethome
    - essentials.signs.use.disposal
    - essentials.spawn
    - essentials.suicide
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
  Shiny:
    default: false
    prefix: '&6[&eShiny&6]&f '
    inheritance:
    - Guest
    - Member
    build: true
    permissions:
    - kit.shiny
    - essentials.help
    - essentials.rules
    - essentials.motd
    - essentials.nick
    - essentials.hat
  Mod:
    default: false
    prefix: '&2[&2Mod&2]&7 '
    inheritance:
    - Shiny
    - Member
    - Guest
    build: true
    permissions:
    - essentials.sethome.multiple.staff
    - essentials.helpop
    - essentials.home.others
    - essentials.nick
    - essentials.warp
    - essentials.warp.list
    - essentials.kick
  Admin:
    default: false
    prefix: '&4[&4Admin&4]&8 '
    inheritance:
    - Mod
    - Shiny
    - Member
    - Guest
    build: true
    permissions:
    - essentials.gamemode
    - essentials.give
    - essentials.god
	- essentials.ban
  Owner:
    default: false
    prefix: '&c[&9Owner&c]&3 '
    build: true
    permissions:
    - '*'
users:
  gumguy99:
    group:
    - Owner
  no_one_yet:
    group:
    - Admin
```

Also, I'm using a website to host my server it's called Fluctis here are all of my plugins/file locations screenshots
https://gyazo.com/60d3b29a7adb6b4a8c6d1fcc76664493
https://gyazo.com/289830839a70bd0a8b2ebe4873532733
https://gyazo.com/72218d258f7c869aeb6c8df87d7e7791
https://gyazo.com/e9ebf5bf6ee6cb1478d8ca7318fdcbfd
https://gyazo.com/e830ef34c38661fae276e515b0538cab
https://gyazo.com/5a1b68b72262f7fc584891f575f8be15

If anyone can help me on this it will be definitely appreciated Thank you :)

P.s. I did not modify the config just incase thats important

**Comment by zml2008** [comment]
Looks like a syntax error in your configuration -- take a look at the last permission in the Admin group. Make sure the indentation is the same and the tab character isn't present anywhere.

**Comment by Stormbow** [comment]
> [21:43:42] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsChat to the same version.

• Your server host is providing you with the wrong Essentials plugin files.  If you're running a [Spigot](https://www.spigotmc.org/) server, you'll want to remove the Essentials files your server host is providing, download the [EssentialsX](http://ci.drtshock.net/job/essentialsx/) files— specifically the EssentialsX-2.0.1.jar and EssentialsXChat-2.0.1.jar files —and upload those to your server.

----

• Each of your groups needs the `options:` settings under an `options;` section, as you see in [this example](http://pastebin.com/8ZSHxauG).

• `essentials.ban` in the "Admin" group needs its indentation corrected.

---- 

After making the above corrections, test the server and post here again if there are any continuing or additional problems.

**Comment by gumguy99** [comment]
Thank you so much !!!

**Comment by Stormbow** [comment]
You're welcome.  Feel free to post here again if you run into any other PEX problems.
