### ISSUE TITLE
The Jar file always broken after the server shut down

### ISSUE THREAD

**Issue by JeremyZhang2002** [PEXPlugins/PermissionsEx#2778]
I am currently using Java 8 and Cent OS 6.9 with PaperSpigot.
But the pex jar file seems like usually broken off after the server shut down. So I have to do the chmod 444 to fix it now. Can u fix it from the aspect of the plugin? It is really annoying or are there any problem when I am using the plugin? I am using the version 1.23.3 and minecraft version 1.8.9! Thanks a lot! btw i am Chinese who is not a English native speaker. Maybe there are some problems in describing the problem. If you have any questions about the bug let me know. :D

[18:53:13 ERROR]: Could not load 'plugins/PermissionsEx-1.23.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[PaperSpigot1.8.8.jar:git-PaperSpigot-440]
        ... 5 more

**Comment by Stormbow** [comment]
Do you have the same problem when you use [PEX 1.23.4](https://dev.bukkit.org/projects/permissionsex/files/909154)?

**Comment by JeremyZhang2002** [comment]
I didn't try it. Because on the download page it says it is for 1.7

**Comment by Stormbow** [comment]
That website doesn't let us list all the versions of Minecraft that plugins will work on.

Did you try it?

**Comment by JeremyZhang2002** [comment]
okay, i will try it.
btw thx for ur great plugin! itz really helpful! :D

**Comment by zml2008** [comment]
if you still have issues, try disabling the autoupdater in PEX's config.yml. My suspicion is that the autoupdater is trying to download an invalid file of some sort that overwrites the PEX jar.
