### ISSUE TITLE
[Very Common SQL Issue] Unknown column 'prefix' in 'field list'

### ISSUE THREAD

**Issue by BrainRTP** [PEXPlugins/PermissionsEx#2785]
I have error. Help me please.
[11:58:59] [pool-9-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
	at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
	at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
	... 24 more

**Comment by Stormbow** [comment]
I believe this issue has been reported hundreds of times and the solution is to look through your database and ensure that there is only one entry for `schema-version: 1`.

**Comment by Stormbow** [comment]
@zml2008 can confirm or deny this.  I haven't used SQL in so long that I have forgotten pretty much everything about it.

**Comment by BrainRTP** [comment]
Where in SQL to add schema-version: 1?
File exists schema-version: 1 (when i import  file to MySQL)

**Comment by BrainRTP** [comment]
@Stormbow 
@zml2008  
?

**Comment by Stormbow** [comment]
Not trying to be mean here— if you don't know enough about SQL to know how to add a line to your database, why are you using SQL?

> @zml2008 can confirm or deny this solution, or you can look through the closed tickets here. I haven't used SQL in so long that I have forgotten pretty much everything about it.

That means you'll have to wait for zml to reply.  He knows more about SQL than I do.

**Comment by BrainRTP** [comment]
@zml2008 i need help!

**Comment by Stormbow** [comment]
Are you attempting to run multiple severs a la Bungeecord?

**Comment by BrainRTP** [comment]
@Stormbow 
I have SkyWars & Faction server.
And I need permission on MySQL.
All works, but at start the error constantly gets out

**Comment by Stormbow** [comment]
If you don't know how to use SQL, best not use SQL.

**Comment by Stormbow** [comment]
Woops, wrong button.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
