### ISSUE TITLE
MC 1.12-pre2 deprecated SQL class, SQL fails

### ISSUE THREAD

**Issue by Romaq** [PEXPlugins/PermissionsEx#2786]
Spigot/ MC 1.12 pre-release 2

"File" method appears to work fine, though I didn't start to load it yet.

Initially, I used "url" instead of "uri" for the config, and it correctly overwrote the values in the config file, "Do it THIS way, try again!" I changed the label to uri, made sure spaces-not-tabs as displayed by Notepad++
```yaml
  backend: sql
<config stuff>
  backends:
    sql:
      user: <correct_username>
      password: <password>
      type: sql
      uri: mysql://<someip>/<database>
```
Error log:
```
14.05 13:56:54 [Server] INFO Enabling PermissionsEx v1.23.4
14.05 13:56:54 [Server] INFO Initializing sql backend
14.05 13:56:54 [Server] WARN Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
14.05 13:56:54 [Server] INFO ========== UNABLE TO LOAD PERMISSIONS BACKEND =========
14.05 13:56:54 [Server] INFO Your configuration must be fixed before PEX will enable
14.05 13:56:54 [Server] INFO Details: Unable to connect to SQL database
14.05 13:56:54 [Server] INFO =======================================================
14.05 13:56:54 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: Unable to connect to SQL database
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:118) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
14.05 13:56:54 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
14.05 13:56:54 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
14.05 13:56:54 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx-1.23.4.jar:?]
14.05 13:56:54 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
14.05 13:56:54 [Server] INFO Caused by: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219) ~[spigot-1.12-pre2-2017-05-14a.jar:git-Spigot-429b0e3-5195487]
14.05 13:56:54 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[?:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[?:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[?:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[?:?]
14.05 13:56:54 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[?:?]
```
Going back to file method for the time being.

EDITED to complete the stack trace.

**Comment by zml2008** [comment]
The warning message is unrelated to your error. Unfortunately, you cut out the majority of the actual stacktrace for the real error so we can't help you much with that.

**Comment by Romaq** [comment]
I'll edit the message to put the stack trace in.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
