### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zikl** [PEXPlugins/PermissionsEx#2793]
The server will restart itself and discard this error

[20:46:31 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to `http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>`. Full error:
java.lang.NullPointerException
at ru.tehkode.permissions.bukkit.PermissionsEx$PlayerEventsListener.onPlayerQuit(PermissionsEx.java:461)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379)
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1063)
at net.minecraft.server.v1_11_R1.PlayerConnection.disconnect(PlayerConnection.java:245)
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:220)
at cz.GravelCZLP.Breakpoint.Breakpoint.kickPlayers(Breakpoint.java:472)
at cz.GravelCZLP.Breakpoint.Breakpoint.onDisable(Breakpoint.java:248)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345)
at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
at java.lang.Thread.run(Thread.java:745)
 
[20:46:31 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to `http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>`. Full error:
java.lang.NullPointerException
at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:220)
at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:201)
at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:53)
at ru.tehkode.permissions.bukkit.SuperpermsListener.updateAttachment(SuperpermsListener.java:39)
at ru.tehkode.permissions.bukkit.SuperpermsListener.onSystemEvent(SuperpermsListener.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
at ru.tehkode.permissions.bukkit.PermissionsEx.callEvent(PermissionsEx.java:393)
at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:697)
at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:701)
at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:659)
at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:645)
at ru.tehkode.permissions.PermissionManager.end(PermissionManager.java:668)
at ru.tehkode.permissions.bukkit.PermissionsEx.onDisable(PermissionsEx.java:290)
at cz.GravelCZLP.Breakpoint.Updater.Update.lambda$gameEnd$1(Update.java:143)
at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
at cz.GravelCZLP.Breakpoint.Updater.Update.gameEnd(Update.java:141)
at cz.GravelCZLP.Breakpoint.game.Game.endRound(Game.java:296)
at cz.GravelCZLP.Breakpoint.game.Game.second(Game.java:260)
at cz.GravelCZLP.Breakpoint.game.Game$3.run(Game.java:362)
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
at java.lang.Thread.run(Thread.java:745)

**Comment by Stormbow** [comment]
You'll need zml's help on that one.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
