### ISSUE TITLE
Unknown column 'prefix' in 'field list'

### ISSUE THREAD

**Issue by SilverJow** [PEXPlugins/PermissionsEx#2811]
Hello, i cleared my PEX tables and i created a new permissions node, the permissions are working properly but the prefixes aren't working on some servers, i get this error log:
03:20:09] [pool-16-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
	at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
	at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
	... 25 more
How can i fix this? 
Thanks for the support

**Comment by Stormbow** [comment]
I don't handle SQL errors, but I think the solution is to look through your database and you'll find you have 2 "schema-version: 1" lines.  Delete one and everything should be fine.

**Comment by SilverJow** [comment]
There is not a schema-version: 1 on the database, i searched very well, believe me 😞

**Comment by Stormbow** [comment]
Then add one.  ;-)

There should be _one_.

**Comment by Stormbow** [comment]
When you import your permissions.yml file to the database, the `schema-version: 1` line which belongs in the pex file goes into the database.

**Comment by Stormbow** [comment]
So, if your file was messed up from the beginning and you didn't have a schema line, there's your problem.  ;-)

**Comment by SilverJow** [comment]
I fixed the problem by myself, thank you ...

**Comment by SilverJow** [comment]
@Stormbow I would like to know if there's a permission to deny a user use the command /pex
For example: i want to give a friend all the permissions, with /pex user Nick add *
but i also would like to deny him to use tthe command /pex

**Comment by Stormbow** [comment]
> I fixed the problem by myself, thank you ...

No one pointed you in the right direction.  Eh?  

```
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: Nick
    group:
    - TheirGroupNameHere
    permissions:
    - -permissions.*
    - '*'
```

The wildcard `- '*'` will give them access to all other plugins on the server, including the power to change their settings completely.

**Comment by SilverJow** [comment]
Well, you are right, you pointed me in the right direction, and now i want to share this because maybe could help someone having the same problem than mine:
The problem of Unknown column 'prefix' in 'field list' can be fixed if you follos this steps:
First let's suppose that you have a mysql database like this:
INSERT INTO `permissions` (`id`, `name`, `type`, `permission`, `world`, `value`) VALUES
(1, 'VIP, 0, 'prefix', '', '&c[V]'),
(2, 'VIP', 0, 'permission.1, '', ''),
(3, 'VIP', 0, 'permission.2', '', ''),
(4, 'VIP', 0, 'permission.3', '', ''),
....
To fix this is just add the following line and change some ids:
INSERT INTO `permissions` (`id`, `name`, `type`, `permission`, `world`, `value`) VALUES
(1, 'system', 2, 'schema_version', '', '2'),
(2, 'VIP, 0, 'prefix', '', '&c[V]'),
(3, 'VIP', 0, 'permission.1, '', ''),
(4, 'VIP', 0, 'permission.2', '', ''),
(5, 'VIP', 0, 'permission.3', '', ''),
....
I just want to say thank you for the support, and i hope that this can help someone

**Comment by Stormbow** [comment]
I have no idea what you just said, but it looks SQL-ish, so— awesome and thanks for sharing the solution!  :-)
