### ISSUE TITLE
1.12 Error

### ISSUE THREAD

**Issue by Gamofinn** [PEXPlugins/PermissionsEx#2821]
Hi, I just updated my server to Spigot 1.12 running PEX 1.23.4 and I am getting this error:
`java.lang.ExceptionInInitializerError: No such field permSubs in class class me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener
	at ru.tehkode.utils.FieldReplacer.<init>(FieldReplacer.java:16)
	at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap.inject(PEXPermissionSubscriptionMap.java:48)
	at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions.<init>(RegexPermissions.java:29)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:204)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
	at me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener.enablePlugin(EventCallListener.java:60)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by Stormbow** [comment]
When does this error occur?  What was happening on the server immediately before this error appeared?  Is this error from the startup log?  (If so, display the entire startup log, on [Pastebin](http://pastebin.com).)

Ivory Kingdom has reported that PEX 1.23.4 works flawlessly on Minecraft 1.12 in [this post](http://ivorykingdom.net/showthread.php?tid=161&pid=408#pid408).

**Comment by Gamofinn** [comment]
Yes, this error is happening on startup. It is a BungeeCord server so this server (The Hub) is in offline mode.
https://pastebin.com/XKDkrsPz

**Comment by Stormbow** [comment]
If you remove the ChatEx plugin (which is based on ChatManager, which is not supported by PEX), do you still have this error appearing?

**Comment by Stormbow** [comment]
Since the error appears right in the middle of the UltraCosmetics plugin loading, I'd recommend removing UltraCosmetics to see if the error is abated also.

**Comment by Gamofinn** [comment]
Ok, I removed ChatEx and UltraCosmetics and this is what I get. This time it appeared after it was done loading.
https://pastebin.com/BdL2TG77

**Comment by Stormbow** [comment]
me.jasperjh.**animatedscoreboard**.objects.trigger.EventCallListener

Woops.  I missed this in the first post.  AnimatedScoreboard is doing it.  Is that a 1.12 plugin?

**Comment by Gamofinn** [comment]
It says it has been tested for 1.12.

**Comment by Stormbow** [comment]
Ok, you'll need to wait for the PEX author ( @zml2008 ) to have a chance to take a look at it.

**Comment by zml2008** [comment]
It looks like AnimatedScoreboard is injecting its own replacement code into the Bukkit plugin system that interferes with the more fine-grained injection PEX does to apply its permissions resolving to Bukkit's permissions system. There may be a way to work around this issue but no fix is guaranteed.

**Comment by Gamofinn** [comment]
Talked to the AnimatedScoreboard author about it and he says he will try and fix it but it will be hard.
He is: https://www.spigotmc.org/members/jasperjh.57634/

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
