### ISSUE TITLE
I don't even know what the problem is...

### ISSUE THREAD

**Issue by Ronnie0982** [PEXPlugins/PermissionsEx#2822]
Hello :I 
I really don't have a clue on what the problem is here..
I am running a 1.11.2 to 1.12 Survival server...
========================================
Full error:
java.lang.ExceptionInInitializerError: No such field permSubs in class class me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener
	at ru.tehkode.utils.FieldReplacer.<init>(FieldReplacer.java:16)
	at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap.inject(PEXPermissionSubscriptionMap.java:48)
	at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions.<init>(RegexPermissions.java:29)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:204)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener.enablePlugin(EventCallListener.java:60)
	at me.codercloud.installer.manager.PluginOverview.onDoubleClick(PluginOverview.java:45)
	at me.codercloud.installer.util.tasks.MenuTask$Click.invoke(MenuTask.java:394)
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.click(MenuTask.java:607)
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.access$10(MenuTask.java:558)
	at me.codercloud.installer.util.tasks.MenuTask.inventoryClick(MenuTask.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener.callEvent(EventCallListener.java:38)
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1849)
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33)
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10)
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
See  #2821.

**Comment by Ronnie0982** [comment]
So that means that i need to switch my PEX awesome..

**Comment by Stormbow** [comment]
Or ditch the only plugin that appears to generate the error— animatedscoreboard.  ;-)

**Comment by Ronnie0982** [comment]
Fine, but for some reason i don't have my Prefix in my chat ##IBlameItOnEssentials...

**Comment by Stormbow** [comment]
_That_, I can definitely help with— [clicky here](https://pastebin.com/eHCCcNuY). :-)

**Comment by Ronnie0982** [comment]
Awesome thanks! :)

**Comment by Stormbow** [comment]
You're welcome.  Let me know how it goes. :-)

**Comment by Ronnie0982** [comment]
You got it :)

**Comment by Ronnie0982** [comment]
Well not that good ATM...
Have no idea why and i have so many errors...

**Comment by Ronnie0982** [comment]
For some reason i need to Force a custom prefix on?

**Comment by Stormbow** [comment]
> Have no idea why and i have so many errors...

Pastebin your startup log (in full) and I can try to help with some of those.

> Force a custom prefix on?

I've never heard of that before.  What do you mean, exactly?

**Comment by Ronnie0982** [comment]
>I've never heard of that before. What do you mean, exactly?
Well, i needed to remove some of my plugins prefixes to get it to work

> Pastebin your startup log (in full) and I can try to help with some of those.

On the way

**Comment by Ronnie0982** [comment]
https://pastebin.com/CQ8Meszn

**Comment by Ronnie0982** [comment]
Maybe this:
[22:47:50 INFO]: Essentials: Using config file enhanced permissions.

**Comment by Stormbow** [comment]
It appears you're running a funky "Paper" Spigot server, but using an outdated Essentials package.  (Why don't you use the regular "Spigot" server wrapper?)

Try downloading [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) and [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (+ [Vault](http://dev.bukkit.org/bukkit-plugins/vault/)) and get those installed instead.  See if that helps with the Essentials hate you're getting.  You may have to delete the plugins\Essentials\ folder and let this new .jar file recreate it anew, so you get the full config.yml file.

**Comment by Ronnie0982** [comment]
> It appears you're running a funky "Paper" Spigot server, but using an outdated Essentials package. (Why don't you use the regular "Spigot" server wrapper?)

Well i don't know :D

>Try downloading EssentialsX and EssentialsXChat (+ Vault) and get those installed instead. See if that helps with the Essentials hate you're getting. You may have to delete the plugins\Essentials\ folder and let this new .jar file recreate it anew, so you get the full config.yml file.

I have tried that, it does gave me a EssentialsX updated error...

**Comment by Ronnie0982** [comment]
> outdated Essentials package

Do you know the link to a updated version?

**Comment by Stormbow** [comment]
> Do you know the link to a updated version?

Speaking of which...  It looks like "Paper Spigot" has been taken down; I saw a post saying there was some copyright infringement claims made against that server wrapper (maybe similar to how Craftbukkit was DMCA'd and shut down).

I'd download Spigot 1.11.2 in the link above and give that a whirl.

**Comment by Ronnie0982** [comment]
Okay, i see

**Comment by Ronnie0982** [comment]
I have a feeling that EssentialsChat don't work...

**Comment by Ronnie0982** [comment]
I am rolling back, thanks for the help and information
