### ISSUE TITLE
[PEX 2.x] 1.12 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by IsaiahPatton** [PEXPlugins/PermissionsEx#2825]
```
[00:15:42 ERROR]: Error occurred while enabling PermissionsEx v2.0-SNAPSHOT-b147 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isAssignableFrom(Lcom/google/common/reflect/TypeToken;)Z
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.serialize.TypeSerializerCollection.get(TypeSerializerCollection.java:45) ~[?:?]
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:80) ~[?:?]
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[?:?]
        at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:90) ~[?:?]
        at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:84) ~[?:?]
        at ninja.leaping.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:149) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1120]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1120]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1120]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.12.jar:git-Paper-1120]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.12.jar:git-Paper-1120]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1120]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1120]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1120]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:283) [patched_1.12.jar:git-Paper-1120]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1120]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

Paper 1.12 (git-Paper-1120, latest at this time)
PermissionsEx version 2.0-SNAPSHOT-b147

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
