### ISSUE TITLE
pex error

### ISSUE THREAD

**Issue by serif0** [PEXPlugins/PermissionsEx#2827]
### Description ###

[Insert description of issue here]
### What PEX Saw ###

**Reason:** While checking permissions -- Issue getting PEX instance?

**Stacktrace:**
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at org.bukkit.configuration.MemorySection.mapChildrenValues(MemorySection.java:733)
	at org.bukkit.configuration.MemorySection.getValues(MemorySection.java:100)
	at ru.tehkode.permissions.backends.file.FileEntity.getNode(FileEntity.java:58)
	at ru.tehkode.permissions.backends.file.FileEntity.<init>(FileEntity.java:42)
	at ru.tehkode.permissions.backends.file.FileUser.<init>(FileUser.java:39)
	at ru.tehkode.permissions.backends.FileBackend.getUser(FileBackend.java:111)
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:116)
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:135)
	at ru.tehkode.permissions.bukkit.PermissionsEx.getUser(PermissionsEx.java:201)
	at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.checkPermission(PermissiblePEX.java:135)
	at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.hasPermission(PermissiblePEX.java:116)
	at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
	at be.maximvdw.featherboard.BoardGroup.hasPermission(Unknown Source)
	at be.maximvdw.featherboard.b.a(Unknown Source)
	at be.maximvdw.featherboard.b.run(Unknown Source)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.Cr

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
