### ISSUE TITLE
Not working for 1.12

### ISSUE THREAD

**Issue by GoNelson** [PEXPlugins/PermissionsEx#2832]
Hello

I am using permissionsEx 1.23.4
and i am getting errors.

Error:
`> [06:04:38 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="
https://git.io/create">redirected</a>.</body></html>. Full error:
java.lang.ExceptionInInitializerError: No such field permSubs in class class me.jasperjh.animatedscoreboard.objects.trigger.EventCallListe
ner
    at ru.tehkode.utils.FieldReplacer.<init>(FieldReplacer.java:16)
    at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap.inject(PEXPermissionSubscriptionMap.java:48)
    at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions.<init>(RegexPermissions.java:29)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:204)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
    at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
    at me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener.enablePlugin(EventCallListener.java:60)
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
    at java.lang.Thread.run(Thread.java:745)`

Thanks for your time

**Comment by Stormbow** [comment]
This is an issue with Animated Scoreboard.  The author is aware of it and will be attempting to fix it.

See PEX Ticket #2821 for more information.
