### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by tamedkek** [PEXPlugins/PermissionsEx#2869]
?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+CONSOLE+was+executing+%2Fpex%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.RuntimeException%3A+java.lang.RuntimeException%3A+No+groups+defined.+Check+your+permissions+file.%0D%0A%09at+ru.tehkode.permissions.commands.CommandsManager.execute%28CommandsManager.java%3A121%29%0D%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onCommand%28PermissionsEx.java%3A159%29%0D%0A%09at+org.bukkit.command.PluginCommand.execute%28PluginCommand.java%3A44%29%0D%0A%09at+org.bukkit.command.SimpleCommandMap.dispatch%28SimpleCommandMap.java%3A140%29%0D%0A%09at+org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand%28CraftServer.java%3A620%29%0D%0A%09at+org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand%28CraftServer.java%3A606%29%0D%0A%09at+net.minecraft.server.v1_8_R3.DedicatedServer.aO%28DedicatedServer.java%3A372%29%0D%0A%09at+net.minecraft.server.v1_8_R3.DedicatedServer.B%28DedicatedServer.java%3A336%29%0D%0A%09at+net.minecraft.server.v1_8_R3.MinecraftServer.A%28MinecraftServer.java%3A629%29%0D%0A%09at+net.minecraft.server.v1_8_R3.MinecraftServer.run%28MinecraftServer.java%3A537%29%0D%0A%09at+java.lang.Thread.run%28Unknown+Source%29%0D%0ACaused+by%3A+java.lang.RuntimeException%3A+No+groups+defined.+Check+your+permissions+file.%0D%0A%09at+ru.tehkode.permissions.backends.FileBackend.getDefaultGroup%28FileBackend.java%3A124%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.getDefaultGroup%28PermissionManager.java%3A291%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.getDefaultGroup%28PermissionManager.java%3A280%29%0D%0A%09at+ru.tehkode.permissions.PermissionUser.getGroups%28PermissionUser.java%3A219%29%0D%0A%09at+ru.tehkode.permissions.PermissionUser.getOption%28PermissionUser.java%3A130%29%0D%0A%09at+ru.tehkode.permissions.PermissionEntity.getOptionBoolean%28PermissionEntity.java%3A294%29%0D%0A%09at+ru.tehkode.permissions.PermissionEntity.initialize%28PermissionEntity.java%3A53%29%0D%0A%09at+ru.tehkode.permissions.PermissionUser.initialize%28PermissionUser.java%3A51%29%0D%0A%09at+ru.tehkode.permissions.ProxyPermissionUser.initialize%28ProxyPermissionUser.java%3A42%29%0D%0A%09at+ru.tehkode.permissions.PermissionManager.getUser%28PermissionManager.java%3A118%29%0D%0A%09at+ru.tehkode.permissions.bukkit.commands.UserCommands.userSetGroup%28UserCommands.java%3A520%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke0%28Native+Method%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke%28Unknown+Source%29%0D%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.invoke%28Unknown+Source%29%0D%0A%09at+java.lang.reflect.Method.invoke%28Unknown+Source%29%0D%0A%09at+ru.tehkode.permissions.commands.CommandsManager%24CommandBinding.call%28CommandsManager.java%3A252%29%0D%0A%09at+ru.tehkode.permissions.commands.CommandsManager.execute%28CommandsManager.java%3A114%29%0D%0A%09...+10+more%0D%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Ausers%3A%0A++Tamed_taco_pap%3A%0A++++group%3A%0A+++++ninja%3A%0A++++++prefix%3A%27%260%5B%26cNINJA%260%5D%27%60%60%60%0A

**Comment by Stormbow** [comment]
When you start your server, can you copy everything that prints to the server console and put it on [Pastebin](http://pastebin.com), then leave the link Pastebin gives you in this thread?

**Comment by tamedkek** [comment]
https://pastebin.com/ef4yfnLE

**Comment by Stormbow** [comment]
(Your server is very old, version 1.8.8; consider running a more recent server.  Whatever you decide, be sure that all of your plugins are for the server version you're choosing.)

Look at the plugins installed on your server.  You have multiple copies of the .jar files for Essentials, PermissionsEx, WorldEdit, and WorldGuard in there.

You're also using different versions of the "Essentials" products.  Be sure that all of the "Essentials" files are for the same version of "Essentials".  In reality, "Essentials" was discontinued at Minecraft 1.8 after Bukkit/Craftbukkit was discontinued.  A Spigot user took that plugin and make "EssentialsX" for Minecraft 1.8.1 and later (through 1.12).  Server hosts frequently give you parts of "Essentials" and parts of "EssentialsX" without knowing (or caring) that they are doing so.  This is what causes the "version mismatch" that you can see on line 112 of your console log paste.

You'll need to consider getting a different chat management plugin also, because ChatManager is not supported by PEX in almost all cases.  Since you're using Essentials (well, you will be, eventually), you may want to consider using EssentialsChat/EssentialsXChat to handle your chat functions.

---

After addressing all of the above issues, test the server and if there are any errors in the console log, leave me a fresh Pastebin link for the new log, and I'll see if I can get those fixed for you too.

**Comment by Stormbow** [comment]
Massive error log from the other ticket: https://pastebin.com/GgKGVByF

**Comment by Stormbow** [comment]
Keep all issues in one ticket please.

**Comment by Stormbow** [comment]
The error log indicates that you have errors in your permissions.yml file.  Show me that file, on Pastebin.

**Comment by tamedkek** [comment]
https://pastebin.com/PsXaChKQ

**Comment by Stormbow** [comment]
Your file is out of order.  Use [this example](https://pastebin.com/8ZSHxauG) when you make your file.

**Comment by Stormbow** [comment]
Did you get all of the previous plugin duplicates deleted from the server?

**Comment by tamedkek** [comment]
Loading libraries, please wait...
[15:37:30 INFO]: Starting minecraft server version 1.8.8
[15:37:30 INFO]: Loading properties
[15:37:30 INFO]: Default game type: SURVIVAL
[15:37:30 INFO]: Generating keypair
[15:37:30 INFO]: Starting Minecraft server on *:25565
[15:37:30 INFO]: Using default channel type
[15:37:31 INFO]: This server is running CraftBukkit version git-Bukkit-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[15:37:31 ERROR]: Could not load 'plugins\KitAdder (1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Essentials
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [craftbukkit.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit.jar:git-Bukkit-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[15:37:31 ERROR]: Could not load 'plugins\PrisonMine.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PrisonSuite
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [craftbukkit.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit.jar:git-Bukkit-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[15:37:31 INFO]: [NoCheatPlus] Loading NoCheatPlus v3.15.1-RC-sMD5NET-b1084
[15:37:31 INFO]: [NoCheatPlus] onLoad: Early set up of static API, configuration, logging.
[15:37:31 INFO]: [NoCheatPlus] Logging system initialized.
[15:37:31 INFO]: [NoCheatPlus] Detected Minecraft version: 1.8.8
[15:37:31 INFO]: [WorldEdit] Loading WorldEdit v5.5.7
[15:37:31 INFO]: [Duels] Loading Duels v1.1
[15:37:31 INFO]: [ClearLag] Loading ClearLag v2.9.7
[15:37:31 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[15:37:31 INFO]: [HealSoup] Loading HealSoup v1.0
[15:37:31 INFO]: [Vault] Loading Vault v1.2.25-b320
[15:37:31 INFO]: [WorldGuard] Loading WorldGuard v5.7.5
[15:37:31 INFO]: [PaidRanks] Loading PaidRanks v1.8
[15:37:31 INFO]: [ColoredTags] Loading ColoredTags v2.1.3
[15:37:31 INFO]: [CreateYourOwnMenus] Loading CreateYourOwnMenus v0.5.9
[15:37:31 INFO]: [SimpleRegionMarket] Loading SimpleRegionMarket v3.6
[15:37:31 INFO]: [Jail] Loading Jail v2.5.0
[15:37:31 INFO]: [Vault] Enabling Vault v1.2.25-b320
[15:37:31 INFO]: [Vault][Permission] PermissionsEx found: Waiting
[15:37:31 INFO]: [Vault][Permission] SuperPermissions loaded as backup permission system.
[15:37:31 INFO]: [Vault][Chat] PermissionsEx found: Waiting
[15:37:31 INFO]: [Vault] Enabled Version 1.2.25-b320
[15:37:31 INFO]: [Vault][Permission] PermissionsEx hooked.
[15:37:31 INFO]: Preparing level "world"
[15:37:31 INFO]: Preparing start region for level 0 (Seed: 8440133092700741118)
[15:37:32 INFO]: Preparing spawn area: 73%
[15:37:32 INFO]: Preparing start region for level 1 (Seed: 8440133092700741118)
[15:37:33 INFO]: Preparing start region for level 2 (Seed: 8440133092700741118)
[15:37:33 INFO]: [NoCheatPlus] Enabling NoCheatPlus v3.15.1-RC-sMD5NET-b1084
[15:37:33 INFO]: [NoCheatPlus] McAccess set to: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[15:37:33 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.5 blocks.
[15:37:33 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.6.1 blocks.
[15:37:33 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.7.2 blocks.
[15:37:33 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.8 blocks.
[15:37:33 INFO]: [NoCheatPlus] Inventory checks: FastConsume is available, disabled InstantEat.
[15:37:33 INFO]: [NoCheatPlus] Packet level access: ProtocolLib is not available.
[15:37:34 INFO]: [NoCheatPlus] Version 3.15.1-RC-sMD5NET-b1084 is enabled.
[15:37:34 INFO]: [WorldEdit] Enabling WorldEdit v5.5.7
[15:37:34 INFO]: WEPIF: Using the Bukkit Permissions API.
[15:37:34 INFO]: [Duels] Enabling Duels v1.1
[15:37:34 INFO]: [Duels] Database up to date.
[15:37:34 INFO]: [Duels] Connected to DB
[15:37:34 INFO]: [ClearLag] Enabling ClearLag v2.9.7
[15:37:34 INFO]: [ClearLag] Loading modules...
[15:37:34 INFO]: [ClearLag] Modules enabed, loading config values
[15:37:34 INFO]: [ClearLag] Modules have been loaded!
[15:37:34 INFO]: [ClearLag] Clearlag is now enabled!
[15:37:34 INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.8]...
[15:37:34 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[15:37:34 INFO]: [PermissionsEx] Initializing file backend
[15:37:34 INFO]: [PermissionsEx] Permissions file successfully reloaded
[15:37:34 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[15:37:34 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[15:37:34 INFO]: [HealSoup] Enabling HealSoup v1.0
[15:37:34 INFO]: [WorldGuard] Enabling WorldGuard v5.7.5
[15:37:34 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world) Lava fire is blocked.
[15:37:34 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[15:37:34 INFO]: [WorldGuard] Loaded configuration for world 'world'
[15:37:34 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[15:37:34 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[15:37:34 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[15:37:34 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[15:37:34 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[15:37:34 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[15:37:34 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[15:37:34 INFO]: [WorldGuard] 3 regions loaded for 'world'
[15:37:34 INFO]: [WorldGuard] 0 regions loaded for 'world_nether'
[15:37:34 INFO]: [WorldGuard] 0 regions loaded for 'world_the_end'
[15:37:34 INFO]: [PaidRanks] Enabling PaidRanks v1.8
[15:37:34 INFO]: [PaidRanks] is now enabled
[15:37:34 INFO]: [ColoredTags] Enabling ColoredTags v2.1.3
[15:37:34 INFO]: [CreateYourOwnMenus] Enabling CreateYourOwnMenus v0.5.9
[15:37:34 INFO]: [SimpleRegionMarket] Enabling SimpleRegionMarket v3.6
[15:37:34 WARN]: [SimpleRegionMarket] MAIN.WARN.VAULT_NO_ECO
[15:37:34 INFO]: [SimpleRegionMarket] Loaded 4 template(s), 0 world(s) and 0 region(s).
[15:37:34 INFO]: [SimpleRegionMarket] The check took 0ms
[15:37:34 INFO]: [SimpleRegionMarket] Permissions loaded (PermissionsEx)
[15:37:34 INFO]: [SimpleRegionMarket] SimpleRegionMarket enabled.
[15:37:34 INFO]: [Jail] Enabling Jail v2.5.0
[15:37:35 WARN]: [Fatal Error] :1:1: Premature end of file.

[15:37:35 WARN]: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[15:37:35 WARN]:        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
[15:37:35 WARN]:        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
[15:37:35 WARN]:        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
[15:37:35 WARN]:        at com.matejdro.bukkit.jail.UpdateChecker.updateNeeded(UpdateChecker.java:34)
[15:37:35 WARN]:        at com.matejdro.bukkit.jail.Jail.onEnable(Jail.java:115)
[15:37:35 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:37:35 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[15:37:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[15:37:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
[15:37:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
[15:37:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
[15:37:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
[15:37:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
[15:37:35 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)
[15:37:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
[15:37:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:37:35 INFO]: [Jail] Loaded 1 jail zones.
[15:37:35 INFO]: [Jail] Loaded 0 prisoners.
[15:37:35 INFO]: [Jail] Loaded 0 cells.
[15:37:35 INFO]: [Jail] Notifications plugin not installed
[15:37:35 INFO]: [Jail] Jail v2.5.0 loaded!
[15:37:35 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:37:35 INFO]: Done (3.960s)! For help, type "help" or "?"
[15:37:35 INFO]: [ClearLag] No updates found!
[15:37:35 INFO]: [NoCheatPlus] Post-enable running...
[15:37:35 WARN]: [Fatal Error] :1:1: Premature end of file.

[15:37:36 INFO]: [NoCheatPlus] Post-enable finished.
[15:37:36 INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[15:37:44 INFO]: UUID of player Tamed_taco_pap is 0be58318-b94a-4530-a35e-a1639af3f954
[15:37:44 INFO]: Tamed_taco_pap[/127.0.0.1:57566] logged in with entity id 142 at ([world]-25.69999998807907, 81.50305237865902, -154.30000001192093)
[15:37:48 INFO]: <Tamed_taco_pap> ya

**Comment by Stormbow** [comment]
KitAdder is probably not for Minecraft 1.8.8, and the Jail plugin file is corrupted (needs to be downloaded again, IF it is for Minecraft 1.8.8).

**Comment by Stormbow** [comment]
• KitAdder is looking for a version of "Essentials", so Kitadder may be an outdated plugin.

• PrisonMine is looking for "PrisonSuite", and may also be an outdated plugin..

• The Jail plugin file is corrupted (needs to be downloaded again, IF it is for Minecraft 1.8.8).

**Comment by tamedkek** [comment]
https://pastebin.com/qkazSkJ1

**Comment by tamedkek** [comment]
the default no work

**Comment by Stormbow** [comment]
I don't know what is causing the error on line 109 and I don't know what line 112 is referring to, but everything else looks like it's installed correctly.  Now you just need to configure all of your plugins to do what you want them to do.

What _exactly_ does not work, and for whom does it not work?

**Comment by tamedkek** [comment]
i loged in with an alt and it wasnt guest

**Comment by Stormbow** [comment]
To resolve those problems, I'll need to see your most recent permissions.yml file.

**NOTE:**  The permissions.yml file in your server's root directory is NOT the file you should edit.  If there is anything inside that file, delete all of it, save the file, and close it.  The permissions for your server need to be entered in the PermissionsEx folder's permissions.yml file.

**Comment by Stormbow** [comment]
> i loged in with an alt and it wasnt guest

OK, show me your most recent permissions.yml file, as mentioned above.

**Comment by tamedkek** [comment]
i cant post yml folder

**Comment by Stormbow** [comment]
The file inside it.

**Comment by tamedkek** [comment]
skype?

**Comment by Stormbow** [comment]
Discord:  https://discord.gg/36tey3M

**Comment by Stormbow** [comment]
Problems solved. :-)

**Comment by tamedkek** [comment]
stormbow

**Comment by tamedkek** [comment]
can u hop on dis

**Comment by Stormbow** [comment]
I'm on my Discord now, and playing on a server.  🥇
