### ISSUE TITLE
I get this issue When I Load the server

### ISSUE THREAD

**Issue by TheSaltyPug** [PEXPlugins/PermissionsEx#2877]
`[12:57:16] [Server thread/ERROR]: Error occurred while enabling PermissionsEx v2.0-SNAPSHOT-b147 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isAssignableFrom(Lcom/google/common/reflect/TypeToken;)Z
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.serialize.TypeSerializerCollection.get(TypeSerializerCollection.java:45) ~[?:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:80) ~[?:?]
	at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[?:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:90) ~[?:?]
	at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:84) ~[?:?]
	at ninja.leaping.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:149) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-7228328-e03b1a5]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-7228328-e03b1a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[12:57:16] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.`

As far as I can tell, permissions LOAD. But I CANNOT DO COMMANDS.

**Comment by Stormbow** [comment]
Since PermissionsEx 2 hasn't been officially released yet, I haven't used it at all.

You'll need to wait for @zml2008 to reply to this thread for assistance.

**Comment by TheSaltyPug** [comment]
This is the version that was was released, like, in January... Is there still PEX 1, then, that I can download? Where? Thankfully, the actual server I run is still on 1.11.2 (this is my test/backup server) so nothing is broken, yet.

**Comment by Stormbow** [comment]
It's a dev build though, not an official release build.

[PEX 1.23.4](https://dev.bukkit.org/projects/permissionsex/files) works on Minecraft 1.7.9 through 1.12 servers.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
