### ISSUE TITLE
 Unknown column 'prefix' in 'field list'

### ISSUE THREAD

**Issue by alex456601** [PEXPlugins/PermissionsEx#2902]
[10:44:49] [pool-11-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
	at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
	at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:373)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:322)
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
	... 24 more

**Comment by Stormbow** [comment]
I believe this error means you have 2 entries of `schema-version: 1` in your database.  (There are dozens of open and closed tickets about this issue posted here.)

Check your database and let me know what you find out.

**Comment by Stormbow** [comment]
Hopefully, that'll fix the issue.  If not, you've got me stumped because I don't have enough SQL experience to really help out here.

You'll need to wait for @zml2008 to reply if the solution I offered doesn't help.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
