### ISSUE TITLE
Permissions being checked must not be null!

### ISSUE THREAD

**Issue by Magictintin98** [PEXPlugins/PermissionsEx#2973]
Please help me (Sorry for the English, i'm French)
It only happend when PATRICK_SAUVAGE is connecting
```
[22:05:37] [Server thread/ERROR]: Permission name cannot be null
java.lang.IllegalArgumentException: Permission name cannot be null
	at org.bukkit.permissions.PermissibleBase.isPermissionSet(PermissibleBase.java:50) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:135) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at me.confuser.banmanager.commands.UnbanCommand.onTabComplete(UnbanCommand.java:150) ~[BanManager.jar:?]
	at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:387) [Essentials-2.x-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabCompleteCommand(CraftServer.java:1595) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabComplete(CraftServer.java:1579) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1095) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1915) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:46) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:10) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

[22:05:39] [pool-32-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
java.lang.IllegalArgumentException: Permissions being checked must not be null!
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:227)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
	at me.confuser.banmanager.commands.UnbanCommand.onTabComplete(UnbanCommand.java:150)
	at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:387)
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135)
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabCompleteCommand(CraftServer.java:1595)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabComplete(CraftServer.java:1579)
	at net.minecraft.server.v1_8_R3.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1095)
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1915)
	at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:46)
	at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:10)
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Shiftkeyplayz** [comment]
Do you mind showing the permissions.yml please?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
