### ISSUE TITLE
PermissionsEX crashing with AnimatedScoreboard

### ISSUE THREAD

**Issue by NotAHackedCookie** [PEXPlugins/PermissionsEx#2984]
I get this error what can I do?

[13:31:29] [pool-14-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/You are being redirected.. Full error:
java.lang.ExceptionInInitializerError: No such field permSubs in class class me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener
at ru.tehkode.utils.FieldReplacer.(FieldReplacer.java:16)
at ru.tehkode.permissions.bukkit.regexperms.PEXPermissionSubscriptionMap.inject(PEXPermissionSubscriptionMap.java:48)
at ru.tehkode.permissions.bukkit.regexperms.RegexPermissions.(RegexPermissions.java:29)
at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:204)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at me.jasperjh.animatedscoreboard.objects.trigger.EventCallListener.enablePlugin(EventCallListener.java:60)
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
at java.lang.Thread.run(Thread.java:748)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
