### ISSUE TITLE
2.0-SNAPSHOT-b147 fails to start on Spigot 1.12.2

### ISSUE THREAD

**Issue by rautamiekka** [PEXPlugins/PermissionsEx#2990]
Just before reporting I updated the Server and tried again.

An Ubuntu Linux 16.04 LTS x64 running Oracle Java SE 8 Update 151 x64.

**Server version:**
```
[11:11:24 INFO]: Starting minecraft server version 1.12.2
[11:11:24 INFO]: This server is running CraftBukkit version git-Spigot-d21162c-61e0c69 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

**The error which occurs with both shaded and non-shaded:**
```
[12:14:57 INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT-b147
[12:14:58 ERROR]: Error occurred while enabling PermissionsEx v2.0-SNAPSHOT-b147 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isAssignableFrom(Lcom/google/common/reflect/TypeToken;)Z
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.serialize.TypeSerializerCollection.get(TypeSerializerCollection.java:45) ~[?:?]
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:80) ~[?:?]
        at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[?:?]
        at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:90) ~[?:?]
        at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:84) ~[?:?]
        at ninja.leaping.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:149) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
