### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jamoreq** [PEXPlugins/PermissionsEx#3035]
```
[20:05:33] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT-b155
[20:05:34] [Server thread/ERROR]: [PermissionsEx] Error occurred while enabling PermissionsEx
java.lang.IllegalArgumentException: Path plugins/PermissionsEx/permissions.json must be a file
	at ca.stellardrift.permissionsex.util.configurate.WatchServiceListener.listenToFile(config-reload.kt:130) ~[?:?]
	at ca.stellardrift.permissionsex.util.configurate.WatchServiceListener.createConfig(config-reload.kt:155) ~[?:?]
	at ca.stellardrift.permissionsex.backend.file.FileDataStore.createLoader(FileDataStore.java:102) ~[?:?]
	at ca.stellardrift.permissionsex.backend.file.FileDataStore.migrateLegacy(FileDataStore.java:146) ~[?:?]
	at ca.stellardrift.permissionsex.backend.file.FileDataStore.initializeInternal(FileDataStore.java:163) ~[?:?]
	at ca.stellardrift.permissionsex.backend.AbstractDataStore.initialize(AbstractDataStore.java:68) ~[?:?]
	at ca.stellardrift.permissionsex.PermissionsEx.initialize(PermissionsEx.java:396) ~[?:?]
	at ca.stellardrift.permissionsex.PermissionsEx.<init>(PermissionsEx.java:131) ~[?:?]
	at ca.stellardrift.permissionsex.bukkit.PermissionsExPlugin.onEnable(PermissionsExPlugin.java:163) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-183]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-183]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.14.4.jar:git-Paper-183]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by zml2008** [comment]
Thanks for testing out 2.x! It looks like there's a bug in the configuration autoreloader where it expects the permissions file to exist already -- this will be fixed in an upcoming build, but if you would like to continue working with 2.x you can create a file named `permissions.json` in the PermissionsEx configuration folder.
