### ISSUE TITLE
Having an odd issue with PEX

### ISSUE THREAD

**Issue by MattALevine** [PEXPlugins/PermissionsEx#3089]
Here's the error log I'm getting:

08.06 18:55:37 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
08.06 18:55:37 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[?:?]
08.06 18:55:37 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[?:?]
08.06 18:55:37 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
08.06 18:55:37 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
08.06 18:55:37 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
08.06 18:55:38 [Multicraft] Skipped 144 lines due to rate limit (30/s)

lmk if I should post my config file as well.

**Comment by MattALevine** [comment]
Also this section seems suspicious:

08.06 18:55:30 [Server] INFO [Economy] Essentials Economy found: Waiting
08.06 18:55:30 [Server] INFO [Permission] PermissionsEx found: Waiting
08.06 18:55:30 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
08.06 18:55:30 [Server] INFO [Chat] PermissionsEx found: Waiting
08.06 18:55:30 [Server] INFO Enabled Version 1.7.2-b107
08.06 18:55:30 [Server] INFO WEPIF: Vault detected! Using Vault for permissions

**Comment by MattALevine** [comment]
I think I found the error myself, was missing a handful of apostrophes. No errors about PEX are jumping out at me anymore in the console.
