### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrStupsi** [PEXPlugins/PermissionsEx#3094]
Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
        at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
        at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
        at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
        at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
        at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
        at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
        at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
        at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
        at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
        ... 24 more

**Comment by zml2008** [comment]
PEX v1 has been unsupported since like 2016.
