### ISSUE TITLE
Error with permissions.yml file

### ISSUE THREAD

**Issue by explodersname** [PEXPlugins/PermissionsEx#3097]
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_265]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_265]
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 228, column 39:
     ... b123-c587-3180-9614-aa425f00c61e:
                                         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx.jar:?]
	... 23 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: 
 in 'string', line 228, column 39:
     ... b123-c587-3180-9614-aa425f00c61e:
                                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx.jar:?]
	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx.jar:?]
	... 23 more
[23:34:04] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4

What should I do?

**Comment by zml2008** [comment]
1. PEX v1 is no longer supported
2. Your problem would be solved if you could learn how to read...

**Comment by explodersname** [comment]
It was actually quite a simple fix, one of our developers made a typo.
