### ISSUE TITLE
PEX 2.0: Promoting or demoting user results in java.lang.nullPointerException error

### ISSUE THREAD

**Issue by Ben569483** [PEXPlugins/PermissionsEx#3136]
When I promote or demote users I get this error in the console

> [15:45:33] [Server thread/INFO]: Error (NullPointerException) occurred while performing command task! Please see console for details: null
> [15:45:33] [Server thread/ERROR]: [PermissionsEx] Error occurred while executing command for user CONSOLE
java.lang.NullPointerException: null
at ca.stellardrift.permissionsex.bukkit.BukkitMessageFormatter.ladder(BukkitMessageFormatter.java:117) ~[?:?]
at ca.stellardrift.permissionsex.bukkit.BukkitMessageFormatter.ladder(BukkitMessageFormatter.java:43) ~[?:?]
at ca.stellardrift.permissionsex.command.RankingCommands$2.lambda$execute$2(RankingCommands.java:91) ~[?:?]
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_275]
at ca.stellardrift.permissionsex.command.RankingCommands$2.execute(RankingCommands.java:89) ~[?:?]
at ca.stellardrift.permissionsex.util.command.CommandSpec.process(CommandSpec.java:164) ~[?:?]
at ca.stellardrift.permissionsex.bukkit.PEXBukkitCommand.onCommand(PEXBukkitCommand.java:42) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:758) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:743) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-37d799b-3eb7236]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by zml2008** [comment]
This appears to be from a fairly old build of PermissionsEx v2. Commands have had quite a few changes locally, so this is no longer relevant.
