### ISSUE TITLE
Fix:

### ISSUE THREAD

**Issue by CuriousCoder1232** [PEXPlugins/PermissionsEx#3237]
### Description ###

[Insert description of issue here]
### What PEX Saw ###

**Reason:** While CONSOLE was executing /pex

**Stacktrace:**
```
java.lang.RuntimeException: java.lang.NullPointerException
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:159)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:512)
	at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
	at ru.tehkode.permissions.backends.FileBackend.getRegisteredUsers(FileBackend.java:196)
	at ru.tehkode.permissions.PermissionBackend.getUsers(PermissionBackend.java:203)
	at ru.tehkode.permissions.PermissionManager.getUsers(PermissionManager.java:144)
	at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoCompletePlayerName(PermissionsCommand.java:106)
	at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoCompletePlayerName(PermissionsCommand.java:73)
	at ru.tehkode.permissions.bukkit.commands.PromotionCommands.promoteUser(PromotionCommands.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:114)
	... 10 more
```
### PEX configuration ###
```yaml
# http://mcstats.org
opt-out: false
guid: 66ec1c2a-6edc-415b-9823-dd0ceac0f3df
debug: false
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}
```
### Permissions database ###
```yaml
 groups: 
  default:
    prefix: '&0[&1Guest&0]&3'
    default: true
    permissions: '*'
     option:
      rank: '1000'
  Trusted:
    prefix: '&9[Trusted]&3'
    inheritance:
    - default
    permissions:
    - essentials.feed
    - essentials.kit
    - login
  Jr_Mod:
    prefix: '&l&0[&4Trail_Mod&0]&r'
    inheritance:
    - default
    - Trusted
    permissions:
    - essentials.fly
    - essentials.whois
    - login
    options:
      rank: '900'
  Moderator:
    prefix: '&a[&7Moderator&a]&3'
    inheritance:
    - default
    - Trusted
    permissions:
    - essentials.gamemode
    - essentials.kick
    - essentials.me
 - login
    options:
      rank: '800'
    worlds: {}
  Super_Mod:
    prefix: '&l&4[Builder&4]&6'
    inheritance:
    - default
    - Trusted
    - Moderator
    permissions:
    - essentials.tp
    - essentials.gamemode
    options:
      rank: '700'
  Admin:
    prefix: '&b[Admin]&3'
    inheritance:
    - default
    - Moderator
    permissions:
    - '*'
    - -essentials.ban
    - -essentials.kill
    - -essentials.gamemode.others
    - -essentials.op
    - multiworld.command.flags
    - multiworld.command.spawn
   - login
    options:
      rank: '600'
  Head_Admin:
    prefix: '&6[Head_Admin]&3'
    inheritance:
    - Admin
    options:
      rank: '100'
  Co_Owner:
    prefix: '&d[Co_Owner]&e'
    permissions:
    - -essentials.op
    - multiworld.command.create
    - multiworld.command.load
    - multiworld.command.unload
    - multiworld.command.delete
    - authme.login
    users: Amogus:
    options:
      rank: '2'
   Owner:
    prefix: '&l&4[Owner&4]&6'
    inheritance:
    - default
    - Trusted
    - Moderator
    permissions:
    - essentials.tp
    - essentials.gamemode

    
  ```
.

**Comment by zml2008** [comment]
lol no

**Comment by CuriousCoder1232** [comment]
BRUHHHh its not LETtinG ME PROMotE
OR CHANGE RANKS
