### ISSUE TITLE
Issue with Giving Perms

### ISSUE THREAD

**Issue by ThomasBOIisbest** [PEXPlugins/PermissionsEx#3245]
### Description ###

[I get this error when I try to give permissions to someone.]
### What PEX Saw ###

**Reason:** While CONSOLE was executing /pex

**Stacktrace:**
```
java.lang.RuntimeException: java.lang.NullPointerException
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:159)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:512)
	at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(Unknown Source)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(Unknown Source)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
	at ru.tehkode.permissions.backends.FileBackend.getRegisteredUsers(FileBackend.java:196)
	at ru.tehkode.permissions.PermissionBackend.getUsers(PermissionBackend.java:203)
	at ru.tehkode.permissions.PermissionManager.getUsers(PermissionManager.java:144)
	at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoCompletePlayerName(PermissionsCommand.java:106)
	at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoCompletePlayerName(PermissionsCommand.java:73)
	at ru.tehkode.permissions.bukkit.commands.UserCommands.userSetGroup(UserCommands.java:520)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:114)
	... 10 more
```
### PEX configuration ###
```yaml
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}
```
### Permissions database ###
```yaml
groups:
  Member:
    prefix: '&6[&9Member&6]&7 '
    default: true
    permissions:
    - essentials.ignore
    - modifyworld.*
    - essentials.help
    - essentials.rules
    - essentials.motd
    - essentials.news
    - essentials.customtext
    - essentials.enderchest
    - essentials.afk
    - essentials.afk.auto
    - essentials.sell
    - essentials.home
    - essentials.delhome
    - essentials.spawn
    - essentials.kits.tools
    - essentials.kit
    - essentials.kits
    - essentials.pay
    - essentials.balance
    - essentials.bal
    - essentials.msg
    - essentials.msg.color
    - essentials.r
    - essentials.reply
    - essentials.mail
    - essentials.mail.send
    - essentials.ping
    - essentials.nick
    - essentials.near
    - essentials.worth
    - essentials.signs.use.free
    - essentials.signs.use.buy
    - essentials.signs.use.warp
    - essentials.balance.others
    - essentials.balancetop
    - essentials.baltop
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.back
    - essentials.back.ondeath
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.tpno
  Admin:
    prefix: '&6[&aAdmin&6]&c '
    permissions:
    - '*'
  AdAdmin:
   prefix: '&6[&5Advanced Admin&6]&c '
   permissions:
   - '*'
  HAdmin:
    prefix: '&6[&dHead Admin&6]&c '
    permissions:
    - '*'
  CoOwner:
    prefix: '&6[&cCo-Owner&6]&c '
    permissions:
    - '*'
  Owner:
    perfix: '&6[&4Owner&6]&c '
    permissions:
    - '*'
   
```
.

**Comment by zml2008** [comment]
If you haven't noticed, it's 2022 (almost 2023!).

Did you fall through some sort of crack in the space-time continuum?

**Comment by ThomasBOIisbest** [comment]
I know it 2022 and almost 2023. But, you keep not giving me a solution for this issue.

**Comment by zml2008** [comment]
You are using a Minecraft version from 2013 (almost 10 years ago!) -- unless you travel back in time to 2013, we have no plans to even think about fixing any issues from back then.

**Comment by ThomasBOIisbest** [comment]
If it was from 2013, then you should know a solution, since they fixed it like 2014 or 2013.

**Comment by zml2008** [comment]
I'm not your personal servant, and tbh I've long forgotten anything since then. Things break over time, especially around usernames since the UUID migration happened in 2014.

**Comment by ThomasBOIisbest** [comment]
When did I ever say, you were my personal servant, but I understand what you mean. I guess, I will ask my friend.

**Comment by ThomasBOIisbest** [comment]
Thanks.

**Comment by ThomasBOIisbest** [comment]
Good Day.
