### ISSUE TITLE
For some reason I could not create a group named Citizen

### ISSUE THREAD

**Issue by H644b** [PEXPlugins/PermissionsEx#3251]
### Description ###

[Insert description of issue here]
### What PEX Saw ###

**Reason:** While CONSOLE was executing /pex

**Stacktrace:**
```
java.lang.RuntimeException: java.lang.NullPointerException
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:159)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:512)
	at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(Unknown Source)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(Unknown Source)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
	at ru.tehkode.permissions.backends.file.FileEntity.getNode(FileEntity.java:48)
	at ru.tehkode.permissions.backends.file.FileEntity.<init>(FileEntity.java:42)
	at ru.tehkode.permissions.backends.file.FileGroup.<init>(FileGroup.java:38)
	at ru.tehkode.permissions.backends.FileBackend.getGroup(FileBackend.java:116)
	at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:221)
	at ru.tehkode.permissions.bukkit.commands.GroupCommands.groupCreate(GroupCommands.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
	at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:114)
	... 10 more
```
### PEX configuration ###
```yaml
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}
```
### Permissions database ###
```yaml
groups:
  default:
    default: true
    permissions:
    - modifyworld.*
  OwnerXD:
    prefix: '&6[&cOwner&6]&7'
    permissions:
    - '*'
  owner:
    prefix: '&6[&cOwner&6]&7'
  Admins:
    permissions:
    - essentials.*
    - essentials.gamemode
    - essentials.afk
    - essentials.speed
    - essentials.hat
    - essentials.give
users:
  Preeperteemer:
    permissions:
    - '*'
    options:
      group: OwnerXD
      OwnerXD: remove
      remove: OwnerXD
    group:
    - OwnerXD
    worlds:
      OwnerXD: {}
      '0': {}
  Demo:
    group:
    - Admins
  EmperorJR:
    group:
    - Admins
```

**Comment by H644b** [comment]
btw im using Pex v1.19.6 for my 1.5.2 server

**Comment by zml2008** [comment]
lmao
